GoogleChromeLabs/chromeos_smart_card_connector

common/js/src/messaging/common.js, common/js/src/messaging/message-channel-common.js, smart_card_connector_app/src/background.js
=> Added optional non-fatal default service callback for message channels

common/js/src/messaging/message-channel-pinging.js, common/js/src/messaging/mock-port.js, common/js/src/messaging/port-message-channel-unittest.js, common/js/src/messaging/port-message-channel.js
Add tests for the GoogleSmartCard.PortMessageChannel class.
=> Tests for PortMessageChannel

common/js/src/logging/logging.js
Make the code more straightforward and also handle the (potential) case
when the goog.asserts.ENABLE_ASSERTS constant is changed from its default
value.
=> Clean up logic in the fatal error emitting code

common/js/src/i18n.js, common/js/src/popup-window/client.js, smart_card_connector_app/src/_locales/en/messages.json, smart_card_connector_app/src/window-logs-exporting.js, smart_card_connector_app/src/window-main.js, smart_card_connector_app/src/window.css, smart_card_connector_app/src/window.html
* Switch translation logic from CSS::after to custom javascript
(using chrome.i18n.getMessage(textId))
=> Fixed Chromevox accessibility issues

common/js/src/logging/debug-dump.js
=> Protect the debug dump function against typical stack overflow

common/js/src/logging/debug-dump.js
Ivan, PTAL.
This ensures that debug dumping never results in throwing an exception when in Release mode.
=> Bullet-proof debug dumping code

common/make/app_building_common.mk
=> Provide a way to start the app without rebuilding it

smart_card_connector_app/src/window.html
=> Make the drag area bigger to cover the whole title

smart_card_connector_app/src/_locales/en/messages.json, smart_card_connector_app/src/window-main.js, smart_card_connector_app/src/window.css, smart_card_connector_app/src/window.html
=> Display a warning when running Connector on non-Chrome OS system

common/js/src/deferred-processor.js, third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js, third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h, third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js, third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/known-apps-registry.js, third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js, third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
=> Add docs into the client app permissions code

example_cpp_smart_card_client_app/build/Makefile, example_cpp_smart_card_client_app/src/_locales/en/messages.json, example_cpp_smart_card_client_app/src/background.js, example_cpp_smart_card_client_app/src/window.css, example_cpp_smart_card_client_app/src/window.html, example_cpp_smart_card_client_app/src/window.js
This adds all necessary boilerplate in order to show a window when the
user launches the App.
The window is currently displaying only the name of the App and the
"close" button.
=> Add a window into the example C++ app

smart_card_connector_app/src/window-devices-displaying.js
This is a pure refactoring CL; no functional changes.
=> Add comment for passed readerTracker methods

common/js/src/logging/logging.js
Use "const"/"let" instead of "@const"/"var".
=> Modernize JS in common/js/src/logging/logging.js

example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.cc
Change the built_in_pin_dialog_server.cc file in the C++ Example App
to use the toolchain-independent Value class, instead of Native Client
specific pp::Var class and related.
This contributes to the effort of migrating the
//example_cpp_smart_card_client_app App to support WebAssembly (as
tracked by #220).
=> Migrate built_in_pin_dialog_server.cc to Value

common/js/src/executable-module/emscripten-module.js
Make the GoogleSmartCard.EmscriptenModule JavaScript class inherit
from the GoogleSmartCard.ExecutableModule one, and implement all missing
abstract methods.
This makes it possible to use the EmscriptenModule instances in the
toolchain-agnostic JavaScript code that doesn't care about differences
between Native Client and Emscripten/WebAssembly. This commit
contributes to the migration effort tracked by #220.
=> Inherit JS EmscriptenModule from ExecutableModule

make-all.sh
This commit refactors the //make-all.sh script to delegate the actual
build functionality to the //Makefile script.
Besides simplifying the script and removing duplicated information about
directories to be built, this also adds support of the
Emscripten/WebAssembly builds into make-all.sh.
as tracked by #177.
=> Rewrite make-all.sh to use the top-level Makefile

third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
Change the implementation in clients_manager.cc to use the
toolchain-agnostic Value class instead of Native Client specific
primitives.
This contributes to the Emscripten/WebAssembly migration effort tracked
by #233.
=> Migrate clients_manager.cc to Value

docs/connector-app-api.md
Replace two non-inclusive terms in connector-app-api.md
=> Use inclusive language in connector-app-api.md

common/cpp/src/google_smart_card_common/external_logs_printer.cc
Refactor the common external_logs_printer.cc file to stop using
conversions to NaCl-specific structures, and switch to using the
toolchain-independent "Value" class.
Even though this external_logs_printer.cc file is compiled only under
NaCl, it's still beneficial to switch it away from the NaCl-specific
conversion routines, since it unblocks deleting the latter from the
project.
This refactoring contributes to the WebAssembly/Emscripten migration
effort tracked by #185.
=> Remove NaCl specifics from external_logs_printer

common/js/src/deferred-processor.js
Stop using the old-style Closure Compiler classes and switch to modern
ES6 classes. Code was *not* reformatted, in order to make the diff
readable; later there'll be a separate commit that'll apply clang-format.
A brief overview of the changes done here:
* Instead of declaring the class by marking a function with
"@constructor", the "class" ES6 keyword is used.
* Instead of using goog.inherits() for declaring the inheritance, the
"extends" ES6 keyword is used.
* Static properties are first defined as file-global constants and only
then copied into the class; this allows using them in the class code,
since the old-style "this.someConstant" access doesn't work anymore.
(A side note: ES6 class static properties aren't supported by Closure
Compiler yet.)
* Calls to the parent class' methods …
=> Migrate DeferredProcessor to ES6 classes

third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
Improve the ChromeUsbBackend JavaScript code to avoid throwing
exceptions when the USB API is actually unavailable.
This should never happen in production, but it does happen in the
current (early) "extension" version of the Smart Card Connector.
Also extra safety in the code won't harm anyway.
task #383.
=> Avoid exceptions on missing USB API

smart_card_connector_app/src/manifest.json.template
This adds a condition in the manifest.json.template which includes the browser_action property in case the PACKAGING build
variable is "extension".
task #379.
=> Add extension browser action for the Connector

example_js_standalone_smart_card_client_app/background.js
Enhance the "example_js_standalone_smart_card_client_app" code to also
call the SCardGetStatusChange() function, demonstrating how this
asynchronous function is used but also to be useful for our own QA
testing purposes.
=> Extend the JS example to use SCardGetStatusChange

smart_card_connector_app/src/window-about-showing.js, smart_card_connector_app/src/window-devices-displaying.js, smart_card_connector_app/src/window-help-showing.js
This PR adds some functionality to parts of the extension's main window such as events for the About and Help buttons which cause corresponding windows to be opened. As well as adding the extension version of tracking list of readers.
=> Add functionality to main window UI 

common/js/src/logging/log-buffer.js, smart_card_connector_app/src/window-logs-exporting.js, third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Fix a few places in the code to correctly work in Release mode with the
recently enabled JavaScript code minification (see #420).
=> Fix JS minification issues

common/cpp/src/google_smart_card_common/ipc_emulation.cc
Fix the WaitForInMemoryFileCanBeRead() method to actually perform
waiting when the "timeout_milliseconds" parameter is passed as a null
optional.
The bug was caused by the fact that, apparently, std::chrono's max()
method is impractical to use: waiting for such a max() timeout actually
is a no-op, because the standard library adds the timeout to the current
time, causing the integere overflow.
The fix is to revert to the older version that used two separate calls
sleep() and sleep_for() depending on the parameter passed.
This commit contributes to the WebAssembly migration effort, tracked by
issue #233.
=> Fix IPC emulation waiting with no timeout

common/js/src/popup-window/popup-opener.js, third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js, third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
This PR fixes some code formatting issues that came up from multiple edits made to the migration PR #423.
=> Fix code formatting

third_party/libusb/webport/src/libusb_js_proxy.cc
Unlike other libusb_*_transfer functions, libusb_control_transfer
returns the number of bytes actually transferred instead of
LIBUSB_SUCCESS. Fix this, as #456 broke it.
Also simplify the error handling a bit.
This commit is part of preparatory work for the WebUSB support
effort tracked by #429.
=> [usb] Fix control transfer result

third_party/libusb/webport/src/libusb_opaque_types.cc
Make sure that when multiple event loops are running, the loop that was
interested in a particular transfer (via the associated "completed"
variable) exits immediately after that transfer finishes. The
problematic scenario is when there are two threads, both running an
event loop, and one thread populates the result of the transfer that the
other thread was waiting for. When a thread misses a notification like
in that case, it'll wait until the whole transfer timeout passes before
noticing that the "completed" variable is populated.
To fix that, we trigger one additional conditional variable
notification immediately after the transfer is populated.
This bug was likely present in our code since ever, but it became more
visible once we switched synchronous transfers to asynchronous ones
(in …
=> [usb] Fix missing transfer completion event

common/cpp/src/google_smart_card_common/value_emscripten_val_conversion.cc, common/cpp/src/google_smart_card_common/value_emscripten_val_conversion_unittest.cc
Add support for conversions from the JavaScript DataView type into the
C++ Value class. The DataView was one of types that we intentionally
skipped from the original emscripten-to-Value converter, because this
type seemed too exotic to be used in our project. However, it turned out
that WebUSB uses DataView a lot, so instead of doing artificial
conversions at the WebUSB adaptor layer we're filling the gap in the
emscripten-to-Value converter.
=> [wasm] Support DataView-to-Value conversion

third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Implement these three operations in the libusb-to-WebUSB adaptor:
claimInterface, releaseInterface, resetDevice.
They are thin wrappers around WebUSB methods.
=> [usb] WebUSB {claim,release}Interface, resetDevice

third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Add implementation of bulkTransfer/interruptTransfer commands into the
libusb-to-WebUSB adaptor.
=> [usb] WebUSB bulk/interrupt transfers

third_party/libusb/webport/src/libusb-to-webusb-adaptor-unittest.js
Add unit tests for dynamic scenarios, when a device is added or removed.
Also refactor tests a bit to avoid repetitions of fake objects.
=> [usb] More listDevices tests for WebUSB

third_party/libusb/webport/src/libusb-to-webusb-adaptor-unittest.js
Add basic unit tests for the getConfigurations() method of
the LibusbToWebusbAdaptor JS class.
=> [usb] Unit test getConfigurations for WebUSB

third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js, third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Refactor the UserPromptingChecker JavaScript class to use
"async"/"await", which greatly simplifies the asynchronous code in this
code.
This contributes to the JS modernization effort tracked by #264.
=> [js] Asyncify UserPromptingChecker

.github/workflows/makefile.yml
Implement the initial workable version of the Continuous Integration,
based on GitHub Actions. The config sets up the needed OS
environment, checks out the code, initializes the toolchain (Emscripten
and NaCl) and builds the WebAssembly version of the code.
=> Initial CI config: checkout, WebAssembly builds

third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Rewrite the disabled LibusbJsProxyTest.ContextsCreation test according
to the new code structure (the test was disabled during the big rewrite
of our USB wrappers in order to support WebUSB).
=> Resurrect LibusbJsProxyTest.ContextsCreation

third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Add unit tests for the LibusbJsProxy class methods that
increment/decrement a device's reference counter.
The tests can't explicitly assert the reference counter (it's not
exposed by the standard libusb API), so if something goes wrong the test
will start corrupting memory; running it under ASan will make sure this
error would be caught.
=> Add tests for libusb device ref counter

common/make/internal/executable_building_nacl.mk
Only create nacl_io_manifest.txt in makefiles that produce executable
binaries, as opposed to makefiles that generate static libraries. The
manifest is useless for a static library and just adds unnecessary spam
into the build log.
=> Don't create nacl_io_manifest for static libs

smart_card_connector_app/src/application_unittest.cc
Add unit tests for the Connector app that verify scenarios
of plugging/unplugging a smart card reader.
=> Tests  connector adding/removing reader

common/cpp/build/tests/Makefile, common/cpp/src/google_smart_card_common/multi_string_unittest.cc
Add unit tests for //common/ multi_string C++ helpers.
=> Unit-test multi_string C++ helpers

smart_card_connector_app/src/application_unittest.cc
Add unit tests for SCardIsValidContext calls arriving from JavaScript.
=> Unit-test IsValidContext client request

smart_card_connector_app/src/application_unittest.cc
Add unit tests for SCardConnect calls arriving from JavaScript when
there's no card inserted.
=> Unit-test Connect client requests without card

smart_card_connector_app/src/application_unittest.cc
Add tests for the scenairo when one PC/SC client application tries to
hijack another client's contexts.
=> Unit-test PC/SC context isolation

third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Resurrect a unit test for the LibusbJsProxy for the scenario when the JS
side replies to the already canceled input transfer and there's a new
input transfer with the same parameters.
=> Unit-test USB input transfer rerouting

third_party/libusb/webport/src/libusb_tracing_wrapper.cc
Fix the LibusbTracingWrapper class to not leak memory when a transfer
with the LIBUSB_TRANSFER_FREE_TRANSFER flag is used.
The leak was caused by the fact that the LibusbTracingWrapper wraps
every transfer into another libusb_transfer before passing it to the
underlying implementation (to LibusbJsProxy). The idea was that the
wrapped transfer has the same parameters as the original transfer,
except for the injected callback that logs additional data. The problem
was that LibusbJsProxy doesn't know anything about the original transfer
object, hence it doesn't perform the automatic deallocation even if it
requested it via the LIBUSB_TRANSFER_FREE_TRANSFER flag.
This bug contributes to the bugfixes tracked by #685. The unit tests
that catch it are in #684.
=> Fix USB tracing wrapper mem leak w/ FREE_TRANSFER

third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Extend the libusb_js_proxy_unittest.cc file to additionally test
LibusbTracingWrapper.
We don't test the latter in isolation in its own test file, since we'd
essentially want to repeat all test cases we wrote for LibusbJsProxy.
Moreover, testing it in isolation would be weird as the test mocks would
need repeating pieces of LibusbJsProxy (e.g., "automatically delete the
transfer if LIBUSB_TRANSFER_FREE_TRANSFER is specified").
=> Unit-test LibusbTracingWrapper

common/js/src/logging/logging.js
Normally the Smart Card Connector (and examples like example_cpp App)
self-reload themselves when hitting a fatal error message in Release
mode. This change allows to suppress this by opening DevTools attached
to the background page and typing this code:
GoogleSmartCard.disableSelfReloadOnFatalError();
It's intended as a small aid for developers, in situations when they are
investigating a crash happening in the Release mode. It used to be easy
to suppress this by opening DevTools and setting the "goog.DEBUG"
constant manually, however after we enabled advanced JS optimizations
in #420 it became impossible (not only the constant name is minified,
but whole branches of unreachable code are deleted in Release mode now).
=> Allow disabling self-reload on fatal errors

third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Hide data fields in LibusbJsProxyTest in the private section, so that
tests don't use them unintentionally.
Also fix the recently added "AsyncInputControlTransferDataRerouting"
test to use |libusb()| (which is either |libusb_js_proxy_| or
|libusb_tracing_wrapper_| according to the test parameter).
=> Private data fields in libusb_js_proxy_unittest

smart_card_connector_app/src/application_unittest.cc, smart_card_connector_app/src/testing_smart_card_simulation.cc, smart_card_connector_app/src/testing_smart_card_simulation.h
Add a unit test for the SCardTransmit call from the JS side. To make the
testing closer to real-world use cases, we add a basic simulation of a
PIV card applet, and simulate the SELECT command in the test.
=> Unit-test Transmit with a fake PIV card

smart_card_connector_app/src/application_unittest.cc
Add unit test coverage for the basic scenario in SCardReconnect().
=> Unit-test Reconnect

smart_card_connector_app/src/application_unittest.cc
Add unit test coverage for the case when two clients concurrently
connect to the same reader and card. One test checks successful scenario
(when sharing is allowed), and another checks failure scenario (when one
client holds exclusive access).
=> Unit-test concurrent card connections

smart_card_connector_app/src/application_unittest.cc
Add a unit test for the basic scenario in SCardStatus method.
=> Unit-test Status PC/SC call

smart_card_connector_app/src/application_unittest.cc
Add unit test coverage for the SCardCancel method.
=> Unit-test Cancel PC/SC

smart_card_connector_app/src/application_unittest.cc
Add unit tests for the SCardControl PC/SC-Lite calls. The tests cover a few possible commands, but not all of them (e.g., not PIN pad commands).
=> Unit-test SCardControl

smart_card_connector_app/src/application_unittest.cc
Add a smoke test for the SCardSetAttrib PC/SC-Lite request.
=> Unit-test SCardSetAttrib

smart_card_connector_app/src/application_unittest.cc
Add test coverage for auto-cleanup behavior that releases all PC/SC-Lite SCARDCONTEXTs that were left by a disconnected client.
The test is is written in an suboptimal way as it spins a polling loop for waiting for an event happening on a background thread; still, even such a test is better than not having a test at all.
=> Unit-test automatic PC/SC context cleaning

common/js/src/messaging/message-channel-pinging.js
Migrate the //common/js/src/messaging/message-channel-pinging.js file from legacy Closure Compiler classes to ES6 classes.
=> Migrate MessageChannelPinging to ES6 class

smart_card_connector_app/src/chrome-api-provider.js, third_party/closure-compiler/src_additional/chrome_extensions.js, third_party/pcsc-lite/naclport/js_client/src/api.js
Add listeners for chrome.smartCardProviderPrivate.onReleaseContextRequested, onListReadersRequested, onGetStatusChangeRequested, onCancelRequested.
=> Add new listeners for chrome.smartCardProviderPrivate events

third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
This is pure refactoring commit. Reimplement the "Checker" JavaScript class using the modern ES6 class instead of the deprecated Closure Compiler classes.
=> Migrate Checker to ES6 class

third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
Add code for injecting a custom PermissionsChecker instance in tests.
=> Add test injector for PermissionsChecker

third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js, third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js, third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
=> Fix dispose called on null during ClientHandler disposal

smart_card_connector_app/src/chrome-api-provider.js
Adds logs for requests from chrome.smartCardProviderPrivate API. Requests' arguments and results will be logged in Debug mode.
=> Add logs for request processing to ChromeApiProvider

example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
bridge-integrationtest.js was occasionally flaky, complaining about uncatched errors during teardown. It turned out to be because of the test doing the teardown before the response from C++ was received (in cases when this response isn't interesting to check).
The fix is to wait until the response arrives before exiting the test. As drive-by, we also modernize the code in this test via async+await.
This commit contributes to the Emscripten integration test implementation tracked by #816, because the flakiness was very high in the Emscripten mode.
=> Fix flaky teardown errors in bridge-integrationtest

.github/workflows/makefile.yml
=> Increase timeouts for CI jobs

third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
Fix a few occurrences of unreachable code in JS code. This is found via ESLint.
This is a pure refactoring commit, part of the effort tracked by #937.
=> [js style] Fix unreachable code

third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
Delete unused variables. This is a pure refactoring commit.
This is found via ESLint. It's part of the effort tracked by #937.
=> [js style] Drop unused vars

smart_card_connector_app/src/chrome-api-jstocxxtest.js, third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Fix more semicolon issues found by ESLint.
This is part of the cleanup tracked by #937.
=> [js style] More semicolon fixes

env/.gitignore, env/initialize.sh
Install NPM as part of the env initialize.sh script.
This will be used for installing and using Eslint for linting JavaScript code in our project, as tracked by #937.
=> [js style] Install NPM into env/

env/initialize.sh
Install ESLint as part of the env initialize.sh script.
This will be used for linting JavaScript code in our project, as tracked by #937.
=> [js style] Install ESLint into env/

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Verify the JavaScript API's SCardIsValidContext() behavior.
=> [JS-to-C++ test] Test SCardIsValidContext

smart_card_connector_app/src/testing-smart-card-simulation-libusb-hook.js
Workaround spurious "UnhandledPromiseRejection" errors in JS console happening when a Libusb function failure is simulated.
The root cause seems to be the incompatibility of the goog.Promise's built-in safety guards and modern EcmaScript's await expression. The promise, when rejected, thinks that its failure wasn't checked or propagated, despite that it's what "await" does. I didn't manage to fix this broken communication, so instead this commit suppresses the broken safeguard.
This commit contributes to #869, as it's a prerequisite for adding SCardGetStatusChange() tests.
=> [JS-to-C++ test] Workaround unhandled promise error

scripts/internal/find-files-for-linting.py
Let the caller specify whether all files need to be linted, or a diff to a particular git ref needs to be considered.
This contributes to the effort tracked by #937.
=> [scripts] Pass base gitref to find-files-for-linting

scripts/internal/find-files-for-linting.py
find-files-for-linting.py ignores third-party code that we don't maintain manually within this repository.
This contributes to the effort tracked by #937.
=> [scripts] Ignore third-party code from linting

smart_card_connector_app/src/chrome-api-jstocxxtest.js, smart_card_connector_app/src/mock-chrome-api.js
Make dispatchEvent return the mock of result reporting function to make expectations checks more straightforward.
=> [chrome-api-jstocxxtest] Refactor report result check

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Test various edge cases of receiving incorrect PC/SC requests. The only thing to verify is that we don't crash.
=> [JS-to-C++] Test malformed requests

.github/actions/build-dependencies-installation/action.yml, .github/workflows/makefile.yml
Lint JavaScript code via ESLint in each Continuous Integration run.
This is part of the linting effort tracked by #937.
=> [js style] Execute ESLint in CI runs

smart_card_connector_app/src/chrome-api-jstocxxtest.js, smart_card_connector_app/src/pcsc-api-jstocxxtest.js, smart_card_connector_app/src/testing-smart-card-simulation-constants.js
Create constants for TestingSmartCardSimulation values used by js-to-cxx tests. This is a pure refactoring commit.
=> Create constants for simulation values used by js-to-cxx tests

smart_card_connector_app/src/chrome-api-jstocxxtest.js
Add test with cancelled `onGetStatusChangeRequested` request.
=> [chrome-api-jstocxxtest] Test onCancelRequested

.github/actions/build-dependencies-installation/action.yml
=> Disable pip cache in CI

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Test basic successful scenarios for the SCardConnect PC/SC function.
=> [JS-to-C++ test] Test SCardConnect success

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Test edge cases when calling SCardCancel.
=> [JS-to-C++ test] Test SCardCancel errors

common/cpp/src/public/logging/syslog/syslog.h, common/js/src/deferred-processor.js, common/js/src/extension-id.js, common/js/src/packaging.js, third_party/pcsc-lite/naclport/server/src/readerfactory_nacl.cc, third_party/pcsc-lite/naclport/server/src/sys/un.h
On all files.
Generated by "scripts/format-code.py --base=none".
=> [style] Reapply clang-format

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Test basic successful scenario for the SCardDisconnect PC/SC function.
=> [JS-to-C++ test] Test SCardDisconnect success

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Test basic successful scenario for the SCardReconnect PC/SC function.
=> [JS-to-C++ test] Test SCardReconnect success

smart_card_connector_app/src/chrome-api-provider.js
Catch errors for chrome.smartCardProviderPrivate.addListener. Those can throw on the older versions of dev channel, i.e., when chrome.smartCardProviderPrivate didn't have all the events it currently has.
=> [Web API] Catch addListener errors

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Test basic successful scenario for the SCardStatus PC/SC function.
=> [JS-to-C++ test] Test SCardStatus success

common/js/src/requesting/requester-unittest.js, common/js/src/requesting/requester.js
If sending a message failed, the Requester.postRequest() message should reject the returned promise instead of failing itself with an exception.
A real example when this can happen is when sending a message that causes a crash in an Emscripten module, because in that case the exception is bubbled up synchronously.
This is preparation for implementing a regression test for https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/issues/823.
=> JS Requester handles exceptions correctly

smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Add basic success/failure test cases for SCardGetAttrib() PC/SC function.
=> [JS-to-C++ test] Test SCardGetAttrib

common/js/src/logging/crash-loop-detection.js
Simplify asynchronous code in CrashLoopDetection using the common promisify() helper function.
=> [js promise] Use promisify in CrashLoopDetection

smart_card_connector_app/src/application_unittest.cc
Add tests for most of the currently supported attributes in SCardGetAttrib().
=> [PC/SC test] Add more SCardGetAttrib tests

smart_card_connector_app/src/application_unittest.cc
Test a few more scenarios in the SCardSetAttrib() method, adding first test cases for successful cases as well as extending the set of tests for error cases.
=> [PC/SC test] SetAttrib success and more error cases

smart_card_connector_app/src/chrome-api-jstocxxtest.js
=> [chrome-api-jstocxxtest] Test methods on already released sCardContext

third_party/ccid/patches/0004-Fix-InterruptStop-if-called-before-InterruptRead.patch, third_party/ccid/src/src/ccid_usb.c
Apply the fix that was submitted upstream:
https://github.com/LudovicRousseau/CCID/pull/116.
This fixes #1078.
=> Cherry-pick CCID fix for 10-min hang on shutdown

smart_card_connector_app/src/chrome-api-jstocxxtest.js, smart_card_connector_app/src/testing-constants.js, smart_card_connector_app/src/testing-smart-card-simulation-constants.js, third_party/pcsc-lite/naclport/common/src/constants.js
This is a pure refactoring change.
=> [chrome-api-jstocxxtest] Move constants and group tests

smart_card_connector_app/src/chrome-api-jstocxxtest.js
Add tests that calls methods using connection that was already terminated with Disconnect. Check that those will return INVALID_HANDLE. This contributes to #947.
=> [chrome-api-jstocxxtest] Add tests with terminated connection

third_party/libusb/webport/src/libusb_js_proxy.cc
Fix a rare race condition in the Libusb transfer handling code, which was leading to a use-after-free in some scenarios: this fixes #1065. Technically, the fix is "don't dereference a transfer struct after executing its callback".
The underlying root cause is that while one thread calls the transfer's callback, the other thread might already notice it and, if it's waiting for that particular transfer, destroy it. So by the time the first thread reaches the next line (the read from "transfer->flags"), the pointer can be a dangling one.
The commit doesn't add new tests, because it seems that the existing tests are sufficient for catching these kinds of bugs, even with a low probability.
=> [libusb] Fix use-after-free on transfer race cond

smart_card_connector_app/src/application_unittest.cc
Add tests that execute SCardConnect/SCardDisconnect in pattern tests that are instantiated for every card+reader combination we simulate in tests.
We also slightly change the structure of these templated tests, so that we can have a single test for such common functionality that's the same on both "regular readers" and "readers with built-in cards" (e.g., Yubikeys).
=> [PC/SC tests] Test Connect on all simulated readers

smart_card_connector_app/src/application_unittest.cc, third_party/libusb/webport/src/libusb_js_proxy.cc
Fix a use-after-free bug in our libusb_submit_transfer() implementation
(i.e., LibusbJsProxy::LibusbSubmitTransfer()). The bug was that this
function could continue reading from a libusb_transfer* pointer after
it's been placed into a shared data structure, where it can be seen,
populated and destroyed by other threads.
We also add a PC/SC test that triggered this bug with some probability
(visible on the asan_testing bot).
This fixes https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/issues/1090.
=> [libusb] Fix use-after-free in submit_transfer 

third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Change the ControlTransfersMultiThreadedStressTest's fakes to reply asynchronously from the main thread, instead of immediate synchronous replies.
This is better because it avoids reentrant recursive calls ("request1=>response1=>request2=>response2=>...") and excessive call stack usage from hundreds of nested calls. The latter is especially a problem in WebAssembly builds with debugging flags on.
In the real-world usages, this kind of reentrancy never happens because USB APIs are asynchronous.
The fix should unblock upreving to a more recent Emscripten version, as for some reason the stack usage grew in it and made the test very flaky without this fix.
=> [libusb] Avoid recursion in the stress test

smart_card_connector_app/src/application_unittest.cc, smart_card_connector_app/src/testing_smart_card_simulation.cc, smart_card_connector_app/src/testing_smart_card_simulation.h
Add Smart Card Connector unit tests for error scenarios:
* device opening failure,
* interface claiming failure,
* bulk USB transfer failure,
* bulk USB transfer returns an unexpected reply.
Additionally simulate the scenarios when these errors are transient and disappear eventually, to verify that we retry the reader initialization.
=> [pcsc] Add tests for USB error and retry scenarios

.github/workflows/makefile.yml, make-all.sh
Stop building via Native Client in CI and in local builds via `make-all.sh`.
=> [wasm] Switch App builds from NaCl to Wasm

third_party/libusb/webport/README.rst, third_party/libusb/webport/src/libusb_interface.h, third_party/libusb/webport/src/libusb_js_proxy.cc, third_party/libusb/webport/src/libusb_js_proxy.h, third_party/libusb/webport/src/libusb_js_proxy_unittest.cc, third_party/libusb/webport/src/libusb_tracing_wrapper.cc, third_party/libusb/webport/src/libusb_tracing_wrapper.h, third_party/libusb/webport/src/public/libusb_web_port_service.cc
This libusb function will be needed for new drivers we're going to add.
=> [libusb] Implement libusb_open_device_with_vid_pid

third_party/libusb/webport/README.rst, third_party/libusb/webport/src/libusb_interface.h, third_party/libusb/webport/src/libusb_js_proxy.cc, third_party/libusb/webport/src/libusb_js_proxy.h, third_party/libusb/webport/src/libusb_js_proxy_unittest.cc, third_party/libusb/webport/src/libusb_tracing_wrapper.cc, third_party/libusb/webport/src/libusb_tracing_wrapper.h, third_party/libusb/webport/src/public/libusb_web_port_service.cc
This libusb function will be needed for new drivers we're going to add.
=> [libusb] Implement libusb_get_device

smart_card_connector_app/build/Makefile
It was a harmless mistake, but caused a make warning.
=> [mv3] Fix duplicate offscreen doc makefile rule

third_party/driver-hid5021/README.google, third_party/driver-hid5021/src/ifdhandler.c
Import new version of the driver from the upstream.
=> [hid5021] Update driver to 2024-11-02

smart_card_connector_app/src/background.js, smart_card_connector_app/src/window-apps-displaying.js, smart_card_connector_app/src/window-constants.js
This replaces the approach based on injecting functions from the background page into window: this isn't compatible with MV3.
=> [mv3] Send client app list to window via messages

smart_card_connector_app/src/application_unittest.cc
Test scenarios for SCardReconnect() for switching between
SCARD_SHARE_SHARED and SCARD_SHARE_EXCLUSIVE.
=> [PC/SC test] Test reconnect with share mode change

smart_card_connector_app/src/application_unittest.cc
Test scenarios for SCardReconnect() for resetting, unpowering the card.
=> [PC/SC test] Test reconnect with reset & unpower

smart_card_connector_app/src/trusted_clients.json
Allowlist one more Citrix app as per their request.
=> Add Citrix back up build/rollback app to trusted_clients.json

smart_card_connector_app/src/manifest.json.template
This is for the extension release
=> Increase connector version to 4.0.1
