GoogleChromeLabs/chromeos_smart_card_connector

- common/js/src/messaging/message-channel-pinging.js
dispose() was called on the pinger before calling messageChannel_.dispose(),
causing the messageChannel_ to be set to null
this commit fixes #2
> Fixed a null pointer exception in Pinger code

- common/js/src/messaging/message-channel-pinging.js
When the message channel pinger detects a failure (like the wrong format of the "pong" message or the change of remote channel id), the message channel should be closed and disposed.
The previous code didn't do this really.
> Dispose message channel when pinger detects a failure

- common/js/src/requesting/request-receiver.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
Instead of failing (and reloading the whole app) when the message received from a client contains invalid data, the message channel should be disposed.
> Fix Connector App fatal failure on trying to parse an invalid message

- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_debug_dump.cc
This fixes the potential memory access violation that could occur in the debug printing code in the PC/SC-Lite client NaCl port.
The crash could happen when the SCARD_AUTOALLOCATE feature is used and the debug tracing of the executed PC/SC-Lite functions was enabled. The buggy code would try to dump the buffer contents from the address storing the buffer address (instead of dereferencing the pointer and then dumping the bytes).
BTW, this code path is used only on the client side, not on the server side - so there were no security implications for the Connector app.
The bug was discovered because of a hint from clang-tidy (the local variable containing the correct pointer was assigned, but never used).
> Fix possible crash in pcsc-lite-related debug code

- smart_card_connector_app/src/background.js
This fixes the behavior when the Connector app continued to work even
after the NaCl module was disposed of (which could result in various errors
and, generally, makes no sense).
> Emit a fatal error when the PC/SC-Lite server NaCl module destroys

- smart_card_connector_app/src/background.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
This fixes JS fatal errors that could happen when a client tried to
connect to the Connector app after the server message channel was destroyed
(e.g. because of the NaCl module crash).
The problem was that the ClientHandler class constructor could be called
with an undefined value instead of the server message channel (where the
undefined value originates from accessing a property of already disposed
NaclModule object).
> Fix PC/SC-Lite client handling error when the server is destroyed

- common/js/src/logging/debug-dump.js
Ivan, PTAL.
This hopefully fixes a intermittent problem that I observed when debug dump function failed with TypeError saying that right-hand argument of "instanceof" operator cannot be undefined. This is a pretty mysterious error - my guess was that some standard classes are not initialized by the time when the extension code starts.
> Protect debug dumping code against undefined classes

- example_js_standalone_smart_card_client_app/download-google-smart-card-client-library.py
Fix the script execution when no directory is specified.
The problem was:
$ python download-google-smart-card-client-library.py
Accessing GitHub API...
Downloading from "https://github.com/GoogleChrome/chromeos_smart_card_connector/releases/download/1.2.7.0/google-smart-card-client-library.js"...
Traceback (most recent call last):
File "download-google-smart-card-client-library.py", line 60, in <module>
main()
File "download-google-smart-card-client-library.py", line 51, in main
os.path.relpath(os.path.dirname(__file__)), OUTPUT_FILE_NAME)
File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 428, in relpath
raise ValueError("no path specified")
ValueError: no path specified
> Example: fix download script

- README.rst
macOS uses com.apple.ifdreader instead of pcscd.
> README: document how to stop com.apple.ifdreader

- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
Add Xtralogic RDP Client, stable and beta editions, to the list of known client apps
> Add Xtralogic RDP Client to the list of known client apps

- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
this will address https://github.com/rpwoodbu/mosh-chrome/issues/177
and allow users to be able to work with smartcards on mosh also
cc @vapier
> add mosh to the list of known apps

- common/js/src/container-helpers-unittest.js
- common/js/src/container-helpers.js
- test-all.sh
- third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
- third_party/pcsc-lite/naclport/server_clients_management/build/js_unittests/Makefile
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
The Connector app was incorrectly serializing the user selection data
when saving it in the local storage, in cases when the stored data
contained more than one item.
Besides corrupting the stored user selections, this bug was leading to
the app crashes and crash-restart loops, as the error was unrecoverable.
This fixes #57.
> Fix incorrect storage of user selection data

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
The Connector app shouldn't crash due to invalid data
loaded from the local storage. Errors are logged, but
invalid entries are just ignored.
This fixes #57.
> Make local storage data not crash the app

- README.rst
Debian has decomissioned alioth, replacing it by salsa.debian.org, a gitlab instance. As a result, all the CCID and PC/SC-Lite URLs are now dead.
Replace them by their apdu.fr counterparts (or the git repository in one case).
> Fix dead links

- third_party/pcsc-lite/naclport/server/build/Makefile
Compile winscard_svc.c with "-Wno-return-type" and debuglog.c with
"-Wno-format", so that the PC/SC-Lite code is able to build by the
current NaCl toolchain without warnings (any warnings are fatal).
This fixes the recent regression that prevented the code from
being compiled using the current pepper_47 SDK. Apparently, this
old SDK was updated at some point by Chromium authors without
public announcements, and the new toolchain produces compiler
warnings that were not present before.
In particular, this commit fixes the following fatal build errors:
third_party/pcsc-lite/src/src/winscard_svc.c:809:1: error:
control reaches end of non-void function
[-Werror,-Wreturn-type]
}
^
third_party/pcsc-lite/src/src/debuglog.c:196:32: error:
format specifies type 'long' but the argument has type …
> Suppress compiler warnings in PC/SC-Lite code

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
Fix the TypeError exception during the
CertificateProviderBridge.Backend disposal when the
chrome.certificateProvider API is unavailable (e.g., when the
extension is run on Linux) :
TypeError: Cannot read property 'onSignDigestRequested' of undefined
This just is a minor cleanup, since normally the Backend instance is
never disposed of - this only happens when another fatal error occurs
(e.g., when the NaCl module crashes). So this fix only avoids
emitting an additional spurious error which could hamper the
investigation of the original root cause.
> Fix error in cert provider bridge under Linux

- README.rst
- common/make/app_building_common.mk
Run the Chrome binary, in case when it's called by the build scripts
just to produce a CRX file and not to draw any UI, via the xvfb-run
binary.
This allows to build the CRX files on systems that don't have an X11
server running (e.g., remote virtual machines).
Without this change, Chrome fails with an error like this without
producing the CRX file:
Gtk-WARNING **: 12:00:00.000: cannot open display
This change is a follow-up to #69.
> Wrap Chrome --pack-extension run into Xvfb

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
Log every invocation of requestPin/stopPinRequest functions even
in Release mode, together will their input parameters and whether
the operation succeeds.
This should help in investigating bug reports in the third-party
extensions in the future.
The only piece of information that is intentionally NOT logged is
the actual PIN.
> C++ example: More verbose logging of PIN requests

- example_cpp_smart_card_client_app/src/background.js
Add code into the example C++ client app that triggers a self
reload when a fatal error with the NaCl module happens (e.g.,
when it crashes).
> C++ example: Reload app on NaCl module crash

- third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
- third_party/pcsc-lite/naclport/js_client/src/api.js
Add the implementation of logging the results of the PC/SC-Lite API
calls that are made from a NaCl module. This should aid in the
future in the investigation of bugs in third-party middleware
extensions.
The implementation is disabled by default, since even under normal
circumstances a typical smart card middleware makes dozens of
PC/SC-Lite requests per single certificates listing / signature
operation.
This additional logging can be enabled by running these snippets in
the JavaScript console of the extension's background page:
* enabling the logging of return codes:
$jscomp.scope.pcscLiteNaclClientBackend.logger.setLevel(goog.log.Level.FINE)
* additionally, enabling the dumping of all values and buffers (use
with care - this may include privacy/security-sensitive data) : …
> Allow logging the PC/SC-Lite API call results

- example_cpp_smart_card_client_app/src/background.js
- smart_card_connector_app/src/background.js
Add a bit more logging into the C++ example middleware app, to
make it slightly easier to investigate bug reports from the users
(since many users forget to specify some important information).
> C++ example: Log versions and time on startup

- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
The functionality of smart-ssh has meanwhile been integrated into the Secure Shell app. As a result, smart-ssh is now deprecated and no longer listed on the web store. I think that it is time to remove it from the list.
> Remove smart-ssh from the list of known clients

- example_js_standalone_smart_card_client_app/download-google-smart-card-client-library.py
The current code only works with Python 2.  Port it to support both
Python 2 & Python 3.
Basically we have to handle the urllib2->urllib.request rename, and
the fact that urlopen returns bytes, not strings.  This is true for
both Python versions.
> download-google-smart-card-client-library: port to Python 3

- common/cpp/src/google_smart_card_common/formatting.h
- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
- common/cpp/src/google_smart_card_common/numeric_conversions.cc
- common/cpp/src/google_smart_card_common/numeric_conversions.h
- common/cpp/src/google_smart_card_common/pp_var_utils/enum_converter.h
- common/cpp/src/google_smart_card_common/pp_var_utils/extraction.cc
- common/cpp/src/google_smart_card_common/pp_var_utils/extraction.h
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
Remove all usages of the Boost C++ library from the project.
This allows to resolve the build issues caused by some problems
with the NaCl webport of Boost:
/usr/bin/git-secrets: line 116: /usr/lib/git-core/git: Argument list too long
> Get rid of dependency on Boost

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/known-apps-registry.js
Explicitly mark the nullable type, making the style checks built into
the current version of Closure Compiler happy.
Before this CL, the following error was generated:
[JSC_MISSING_NULLABILITY_MODIFIER_JSDOC] KnownApp is a reference
type with no nullability modifier, which is disallowed by the style
guide.
Please add a ! to make it explicitly non-nullable, or a ? to make
it explicitly nullable.
> Fix type annotation in known-apps-registry.js

- common/js/src/deferred-processor.js
- common/js/src/logging/debug-dump.js
- common/js/src/logging/logging.js
- common/js/src/messaging/port-message-channel.js
- common/js/src/messaging/single-message-based-channel-unittest.js
- common/js/src/nacl-module/nacl-module.js
- common/js/src/popup-window/client.js
- common/js/src/popup-window/server.js
- common/js/src/requesting/requester-unittest.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- smart_card_connector_app/src/window-logs-exporting.js
- third_party/pcsc-lite/naclport/js_demo/src/demo.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/readiness-tracker.js
Small cleanup: stop importing things in JavaScript code that aren't used
in the code.
These unused imports were collected using the
"--jscomp_error=extraRequire" Closure Compiler flag. (We don't use this
flag by default, since it also produces lots of false positives.)
> Remove unused imports from JavaScript code

- common/make/js_building_common.mk
Update the code to work with the release 20191111 of Closure Compiler:
* The "--jscomp_error=checkEventfulObjectDisposal" diagnostics seems to
be broken in Debug builds.
> Prepare for Closure Compiler 20191111 update

- common/js/src/container-helpers.js
- common/js/src/logging/debug-dump.js
- common/js/src/logging/logging.js
- common/js/src/messaging/message-channel-pinging.js
- common/js/src/messaging/message-channel-pool.js
- common/js/src/messaging/port-message-channel.js
- common/js/src/messaging/typed-message.js
- common/js/src/nacl-module/nacl-module-log-messages-receiver.js
- common/js/src/popup-window/client.js
- common/js/src/popup-window/server.js
- common/js/src/requesting/remote-call-message.js
- common/js/src/requesting/request-receiver.js
- common/js/src/requesting/requester-message.js
- common/js/src/requesting/requester.js
- example_js_smart_card_client_app/src/background.js
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/window-apps-displaying.js
- smart_card_connector_app/src/window-devices-displaying.js
- third_party/libusb/naclport/src/chrome_usb/chrome-usb-backend.js
- third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
- third_party/pcsc-lite/naclport/js_client/src/api.js
- third_party/pcsc-lite/naclport/js_client/src/context.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/known-apps-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Update the code to work with the release 20191111 of Closure Library:
* The following functions were deprecated and trigger an error now:
+ goog.isNull,
+ goog.isDef,
+ goog.isString,
+ goog.isNumber,
+ goog.isBoolean,
+ goog.object.extend.
> Prepare for Import Closure Library 20191111 update

- env/constants.sh
Don't request the compilation of the NaCl port of the Boost C++
library in the env/initialize.sh script.
The Boost C++ library isn't used in this project anymore since
commit 4c06512.
> Skip compiling Boost naclport by default

- third_party/libusb/naclport/src/libusb_over_chrome_usb.cc
- third_party/libusb/naclport/src/libusb_over_chrome_usb.h
Close issue #90
When connecting to a reader fails, we retry connecting later.
This is done by showing another Bus number for the device.
We need to fake Bus numbers anyway as chrome.usb does not let us retrieve them.
PCSC then views it as a different device from the previous one and attempts
to connect to it once a smartcard reader needs to be accessed.
> Retry connection when initial attempt fails

- common/cpp/build/Makefile
- common/cpp/src/google_smart_card_common/external_logs_printer.cc
- common/cpp/src/google_smart_card_common/external_logs_printer.h
- common/js/src/logging/log-buffer-forwarder.js
- common/js/src/logging/log-buffer.js
- common/js/src/logging/log-formatting.js
- common/js/src/logging/logging.js
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/pp_module.cc
This makes sure that the logs that are collected on the JavaScript side
are also available in the NaCl process stderr. This should make
accessing these logs much simpler in some situations, because NaCl
process stderr is captured at /var/log/ (at least in test Chrome OS
images for non-guest users).
Before this change, the JS logs were only available via DevTools or via
the "Export logs" UI button. Neither works on Chrome OS login screen (at
least out of the box), therefore piping the logs to the log file will
simplify debugging QA/customer issues.
> Forward JS logs to NaCl stderr in Connector app

- smart_card_connector_app/src/background.js
Avoid triggering an exception when the chrome.loginState API is
unavailable. The exception was triggered due to unhandled rejection of
the ChromeLoginStateHook.getHookReadyPromise() promise.
The fix is to make sure that the promise rejection is handled by using
the then() method, instead of thenAlways() that was used before.
> Fix unhandled exception in ChromeLoginStateHook

- common/js/src/logging/log-formatting.js
- common/js/src/logging/logging.js
Having real clock times being logged will simplify understanding logs, especially in the situation when two instances of the same app work simultaneously (one inside the user session and another in the login screen profile).
> Log absolute times

- common/js/src/logging/debug-dump.js
- common/js/src/logging/log-buffer.js
Add a heuristic check that omits performing recursive dumping for
objects that inherit from goog.Disposable, since such objects are most
likely classes that aren't useful to be logged (as they are not pure
containers for data) and are expensive to be logged (as they may contain
non-trivial state).
Also, in accordance with this heuristic, make the
GoogleSmartCard.LogBuffer class inherit from goog.Disposable - since
objects of this class are one of the most heavy-weight objects in the
whole extension, and we definitely want to avoid it being debug-dumped
at any time.
> Avoid dumping non-struct classes for logging

- example_cpp_smart_card_client_app/build/nacl_module/Makefile
- example_cpp_smart_card_client_app/src/_locales/en/messages.json
- example_cpp_smart_card_client_app/src/background.js
- example_cpp_smart_card_client_app/src/pp_module.cc
- example_cpp_smart_card_client_app/src/ui_bridge.cc
- example_cpp_smart_card_client_app/src/ui_bridge.h
- example_cpp_smart_card_client_app/src/window.html
- example_cpp_smart_card_client_app/src/window.js
Extend the C++ example code with the boilerplate that allows
to send messages between the UI JavaScript code and the
NaCl module.
Also, to demonstrate the usage of the message channel,
implement the "Run test" button to trigger some trivial
sequence of PC/SC method calls.
> Implement message channel for example app UI

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
- example_cpp_smart_card_client_app/src/pp_module.cc
- example_cpp_smart_card_client_app/src/ui_bridge.cc
- example_cpp_smart_card_client_app/src/ui_bridge.h
Make the handler of the UI messages use the same mutex as the existing
chrome.certificateProvider message handler, so that they never run
concurrently. This corresponds to the typical single-threaded model of
real-world smart card middleware applications.
Also flip the default in the Example App to make the
chrome.certificateProvider message handler sequential (it was previously
controlled by a boolean flag set to false by default).
Implementation-wise, a cleaner approach than to use mutexes would be to
have a dedicated worker thread that would be used for running all
handler jobs, but it'd be a much bigger change to introduce such a
pattern into the code.
> Sequential UI commands in Example App

- third_party/libusb/naclport/build/js_unittests/.gitignore
Skip the build artifacts from being tracked in the version control
system - those files are just mental noise.
> Add gitignore for libusb JS unittests

- third_party/webports/src/src/build_tools/pip_install.sh
Work around the issue with PIP installation during "webports" "gclient
sync" command, which manifests itself as import failures when running
PIP despite it being installed just before this command.
The hack is to unset the "PYTHONNOUSERSITE" environment variable which
is set by gclient/vpython: for some reason, having this variable set
makes PIP being not found.
This is a quick hack solution, in order to unblock developers - an ideal
solution would be to find out what's wrong in the way how we install
PIP.
This fixes #115.
> Fix PIP installation in webports

- env/constants.sh
- env/initialize.sh
- third_party/webports/README.google
Change the env/initialize.sh script to use the version of the "webports"
repository that is committed and pinned under //third_party/.
This completes the fix #115, by making use of the local patch that works
around the PIP installation issue.
> Use the pinned webports repository

- common/make/nacl_module_building_common.mk
- env/.gitignore
This makes using the "make run"/"make test" commands slightly more
convenient for development/testing on a desktop OS, by reusing the same
Chrome profile directory (--user-data-dir) for all executions.
This partially solves the trouble caused by the asynchronous
installation of the NaCl component in desktop Chrome browsers, which was
manifesting in form of the following error on every run:
NaCl module load failed: The Portable Native Client (pnacl) component
is not installed.
While this commit doesn't fix the underlying issue per se, it makes this
error appear only on the first run, therefore streamlining the
developer experience.
> Workaround for NaCl init issue on desktops

- common/tests_runner/src/index.html
The header and the title in the HTML page of the NaCl test launcher were
misleading.
> Fix the headers in the NaCl code test launcher UI

- third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Move the JS code that allows to track the readers state from the
server's internal into the client directory, which allows it to be
reused in client or middleware extensions.
No functional changes were made in that code - only the internal data
format was changed (to avoid having a structure with unused fields) and
the trivial "var ==> let/const" modernization was performed.
> Extract PC/SC-based reader status tracker

- smart_card_connector_app/src/_locales/en/messages.json
- smart_card_connector_app/src/manifest.json.template
- smart_card_connector_app/src/window-help-showing.js
- smart_card_connector_app/src/window-main.js
- smart_card_connector_app/src/window.html
Add help button that opens Help Article in a new browser tab.
Closes [#45](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/issues/45).
> Add help button

- common/js/src/i18n.js
- example_cpp_smart_card_client_app/src/window.js
- smart_card_connector_app/src/_locales/en/messages.json
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/window-devices-displaying.js
- smart_card_connector_app/src/window-main.js
Gives the add-device button text value of "Add Reader" when no readers are in the list, and gives it the value "Add Another Reader" when 1 or more readers are in the list.
This is to prevent confusion as mentioned in issue #104.
> Change text on Add Reader button depending on list being empty or not

- smart_card_connector_app/src/background.js
There's no need to print the system time on the startup of the Smart
Card Connector app, since the system time is printed now with every log
message (since #108).
> Remove duplicate system time log

- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
Print the SCARDCONTEXT values during the forced PC/SC cleanup in order
to simplify investigation of potential issues.
For the context, this forced cleanup happens when a client app
disconnects from the Smart Card Connector. The forced cleanup
deallocates all contexts/handles that were allocated by that client app
so far, and also cancels all "SCardGetStatusChange" operations.
> More logs for forced PC/SC contexts cleanup

- docs/updating-ccid.md
Replace the "find+touch" trick with the "make clean" approach, which is less hacky.
Also mention that this trick can be used for troubleshooting.
> Add hint on "make clean" into updating-ccid.md

- common/js/src/logging/log-formatting.js
Don't mention the background page in the JavaScript/NaCl log messages -
this information can be inferred from the absence of the HTML page URL.
Given that the majority of log messages come from the background page,
it makes sense to reduce the log clutter (and the RAM usage) by omitting
this part.
This change is part of the effort tracked by issue #146.
> Omit "<background page>." from logs

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.h
- example_cpp_smart_card_client_app/src/pp_module.cc
- third_party/closure-compiler/src_additional/chrome_extensions.js
Implement the support of the new chrome.certificateProvider API
functionality in the Example C++ Client App, namely:
* Using new events
"onCertificatesUpdateRequested"+"onSignatureRequested" instead of the
deprecated ones "onCertificatesRequested"+"onSignDigestRequested"
(with a graceful fallback to the deprecated ones when there's no
choice);
* Using the new type "Algorithm" instead of the deprecated "Hash";
* Plumbing for the "setCertificates" function, that allows to
proactively notify Chrome about changes.
> Support new certificateProvider API in examples

- common/js/src/logging/log-buffer-forwarder.js
Fix a potential problem in LogBufferForwarder that the
"formatted_log_message" object key could be minified by the Closure
Compiler to something like "a", in case the aggressive optimization is
enabled.
For the background, the Closure Compiler in the aggressive compilation
mode renames all object properties to some minified names. This is
unwanted in this case, since the object constructed here is sent to the
NaCl module where it gets parsed (and the keys are expected to have
specific names). The way to suppress the Closure Compiler optimization
is to put the property name into quotes.
This was not a real bug at the moment, since we currently don't use the
aggressive compilation mode, but it's nice to fix it anyway.
This is a follow-up to #105 where this code was originally introduced.
> Fix minification issue in LogBufferForwarder

- common/js/src/logging/logging.js
- docs/updating-pcsc-lite.md
These optional formatting arguments are not used anywhere, and will
complicate the upcoming implementation of crash loop detection (tracked
by #156).
Therefore this CL deletes this unused functionality.
> Drop var_args from logging.js methods

- common/js/src/logging/logging.js
Both functions achieve the same goal - reloading the extension - but
they are supported in different contexts: one only works in non-kiosk
sessions and another only in kiosk ones. We call both of them, in order
to simplify the code.
The commit swaps the order of these calls, so that reload() is called
first. This allows to remove the spurious error from restart() when run
in non-kiosk mode.
This is part of the crash-and-reload process improvement tracked by #156.
> Call runtime.reload() before runtime.restart()

- smart_card_connector_app/src/manifest.json.template
- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
Several apps and extensions were renamed since the time they were
originally added into known_client_apps.json, so updating these names.
Note that there are several unpublished extensions/apps, which aren't
served by WebStore anymore and therefore their old names are kept in
this config as-is.
> Update extension names in known_client_apps.json

- common/js/src/logging/logging.js
- example_cpp_smart_card_client_app/build/Makefile
- example_js_smart_card_client_app/build/Makefile
- smart_card_connector_app/build/Makefile
- third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
Add a build-time parameter that allows to enable/disable the
self-reloading of the extension/app in case a fatal error occurs. This
allows to easily disable this functionality in client applications that
don't want this behavior.
Note that this parameter also controls whether the "crash loop
detection" introduced in #156 is enabled.
Also leave this parameter in the "disabled" state for the
"example_js_standalone_smart_card_client_library", since this library is
used in a wide variety of different extensions/apps, and, most likely,
they don't want to be self-reloaded in case the smart card code fails.
It was an oversight that this functionality was enabled there, and now
with addition in #156 of chrome.storage manipulations it became more
apparent that we want to disable it there by …
> Add flag for disabling the reload-on-failure

- common/js/src/nacl-module/nacl-module.js
- smart_card_connector_app/src/background.js
Fix a few places in the code that were legitimately creating promises
without handling their rejection. The standard promise behavior is that
when it's rejected and there's no rejection handler registered
(immediately or until the next tick) an error is raised. Since in these
pieces of code there's no meaningful error handling necessary, this
commit suppresses this behavior.
This change is intended to simplify investigation of crash reports as
per #156, since these spurious unhandled promise rejections could
distract attention from the actual underlying problem.
For posterity, these places of code were found by inspecting callsites
that create a new Promise (via constructor or via
goog.Promise.withResolver), temporarily inserting reject() calls and
verifying that the DevTools console …
> Unhandled promise fixes

- common/js/src/nacl-module/nacl-module-log-messages-receiver.js
- common/js/src/nacl-module/nacl-module.js
Don't add the '<"nacl_module.nmf">.NaCl' suffix to the logger name
used for NaCl-related log messages. This information about the URL of
the NaCl module is redundant - we don't use multiple NaCl modules
currently.
Also drop the ".NaCl" suffix for messages forwarded from the NaCl
module, and instead add ".Wrapper" for all other messages logged
by the JS code of this class. This way, we move the log clutter from
typically long NaCl logs into usually less interesting JS logs.
Example before:
[200930 04:21:34.51] [  7.244s] [NaclModule<"nacl_module.nmf">.NaCl] [syslog] 00000000 ../../src/src/ifdhandler.c:2008:init_driver() Driver version: 1.4.33 
Example after:
[200930 04:21:34.51] [  7.244s] [NaclModule] [syslog] 00000000 ../../src/src/ifdhandler.c:2008:init_driver() Driver version: 1.4.33 …
> Omit '<"nacl_module.nmf">.NaCl' from logs

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.h
- example_cpp_smart_card_client_app/src/pp_module.cc
Add example usage of setCertificates to the cpp example app.
Fix incorrect API calls that would previously happen when trying to use
ApiBridge::SetCertificates() by transforming the used parameters on the
JS side directly before the API call.
> Fix incorrect setCertificate API calls

- common/js/src/requesting/requester-unittest.js
- common/js/src/requesting/requester.js
Fix a bug that could lead to JavaScript exception in a corner case when
the Requester's postRequest() method is called after the object is
already disposed of. The error was:
TypeError: Cannot read property 'get' of null
at GoogleSmartCard.Requester.popRequestPromiseResolver_
Also add a regression unit test against this bug.
> Fix JS Requester post-after-dispose bug

- common/integration_testing/build/.gitignore
- common/integration_testing/build/Makefile
- common/integration_testing/dependency.mk
- common/integration_testing/include.mk
- common/integration_testing/src/google_smart_card_integration_testing/integration-test-controller.js
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_pp_module.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- common/js/src/requesting/requester.js
- example_cpp_smart_card_client_app/build/Makefile
- example_cpp_smart_card_client_app/build/integration_tests/.gitignore
- example_cpp_smart_card_client_app/build/integration_tests/Makefile
Implement a mini-framework that allows to implement hybrid tests that
exercise both JavaScript and C++ code. In such tests, the main test
script will be written in JavaScript, meanwhile the C++ counterpart is
structured as a set of "helpers" that can be called from the JS code.
The implemented framework abstracts away some boilerplate related to
JS-and-C++ communication and code compilation.
This commit paves the way for fixing the missing test coverage for the
parts that cross the language boundary. Up to this point, we only had
unit test coverage for pieces within single language (only within
JavaScript or only within C/C++), which has been insufficient.
> Framework for JS-and-C++ integration tests

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
Add an integration test that verifies correct conversion of certificate
data from the C++ struct into the JavaScript object when the
chrome.certificateProvider.setCertificates() method is called.
This is a regression test for the bug fixed in #171.
> Nonempty test case for setCertificates() C++ adapter

- env/initialize.sh
Change the env/initialize.sh script to be idempotent by default, so that
already existing tools and libraries are left intact by it. Add the "-f"
option that allows to revert to the previous "destructive" behavior.
This is a preparation change for introducing the WebAssembly build tools
initialization in #177, since it'll make it possible for developers to
rerun "initialize.sh" in order to get WebAssembly tools without
destroying their existing Native Client related state.
> Skip existing files&dirs in env/initialize.sh

- env/.gitignore
- env/constants.sh
- env/initialize.sh
Add download and installation of Emscripten into the env/initialize.sh
script. This will be used in the future for building the WebAssembly
ports of the C/C++ code in the Smart Card Connector app and related
projects (instead of the currently used Native Client) - see #177.
The version of Emscripten is pinned, so that all developers get
consistent results and avoid any potential breakages related to uprevs.
> Download Emscripten in env/initialize.sh

- common/cpp/build/Makefile
- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/value.cc
- common/cpp/src/google_smart_card_common/value.h
- common/cpp/src/google_smart_card_common/value_unittest.cc
Initial implementation of the "Value" class that, approximately, can
hold any JSONifiable object.
This class will be used in follow-ups to replace the widespread usage of
the Native Client / Pepper specific "pp::Var" class, so that all
depending code can be reused in WebAssembly builds (that effort is
tracked by #185).
The class is additionally inspired by the Chromium's "base::Value", but
we're having a much simpler custom implementation here, because
Chromium's implementation brings a bunch of dependencies and is not
trivial to compile.
> Introduce variant Value type

- common/cpp/build/Makefile
- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion.cc
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion.h
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion_unittest.cc
Implement helper function that transforms a Native Client SDK's pp::Var
object into a Value object.
This helper will be used in follow-ups in order to make most of the
//common/cpp library be toolchain-independent and work under both Native
Client and WebAssembly (as tracker by #185), since the Value class is
toolchain-independent.
> Add conversion from NaCl's pp::Var into Value

- common/cpp/src/google_smart_card_common/optional.h
- common/cpp/src/google_smart_card_common/pp_var_utils/extraction.h
Extend our polyfill for the "optional" C++ class to have the reset()
method, and use it in places where the optional was reset by other
means.
Historically, the original C++ Standard proposal for the std::optional
type didn't have the reset() method, which is why we didn't add into our
polyfill as well. However, afterwards this method was added into the
final std::optional interface, which went into C++17.
In the future, once we fully migrate to WebAssembly and drop the Google
Native Client support, we'll be able to delete the whole polyfill class
and use the "optional" class provided by the C++ Standard Library.
> Add optional::reset() method

- common/cpp/build/Makefile
- common/cpp/src/google_smart_card_common/value_unittest.cc
- common/integration_testing/build/Makefile
- common/tests_runner/build.mk
- example_cpp_smart_card_client_app/build/integration_tests/Makefile
- example_cpp_smart_card_client_app/build/nacl_module/Makefile
- smart_card_connector_app/build/nacl_module/Makefile
- third_party/libusb/naclport/build/Makefile
- third_party/pcsc-lite/naclport/common/build/Makefile
Add "-Wall" and "-pedantic" C/C++ compilation flags in all places where
this doesn't break the compilation. Suppress particular warnings in a
couple of places where they are expected or hard to fix.
This should help maintaining the code base by using compiler built-in
diagnostics to a larger extent.
> Use -Wall -pedantic in more places

- common/cpp/src/google_smart_card_common/messaging/typed_message.cc
- common/cpp/src/google_smart_card_common/messaging/typed_message.h
- common/cpp/src/google_smart_card_common/messaging/typed_message_router.cc
- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
- common/cpp/src/google_smart_card_common/messaging/typed_message_unittest.cc
- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.cc
- common/cpp/src/google_smart_card_common/requesting/js_requester.cc
- example_cpp_smart_card_client_app/src/ui_bridge.cc
- smart_card_connector_app/src/pp_module.cc
- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
Refactor the code that creates/parses "typed message" dictionaries to
hold the data in a dedicated struct and to use the StructConverter for
conversion to/from pp::Var instances.
This refactoring removes one particular usage of the
"VarDictValuesExtractor" converter class; the goal is to get rid of all
usages except the internal usage within the StructConverter class.
This will make it easier to migrate to the Value class in the future
(which is part of the WebAssembly migration tracked by #185), since
the Value-based conversions will work via an interface similar to
StructConverter.
> Use StructConverter for typed messages

- common/cpp/build/Makefile
- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/value.cc
- common/cpp/src/google_smart_card_common/value.h
- common/cpp/src/google_smart_card_common/value_debug_dumping.cc
- common/cpp/src/google_smart_card_common/value_debug_dumping.h
- common/cpp/src/google_smart_card_common/value_debug_dumping_unittest.cc
Add functions that generate debug dumps of Value instances, for logging
purposes.
This is equivalent to the currently existing helpers in
//common/cpp/src/pp_var_utils/debug_dump.h. As in those existing
helpers, two versions are provided: the full dump and the privacy-safe
compact dump.
These helpers for Value instances is a preparation step for migrating the
//common/cpp library under WebAssembly (as tracked by #185).
> Add Value debug dumping helpers

- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
- common/cpp/src/google_smart_card_common/value_debug_dumping.cc
Fix "unused variable" and "unused function" warnings that were somehow
missed while landing previous patchsets (namely, #189 and #193).
> Fix compilation warnings in Value implementation

- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/formatting.cc
- common/cpp/src/google_smart_card_common/formatting.h
- common/cpp/src/google_smart_card_common/formatting_unittest.cc
- common/cpp/src/google_smart_card_common/messaging/typed_message_router.cc
- common/cpp/src/google_smart_card_common/numeric_conversions.cc
- common/cpp/src/google_smart_card_common/numeric_conversions.h
- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion.cc
Add another variant of the FormatPrintfTemplate() C++ function that
writes its result to the given pointer, after checking the latter for
being non-null.
This allows to simplify code to avoid writing boilerplate "if
(error_message)" conditions. This change isn't expected to cause any
real-world performance regressions, despite generating error message
parameters even in cases when the result is not used, since it only
affects "unsuccessful" code paths that should only be triggered rarely.
> Helper for creating error messages if requested

- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
Add overloads for the ConvertToValue/ConvertFromValue functions that
perform identity transform, i.e., return the input argument without
changes.
This is needed in order to make generic transformation code work in case
when the same Value class is used in both source and destination
representation - for example, the TypedMessage struct's |data| field.
This is part of the effort on migrating the //common/cpp library to use
the toolchain-independent Value class, making it work under both
Native Client and WebAssembly (#185).
> Add identity transform for Value into itself

- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion.cc
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion.h
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion_unittest.cc
Add new variants of the ConvertToValue/ConvertFromValue functions that
immediately crash the program in case the conversion fails.
These functions should be used in cases when the error is really
unexpected (e.g., when the input data is guaranteed to be of specific
form) and/or when there's no recovery possible from the error.
This is part of the effort on migrating the //common/cpp library to use
the toolchain-independent Value class, making it work under both
Native Client and WebAssembly (#185).
> Add "OrDie" Value conversion variants

- format-code.sh
Add a small script that can be used when developing locally in order to
automatically format the touched C++ files according to the Google C++
Style Guide. The script is based on the "clang-format" tool.
The script assumes that the "clang-format" program is installed into the
system and is in $PATH.
> Script for auto-formatting code via clang-format

- common/cpp/src/google_smart_card_common/value.cc
- common/cpp/src/google_smart_card_common/value.h
- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
Implement helpers for semi-automated implementation that maps between
C++ structs and JSON-like dictionary Values.
This extends the set of helpers for converting between Value instances
and C/C++ objects, paving the way for migrating the rest of //common/cpp
library to become toolchain-independent (as tracked by #185).
This commit implements analogous functionality similar to the already
existing Native Client pp::Var specific helpers (in
pp_var_utils/struct_converter.h), however this new implementation requires
much less boilerplate code to be written for every struct.
> Add conversions for Value to/from C++ structs

- common/cpp/build/Makefile
- example_cpp_smart_card_client_app/src/ui_bridge.cc
- smart_card_connector_app/src/pp_module.cc
- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
Adjust the C++ code outside //common/cpp to the new implementation of
TypedMessage that doesn't support pp::Var anymore.
This CL is a follow-up to #201, and is a stop-gap solution to make the
whole project still compile and work while we're working on the migration
of the //common/cpp library (as tracked by #185). After completion of
that part, we'll clean up the non-//common code to delete all those
back-and-forth pp::Var conversions and to use Value wherever possible.
> Migrate non-//common to Value-based TypedMessage

- common/cpp/src/google_smart_card_common/external_logs_printer.cc
- common/cpp/src/google_smart_card_common/external_logs_printer.h
- common/cpp/src/google_smart_card_common/messaging/typed_message_listener.h
- common/cpp/src/google_smart_card_common/messaging/typed_message_router.cc
- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.cc
- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.h
- common/cpp/src/google_smart_card_common/requesting/js_requester.cc
- common/cpp/src/google_smart_card_common/requesting/js_requester.h
- example_cpp_smart_card_client_app/src/ui_bridge.cc
- example_cpp_smart_card_client_app/src/ui_bridge.h
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
Change the typed_message_listener.h and all child classes to use the
Value class in the interface, rather than using the Native Client
specific pp::Var.
As an additional outcome, the implementation of the
typed_message_router.cc file becomes completely free of pp::Var usages
as well.
by #185).
> Migrate typed_message_listener.h to Value

- common/cpp/build/Makefile
- common/integration_testing/build/Makefile
- common/integration_testing/dependency.mk
- common/integration_testing/include.mk
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_pp_module.cc
- common/tests_runner/build.mk
- test-all.sh
Fix several issues with tests compilation:
* //common/integration_testing/ and //common/tests-runner/ build
scripts were pointing to a non-existing .mk file (since #204);
* //common/integration_testing/ C++ code wasn't updated to use Value
instead of pp::Var (since #196);
* //common/cpp/ build scripts weren't installing value_debug_dumping.h
into a public header location, which made it impossible to use it in
tests (originally forgotten in #189);
* //test-all.sh wasn't updated to include the new
//example_cpp_smart_card_client_app/build/integration_tests/ target.
> Fix test compilation

- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.cc
- common/cpp/src/google_smart_card_common/requesting/js_requester.cc
- common/cpp/src/google_smart_card_common/requesting/requester_message.cc
- common/cpp/src/google_smart_card_common/requesting/requester_message.h
Change the requester_message.h header to use the toolchain-independent
Value class instead of Native Client specific pp::Var class. Besides the
mechanical replacement, this commit introduces dedicated structs for the
"request"/"response" messages, since it makes the interface more concise
and allows to reuse automatic to/from Value conversion helpers.
by #185).
> Migrate requester_message.h to Value

- common/cpp/build/.gitignore
- common/make/executable_building.mk
- common/make/internal/executable_building_emscripten.mk
This adds the first version of Emscripten-specific Makefile definitions,
allowing to compile the C/C++ code under WebAssembly. This new
functionality can be enabled by setting the TOOLCHAIN environment
variable to "emscripten" (the variable still defaults to "pnacl" to use
Google Native Client, as before).
Note that this is only a barebone implementation, since it doesn't
support several important features, namely:
* Auto-detecting related .h files and triggering recompilation of .cc
files on their changes;
* Installation of headers into shared location;
* Building unit tests;
* etc.
These will be addressed in follow-ups, as tracked by #177.
Another note - Right now only very few files in the project can be
compiled using this new Emscripten toolchain, since many files are using
Native …
> Add Emscripten barebone build implementation

- common/cpp/src/google_smart_card_common/requesting/js_requester.cc
- common/cpp/src/google_smart_card_common/requesting/js_requester.h
- common/cpp/src/google_smart_card_common/requesting/remote_call_adaptor.cc
- common/cpp/src/google_smart_card_common/requesting/requester.cc
- common/cpp/src/google_smart_card_common/requesting/requester.h
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.cc
Change requester.h and js_requester.h headers and the corresponding
implementation .cc files to use the toolchain-independent Value
class intead of Native Client specific pp::Var class in most places.
The only left place is the delegate for sending messages to JS, which
will be refactored separately.
by #185).
> Migrate [js_]requester.h to Value

- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
Implement the ConvertToValue() helper for the std::vector<> input type,
with recursively applying the same ConvertToValue() transform to each
item.
This extends the set of helpers for converting between Value instances
and C/C++ objects, paving the way for migrating the rest of //common/cpp
library to become toolchain-independent (as tracked by #185).
> Add conversion from std::vector to Value

- common/cpp/src/google_smart_card_common/value.cc
- common/cpp/src/google_smart_card_common/value.h
- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
Implement the ConvertFromValue() helper for the std::vector<> output
type, with recursively applying the same ConvertFromValue() transform
to each array item.
This extends the set of helpers for converting between Value instances
and C/C++ objects, paving the way for migrating the rest of //common/cpp
library to become toolchain-independent (as tracked by #185).
> Add conversion from Value to std::vector

- common/cpp/build/Makefile
- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
- common/cpp/src/google_smart_card_common/nacl_io_utils.h
- common/cpp/src/google_smart_card_common/pp_var_utils/construction.h
- common/cpp/src/google_smart_card_common/pp_var_utils/copying.h
- common/cpp/src/google_smart_card_common/pp_var_utils/debug_dump.h
- common/cpp/src/google_smart_card_common/pp_var_utils/extraction.h
- common/cpp/src/google_smart_card_common/pp_var_utils/operations.h
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion.h
This fixes the makefiles in //common/cpp to exclude source files from
compilation in case the toolchain is non Native Client and the files
can only be compiled under the Native Client.
This fixes the Emscripten/WebAssembly builds of //common/cpp (as tracked
by #177). Note that there are two groups of excluded files currently:
those that provide NaCl-specific capabilities, and those that aren't
migrated to support Emscripten yet. The latter ones will be gradually
migrated and reenabled in follow-ups.
> Build //common NaCl-specific files only under NaCl

- common/cpp/build/Makefile
- common/cpp/src/google_smart_card_common/logging/logging.cc
- common/cpp/src/google_smart_card_common/value_unittest.cc
- common/integration_testing/build/Makefile
- common/make/internal/executable_building_emscripten.mk
- common/tests_runner/build.mk
- example_cpp_smart_card_client_app/build/integration_tests/Makefile
- example_cpp_smart_card_client_app/build/nacl_module/Makefile
- smart_card_connector_app/build/nacl_module/Makefile
- third_party/libusb/naclport/build/Makefile
- third_party/pcsc-lite/naclport/common/build/Makefile
* Add "-Werror" - i.e., treat warnings as compilation errors. (To note,
in Native Client builds this has always been enabled by NaCl's
toolchain.)
* Enable "NDEBUG" preprocessor definition in Release builds, in order to
disable debug-only assertions and debug value output. (In NaCl builds
this has already been enabled.)
* Fix a few warnings detected by Emscripten's clang compiler:
* * logging.cc:35:16: error: unused variable 'kTypeMessageKey'
* * logging.cc:36:16: error: unused variable 'kMessageType'
* * logging.cc:37:16: error: unused variable 'kDataMessageKey'
* * logging.cc:38:16: error: unused variable 'kDataLogLevelMessageKey'
* * logging.cc:39:16: error: unused variable 'kDataTextMessageKey'
* * value_unittest.cc:80:38: error: implicit conversion from 'const int64_t'
(aka 'const …
> Tighten compilation flags in Emscripten builds

- third_party/googletest/webport/build/.gitignore
- third_party/googletest/webport/build/Makefile
Add a Makefile that performs building of GoogleTest/GoogleMock libraries
and installation of them into the shared static libraries directory.
This Makefile is only supported for Emscripten builds (whose support is
being added at #177), since NaCl SDK already comes with its own port
of GoogleTest.
Note: The Makefile doesn't contain any detection of source file changes
and automated recompilation, since it'd be pretty complex to implement
(because, under the hood, GoogleTest uses a different build system -
CMake) and it's not needed that often (only when someone will uprev the
pinned GoogleTest sources in our repo to a new version). Rebuilding can
be enforced manually by running "make clean".
> Add script for building GoogleTest in Emscripten

- common/cpp/build/Makefile
- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/requesting/async_request.h
- common/cpp/src/google_smart_card_common/requesting/async_request_unittest.cc
- common/cpp/src/google_smart_card_common/requesting/async_requests_storage.h
- common/cpp/src/google_smart_card_common/requesting/remote_call_adaptor.h
- common/cpp/src/google_smart_card_common/requesting/request_result.h
- common/cpp/src/google_smart_card_common/requesting/requester_message.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
- third_party/libusb/naclport/src/libusb_opaque_types.cc
- third_party/libusb/naclport/src/libusb_over_chrome_usb.cc
- third_party/libusb/naclport/src/libusb_over_chrome_usb_unittest.cc
- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
Change async_request.h, async_requests_storage.h, request_result.h
to use the toolchain-independent Value class intead of Native Client
specific pp::Var class in most places. As an additional bonus, the
request_result.cc, requester.cc, requester_message.cc files became
completely free of NaCl-specific definitions as well.
Besides the mechanical replacement, there's a bit of refactoring due to
using std::move() instead of the previously used copying in related
classes. The background here is that the NaCl's pp::Var class was
copyable (with ref-counting), meanwhile the new Value class is only
moveable.
by #185).
> Migrate async_request.h and related to Value

- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog.css
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.cc
1. The dialog not being displayed, due to incorrectly sending a null
value instead of an empty dictionary value when making a C++-to-JS
request. (The error introduced in #209.)
2. Fix the "Cancel" button title not being correctly loaded, due to a
typo in the localized message name (introduced back in #113).
> Fix errors in the example app built-in PIN dialog

- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion.cc
- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion.h
- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion_unittest.cc
Implement helper functions that transform an Emscripten Embind's
emscripten::val object into a Value object.
This will be used in follow-ups in order to receive messages from
JavaScript in Emscripten/WebAssembly builds, with the messages
handling code being toolchain-independent, contributing to the goal
of making most of the //common/cpp library be toolchain-independent
(as tracked by #185).
> Add conversion from Emscripten's val into Value

- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
- common/cpp/src/google_smart_card_common/requesting/async_requests_storage_unittest.cc
Disable the following tests that are currently failing in Emscripten
builds:
* RequestingAsyncRequestsStorageTest.MultiThreading;
* MessagingTypedMessageRouterTest.MultiThreading.
Both tests are related to threading; they're failing due to
out-of-memory (due to hitting the default memory limit when allocating
memory for each thread). Naively increasing the limit doesn't help - the
tests begin to crash with more mysterious errors. Therefore fixing these
tests will require separate later investigation (tracked by #185).
> Temporarily disable tests that fail in Emscripten

- common/js/src/container-helpers-unittest.js
- common/js/src/container-helpers.js
- common/js/src/messaging/port-message-channel-unittest.js
- common/js/src/messaging/port-message-channel.js
Replace ArrayBuffer's with byte Array's when sending cross-extension
messages.
The background for this change is that Chrome Extension APIs don't
support sending ArrayBuffer's inside messages from one extension/app to
another. Currently the code in this project never attempts to do that,
but the refactoring proposed in #222 will start putting ArrayBuffer's
into the sent messages. Therefore the current commit anticipates this
upcoming change and adds an automatic conversion that will prevent data
loss in cross-extension messages.
> Substitute ArrayBuffer in cross-extension messages

- common/cpp/src/google_smart_card_common/pp_var_utils/construction.cc
- common/cpp/src/google_smart_card_common/pp_var_utils/construction.h
- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
Change the vector-to-Value and the [obsolete, NaCl-specific]
vector-to-pp::Var conversion implementations to have a special
treatment for the "std::vector<uint8_t>" input type: convert it into a
binary/ArrayBuffer object, instead of the normal conversion into an
array with numbers.
This suits several purposes:
1. Allow seamless transformations in case the ArrayBuffer is really
required on the receiver side - for example, when calling an
Extensions API that uses an ArrayBuffer parameter.
2. Avoid introducing a special C++ type that would behave like an
std::vector<uint8_t>, but denote "convert me into ArrayBuffer,
unlike any real std::vector". (Note that previously, before we
started working on WebAssembly, the pp::VarArrayBuffer type
was suiting that purpose.)
3. Increase the performance …
> Convert vector<uint8_t> into binary/ArrayBuffer

- common/cpp/src/google_smart_card_common/external_logs_printer.cc
- common/cpp/src/google_smart_card_common/messaging/typed_message.cc
- common/cpp/src/google_smart_card_common/requesting/requester_message.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.cc
- third_party/libusb/naclport/src/chrome_usb/types.cc
- third_party/libusb/naclport/src/chrome_usb/types.h
- third_party/libusb/naclport/src/libusb_over_chrome_usb.cc
- third_party/libusb/naclport/src/libusb_over_chrome_usb_unittest.cc
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
Add helper definitions that allow conversions to/from Value objects for
every relevant enum/struct in this project (i.e., for every enum/struct
that currently support conversions to/from Native Client pp::Var objects).
This paves the way for continuing the //common/cpp WebAssembly migration
effort (as tracked by #185) without breaking the compilation of the
whole project. Specifically, some upcoming commits will change the way
how outgoing request parameters are serialized before being sent to the
JavaScript side: they'll be converted into Value instead of pp::Var.
Note that the current commit still keeps the old pp::Var conversion
helpers: those will be cleaned up in later follow-ups once they become
unused.
The commit also introduces behavior change: some of the struct fields
are …
> Register enums/structs in to/from Value conversion

- third_party/googletest/webport/build/Makefile
Add the "-pthread" flag when compiling and linking the GoogleTest static
libraries in Emscripten builds.
Meanwhile Pthreads aren't actually used by GoogleTest itself (due to the
"gtest_disable_pthreads" parameter that we specify), it's still necessary
because we use "-pthread" when compiling other libraries and source
files, and Emscripten seems to require this flag to be used consistently
everywhere.
This is a preparatory fix for introducing Emscripten builds of unit
tests, as tracked by #177.
> Use "-pthread" for GoogleTest builds in Emscripten

- common/cpp/src/google_smart_card_common/requesting/request_handler.h
- common/cpp/src/google_smart_card_common/requesting/request_receiver.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
Change the request_handler.h header and all related code to use the
toolchain-independent Value class instead of the Native Client specific
pp::Var class.
by #185).
> Migrate request_handler.h to Value

- common/cpp/build/Makefile
- common/cpp/build/tests/.gitignore
- common/js/build/Makefile
- common/make/js_building_common.mk
- common/tests_runner/build.mk
- example_cpp_smart_card_client_app/build/Makefile
- example_cpp_smart_card_client_app/build/integration_tests/.gitignore
- example_cpp_smart_card_client_app/build/integration_tests/Makefile
- third_party/libusb/naclport/build/Makefile
- third_party/libusb/naclport/build/tests/.gitignore
- third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
Rename the existing "run" makefile target into "run_test", in order to
avoid clashing with the Native Client's definition of the "run" target.
Previously we were intentionally using this clash in order to reduce
amount of boilerplate needed for running tests, but that came with the
price of doing some nontrivial hacks (like changing the current
directory CURDIR back and forth). This commit gets rids of these hacks
and makes tests' makefiles slightly simpler, which will also simplify
the upcoming Emscripten test runner implementation.
This is a preparatory fix for introducing Emscripten builds of unit
tests, as tracked by #177.
> Introduce "make run_test" for running tests

- common/cpp/src/google_smart_card_common/requesting/async_request_unittest.cc
Disable the following test that is currently failing in Emscripten
builds:
* RequestingAsyncRequestTest.AsyncRequestStateMultiThreading.
Same as with the tests disabled in #225, the issue is related to the
multi-threading functionality and will need to be investigated
separately as part of the effort tracked in #185.
> Disable one more failing test in Emscripten

- common/make/internal/executable_building_emscripten.mk
Fix the LINK_EXECUTABLE_RULE makefile rule in Emscripten builds to have
the correct list of arguments: the rule was incorrectly written as if
there was an additional first argument that specifies the name of the
executable to be linked. In reality, as documented in the "interface"
file and implemented in the NaCl build scripts, there's no such
argument, and the TARGET variable should be used for that purpose.
This fixes the mistake introduced in the original PR #208. The umbrella
issue that tracks the Emscripten build implementation is #177.
> Fix Emscripten link rule wrong arguments position

- common/cpp/build/Makefile
- common/cpp/src/google_smart_card_common/global_context.h
- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.cc
- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.h
- common/cpp/src/google_smart_card_common/global_context_impl_nacl.cc
- common/cpp/src/google_smart_card_common/global_context_impl_nacl.h
Introduce a GlobalContext interface that abstracts away some of the
differences between Native Client and Emscripten, such as different ways
of sending messages to JavaScript.
This commit provides implementations of this interface for both Native
Client and Emscripten. Currently both the interface and the
implementations are unused; follow-up commits will migrate the existing
codebase in //common/cpp to use this interface instead of various
NaCl-specific delegates (contributing to the goal of making most of the
//common/cpp library be toolchain-independent, as tracked by #185).
> Introduce interface for toolchain-specific C++ ops

- common/cpp/build/Makefile
- common/cpp/build/tests/Makefile
- common/cpp_unit_test_runner/include.mk
- common/cpp_unit_test_runner/src/build_emscripten.mk
- common/cpp_unit_test_runner/src/build_nacl.mk
- common/cpp_unit_test_runner/src/entry_point_nacl.cc
- common/cpp_unit_test_runner/src/index_nacl.html
- third_party/libusb/naclport/build/tests/Makefile
This commit adds the support of building and running C++ unit tests in
Emscripten builds.
In order to achieve this, there's also a refactoring made that
simplifies how the tests' makefiles are organized and allows to abstract
away differences between Native Client and Emscripten.
This is an improvement for the Emscripten/WebAssembly build
infrastructure that is tracked by #177.
> Implement C++ unit test runner for Emscripten

- make-all.sh
Extend the //make-all.sh script to additionally compile all unit and
integration test targets.
This makes it simpler to perform a routine compilation check in the
middle of some refactoring; the existing //test-all.sh script allowed
to achieve the same, but it was also launching all tests which
significantly increased the required time.
Additionally, this change makes sure that the
//common/integration_testing helper library is built before the targets
that use it are built, which avoids some flaky compilation errors (due
to our imperfect handling of concurrent builds of recursive makefiles).
> Compile all tests in make-all.sh

- common/cpp/build/Makefile
- common/cpp/src/google_smart_card_common/requesting/js_requester.cc
- common/cpp/src/google_smart_card_common/requesting/js_requester.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_pp_module.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.cc
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built_in_pin_dialog_server.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
- example_cpp_smart_card_client_app/src/pp_module.cc
- smart_card_connector_app/src/pp_module.cc
- third_party/libusb/naclport/src/google_smart_card_libusb/global.cc
- third_party/libusb/naclport/src/google_smart_card_libusb/global.h
- third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.cc
- third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.h
This commit changes the JsRequester class to use the
toolchain-independent GlobalContext interface instead of directly
operating Native Client specific objects (pp::Core, pp::Instance).
This makes the whole JsRequester class work under both
Emscripten/WebAssembly and Native Client (contributing to the
effort tracked by #185). Besides the mechanical replacement, the
commit had to introduce construction of the GlobalContext object
in entry point .cc files and passing them through down to the
JsRequester constructors.
As a side effect bonus, this commit made the following files
toolchain-independent as well:
* google_smart_card_libusb/global.{h|cc};
* google_smart_card_pcsc_lite_client/global.{h|cc}.
> Migrate js_requester.{h|cc} to GlobalContext

- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.cc
- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_pp_module.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
- example_cpp_smart_card_client_app/src/pp_module.cc
- smart_card_connector_app/src/pp_module.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
- third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/backend.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/backend.h
Change the JsRequestReceiver class to use the toolchain-independent
GlobalContext interface instead of directly operating Native Client
specific objects (pp::Core, pp::Instance).
This makes the whole JsRequestReceiver class work under both
Emscripten/WebAssembly and Native Client (contributing to the
effort tracked by #185).
As a side effect bonus, this commit made the following files
toolchain-independent as well:
* google_smart_card_pcsc_lite_server_clients_management/backend.{h|cc}.
> Migrate js_request_receiver.{h|cc} to GlobalContext

- example_cpp_smart_card_client_app/src/pp_module.cc
- example_cpp_smart_card_client_app/src/ui_bridge.cc
- example_cpp_smart_card_client_app/src/ui_bridge.h
Change the UiBridge class to use the toolchain-independent GlobalContext
interface instead of directly operating Native Client specific objects
(pp::Core, pp::Instance).
This contributes to the goal of making the UiBridge implementation work
under both Emscripten/WebAssembly and Native Client (as part of the
bigger effort tracked by #220).
> Migrate ui_bridge.{h|cc} to GlobalContext

- example_cpp_smart_card_client_app/src/pp_module.cc
- example_cpp_smart_card_client_app/src/ui_bridge.cc
- example_cpp_smart_card_client_app/src/ui_bridge.h
Change the UiBridge class to use the toolchain-independent Value class,
instead of the Native Client specific pp::Var class.
This completes the migration of the UiBridge class in order to support
both Native Client and Emscripten/WebAssembly builds (as part of the
effort tracked by #220).
> Migrate ui_bridge.{h|cc} to Value

- common/cpp/build/Makefile
- common/cpp/src/google_smart_card_common/requesting/remote_call_adaptor.h
- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion.cc
- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion.h
- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion_unittest.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- third_party/libusb/naclport/src/chrome_usb/api_bridge.cc
- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
This commit changes the RemoteCallAdaptor class to use the
toolchain-independent Value class instead of Native Client specific
classes (like pp::Var). This contributes to the effort tracked
by #185.
Besides mechanical replacements, this change introduces a helper class
for converting the input/output remote call arguments from Values into
any supported C++ type. Unlike old NaCl-based conversion helpers,
this class is more flexible (e.g., in case the argument list doesn't have a
fixed length) and produces better error messages.
As a side effect bonus, this commit made the following files
toolchain-independent as well:
* chrome_usb/api_bridge.cc;
* pcsc_lite_over_requester.cc.
> Migrate remote_call_adaptor.{h|cc} to Value

- common/cpp/build/Makefile
- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.cc
- common/cpp/src/google_smart_card_common/requesting/request_receiver.cc
- common/cpp/src/google_smart_card_common/requesting/request_receiver.h
Change the RequestReceiver and JsRequestReceiver classes to use the
toolchain-independent Value class instead of the Native Client specific
pp::Var class.
This makes these classes compile and work both under Native Client
and Emscripten/WebAssembly, contributing to the effort of migration of
the //common/cpp library (as tracked by #185).
> Migrate [js_]request_receiver.{h|cc} to Value

- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion.h
- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion_unittest.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
Change the implementation of test helpers in
//common/integration_testing to use the platform-independent Value
class, instead of Native Client specific pp::Var class. This contributes
to the goal of making the common C++ libraries in this project work
under Emscripten/WebAssembly (as tracked by #185).
Other changes made in this commit:
* Helper methods added for a single-line conversion of incoming remote
call arguments from Values into C++ objects;
* api_bridge_integration_test_helper.cc became, as a bonus side effect,
toolchain-independent as well.
> Convert //common/integration_testing to Value

- third_party/closure-library/include.mk
This commit adds the
//third_party/closure-library/src/third_party/closure directory into the
list of source directories for JavaScript builds performed by Closure
Compiler.
This fixes the issue with inability to use the goog.async.Deferred
class, since it's defined in a file that was under this third_party
subdirectory of the Closure Library, which we didn't include before.
This is a preparatory CL for introducing Emscripten/WebAssembly support
into the Example C++ App (tracked by #220), since the proposed way of
loading the Emscripten module will involve goog.async.Deferred.
> Fix goog.async.Deferred not available in JS code

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
Change the chrome_certificate_provider/api_bridge.{h|cc} files in the
C++ Example App to use the toolchain-independent Value class, instead
of Native Client specific pp::Var class and related.
This contributes to the effort of migrating the
//example_cpp_smart_card_client_app App to support WebAssembly (as
tracked by #220).
> Migrate cert provider api_bridge.{h|cc} to Value

- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.cc
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.h
Surround the Native Client specific code with #ifdef's in
scard_structs_serialization.{h|cc}, so that it's only compiled in Native
Client builds. This way, these files can be used both by code that is
fully migrated to Emscripten/WebAssembly and the code that is still
using Native Client specific primitives.
This is a temporary step in order to accomplish the migration of the
//example_cpp_smart_card_client_app App (tracked by #220) earlier,
before the Smart Card Connector App gets migrated as well. Later,
once everything is migrated, all these #ifdef's together with the
code inside them will be removed.
> ifdef NaCl code in scard_structs_serialization

- example_cpp_smart_card_client_app/build/nacl_module/Makefile
- third_party/pcsc-lite/naclport/cpp_demo/build/Makefile
This commit disables installation of "public" headers from the
//third_party/pcsc-lite/naclport/cpp_demo library into a common
include directory. Instead, the path to this library is simply
added into the include search path in needed makefiles.
More background on this refactoring is in #132.
> Not install pcsc-lite/naclport/cpp_demo headers

- common/cpp/src/google_smart_card_common/global_context.h
- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.cc
- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.h
- common/cpp/src/google_smart_card_common/global_context_impl_nacl.cc
- common/cpp/src/google_smart_card_common/global_context_impl_nacl.h
- common/cpp/src/google_smart_card_common/requesting/js_request_receiver.cc
- common/cpp/src/google_smart_card_common/requesting/js_requester.cc
- example_cpp_smart_card_client_app/src/ui_bridge.cc
Change the GlobalContext::PostMessageToJs()'s signature to take the
Value object by value (instead of const-ref) and remove the boolean
return value.
The reason is that on the Emscripten/WebAssembly platform we'll need to
schedule the message sending job to a different thread (in case we're not
on the main thread), which means that we want to grab the ownership of
the value until it's actually sent. Moreover, it means that we cannot
reliably tell the caller whether the delivery was successful (because it'll
happen asynchronously), therefore the return value is changed to "void".
This is a preparatory commit for the abovementioned change. The overall
WebAssembly migration effort of this library is tracked by #185.
> Make PostMessageToJs() consume the Value object

- common/cpp/build/tests/Makefile
Add the "value_emscripten_val_conversion_unittest.cc" file into build
scripts, so that it's executed with all other tests.
Previously it was forgotten (in both #211 and #218), likely due to some
merge conflict. The tracking issue is #185.
> Add forgotten Emscripten-Value conversion tests

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
Fix the JavaScript exception being raised during the
chrome.certificateProvider.setCertificates() method call, in case the
whole chrome.certificateProvider API is unavailable.
This is expected to be a rare corner case - for example, when running
the Example C++ App in a desktop Chrome browser - nevertheless, it's
better to fix it to simplify testing and debugging it. Note that the
consequence of the bug was not only a JS error in the console, but also
hanging of the setCertificates() call.
> Fix setCertificates() JS error when there's no API

- common/js/src/executable-module/emscripten-module.js
Extend the JavaScript "EmscriptenModule" class to have a bidirectional
message pipe with the executable. This message pipe conforms to the
Closure Library's goog.messaging.MessageChannel interface. Messages to
the module are sent by calling the "postMessage()" method on the
GoogleSmartCardModule class exposed by it via Embind. Messages in the
reverse direction are received via the callback passed to the class'
constructor.
This contributes to the WebAssembly migration effort, as tracked
by #220.
> Implement message channel for Emscripten JS loader

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.h
Delete the code for conversions to/from Native Client pp::Var types from
chrome_certificate_provider/types.{h|cc} files in
//example_cpp_smart_card_client_app. There's no code that uses them
anymore, and the conversions to/from the toolchain-independent Value
class are used instead.
This commit makes it possible to compile these files in
Emscripten/WebAssembly builds, contributing to the migration effort
tracked by #220.
> Delete NaCl conv from cert provider types.{h|cc}

- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.cc
- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.h
- example_cpp_smart_card_client_app/src/entry_point_emscripten.cc
This changes the GlobalContextImplEmscripten::PostMessageToJs()
implementation to forward the operation to the main Emscripten thread.
This fixes the inability to use this method from background threads,
since they're not allowed to make JavaScript operations like calling
back to the GoogleSmartCard.EmscriptenModule JavaScript class.
This contributes to the WebAssembly migration effort, as tracked
by #220.
> Post Emscripten JS messages only from main thread

- Makefile
This commit adds a new makefile, located in the project's root
directory. This makefile can be used to build the whole project in the
specified configuration, namely the TOOLCHAIN (can be "pnacl" [default]
or "emscripten") and the CONFIG (can be "Release" [default] or "Debug").
The main benefit is that the makefile syntax is more suitable than shell
scripts for describing rules like "target foo should always be compiled,
but target bar only under toolchain X" and similar more complex ones.
The makefile also naturally describes dependencies and prerequisites, as
opposed to hardcoding the "magically working" order of targets in shell
scripts.
Currently, only a few targets can be built in the TOOLCHAIN=emscripten
configuration. Follow-up changes will migrate the remaining targets, so
that …
> Introduce top-level Makefile

- common/make/internal/executable_building_emscripten.mk
- example_cpp_smart_card_client_app/build/nacl_module/Makefile
This commit adds automatic detection of static library or any other
specified dependency changes, triggering the rebuild of the resulting
Emscripten .wasm/.js files.
This resolves one of the feature gaps between our Emscripten builds
scripts and the Native Client ones. This effort is tracked by #177.
The commit also drops DEPS dependencies from the
//example_cpp_smart_card_client_app, since the referenced targets aren't
implemented in Emscripten builds. Moreover, our new approach will be to
drop these DEPS wherever possible, and only leave the dependencies
described in the root //Makefile; this will make the build scripts simpler
and more reliable.
> Emscripten: rebuild on library/dependency change

- common/js/src/executable-module/executable-module.js
- common/make/js_building_common.mk
- example_cpp_smart_card_client_app/src/background.js
Change the C++ Example App to conditionally load either the
Emscripten/WebAssembly or the Native Client module, depending on the
build configuration.
This completes the first workable prototype of the WebAssembly version
of the C++ Example App, as tracked by #220.
> Wire up Emscripten module in C++ Example App

- common/make/internal/executable_building_emscripten.mk
Extend the makefiles used in Emscripten builds to perform the cleanup of
all resulting and intermediate files on "make clean".
The tracking issue for Emscripten/WebAssembly build implementation
is #177.
> Add cleaning rules into Emscripten build scripts

- common/js/src/executable-module/emscripten-module.js
This commit adds an observer that's called when the Emscripten module
crashes. It also adds observers for stdout/stderr messages received from
the module, forwarding these messages to the JavaScript logger (making
them discoverable in DevTools and also exportable via functionality like
"Export logs").
This contributes to the Emscripten/WebAssembly migration effort tracked
by #220.
> Catch Emscripten logs and handle crashes

- common/js/src/executable-module/emscripten-module.js
Make sure the destructor of the GoogleSmartCardModule C++ class is
called when the JavaScript class GoogleSmartCard.EmscriptenModule is
disposed of. This makes sure the C++ memory is freed in this flow.
This change is a small cleanup that isn't extremely useful for
real-world use cases, since a smart card client app never shuts down the
module (unless it crashes, but in that case the whole app is
self-reloaded). But the code is more sane this way, and also might make
integration tests consume less memory. The tracking issue is #220.
> Free C++ object on Emscripten module disposal

- common/js/src/executable-module/emscripten-module.js
Mark the reference to the C++ "GoogleSmartCardModule" object in
JavaScript as having unknown type ("?" in the Closure Compiler
notation), so that the compiler doesn't emit warnings on accessing
unknown properties of it.
This is small cleanup for the effort tracked by #220.
> Make Emscripten C++ object untyped in JavaScript

- common/cpp/build/tests/.gitignore
- example_cpp_smart_card_client_app/build/executable_module/.gitignore
- example_cpp_smart_card_client_app/build/integration_tests/.gitignore
- smart_card_connector_app/build/nacl_module/.gitignore
- third_party/ccid/naclport/build/.gitignore
- third_party/libusb/naclport/build/.gitignore
- third_party/libusb/naclport/build/tests/.gitignore
- third_party/pcsc-lite/naclport/common/build/.gitignore
- third_party/pcsc-lite/naclport/cpp_client/build/.gitignore
- third_party/pcsc-lite/naclport/cpp_demo/build/.gitignore
- third_party/pcsc-lite/naclport/server/build/.gitignore
- third_party/pcsc-lite/naclport/server_clients_management/build/.gitignore
Add directories that are produced by Emscripten/WebAssembly builds in
this project into .gitignore files, as these are temporary files that
shouldn't be tracked by the version control system.
This is a minor cleanup for the effort tracked by #177.
> .gitignore Emscripten temporary build artifacts

- common/js/src/executable-module/executable-module.js
- common/make/common.mk
- common/make/executable_building.mk
- common/make/js_building_common.mk
Make compiled JavaScript files be stored in different locations
depending on the TOOLCHAIN environment variable.
This fixes the problem that JS files can stay non-recompiled after
switching the TOOLCHAIN variable. E.g., in the following scenario
resulting JS files would still refer to emscripten if built without this
commit:
TOOLCHAIN=emscripten make && TOOLCHAIN=pnacl make
The underlying reason is that when both the input files are unchanged
and the resulting file paths don't depend on the toolchain, Make
doesn't see any reason to trigger recompilation. We don't have
prerequisites that depend on the compilation flags, and this would
be tricky to implement.
The solution in this commit makes sure that JS files are put into
different locations for pnacl and emscripten, which bypasses the …
> Put built JS files into dir depending on toolchain

- example_cpp_smart_card_client_app/src/application.h
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
Rename variables/functions and reword comments to use generic terms
instead of referring to Native Client, since the code can be compiled in
two modes now: Native Client and Emscripten/WebAssembly.
This is a pure refactoring CL; the tracking issue is #220.
> Delete old references to NaCl from Example C++ App

- common/integration_testing/build/Makefile
- common/integration_testing/include.mk
- example_cpp_smart_card_client_app/build/integration_tests/Makefile
This commit disables installation of "public" headers from the
//common/integration_testing library into a common include
directory. Instead, the path to this library is simply added
into the include search path in needed makefiles.
More background on this refactoring is in #132.
> Not install //common/integration_testing headers

- smart_card_connector_app/build/nacl_module/Makefile
- third_party/ccid/naclport/build/Makefile
- third_party/libusb/naclport/build/Makefile
- third_party/libusb/naclport/build/tests/Makefile
- third_party/libusb/naclport/include.mk
- third_party/pcsc-lite/naclport/server/build/Makefile
This commit disables installation of "public" headers from the
//third_party/libusb library into a common include directory.
Instead, the path to this library is simply added into the include
search path in needed makefiles.
More background on this refactoring is in #132.
> Not install //third_party/libusb headers

- common/integration_testing/build/Makefile
- common/make/common.mk
- common/make/executable_building.mk
- common/make/internal/executable_building_nacl.mk
This commit deletes the makefile rules that implement the
installation of libraries' headers into the comment include directory.
All usages of these rules have been removed by now.
Also fix one remaining usage of common installed headers - the
//common/integration_testing library - which was incorrectly specifying
the include directories.
This completes the refactoring tracked by #132.
> Delete header installation scripts

- common/js/src/messaging/port-message-channel.js
This commit avoids emitting the following JavaScript error in the
DevTools console in case the cross-extension message port fails to
connect:
"Unchecked runtime.lastError: Could not establish connection.
Receiving end does not exist."
This could happen when, for example, the middleware app tries to talk to
the Connector app, but the latter is not installed.
This commit is only a cosmetic improvement: instead of logging something
about unhandled errors, which might be confusing, an "info" log message
is printed. The actual error handling isn't affected by this commit: as
before, the connection error causes the message channel to be shut down.
> Suppress JS error on message port connection error

- third_party/libusb/naclport/src/libusb_over_chrome_usb.cc
This commit is a small cleanup: an unused variable is deleted from
LibusbOverChromeUsb::WrapLibusbTransferCallback().
This is a preparation for migrating the libusb library port to
Emscripten, since the latter's compiler detects the unused lambda
capture as a warning (causing a compilation error).
> libusb: Drop unused variable

- Makefile
- third_party/libusb/naclport/src/chrome_usb/api_bridge.cc
- third_party/libusb/naclport/src/chrome_usb/types.cc
- third_party/libusb/naclport/src/chrome_usb/types.h
- third_party/libusb/naclport/src/libusb_over_chrome_usb.cc
- third_party/libusb/naclport/src/libusb_over_chrome_usb_unittest.cc
This commit allows to build our port of the libusb library under
Emscripten.
For the background, our libusb implementation is header-compatible with
the third-party libusb library, but its implementation is completely
different from the latter: instead of talking to drivers and OS-level
components it redirects all requests to the chrome.usb Extensions
API. Before this commit, our port could only be compiled under
Native Client.
This commit contributes to the effort of migrating the Smart Card
Connector app to Emscripten/WebAssembly, as tracked by #233.
> libusb: Migrate to Emscripten

- Makefile
This commit enables compiling the CCID Free Software Driver in the
Emscripten/WebAssembly mode.
The code in this driver is a pure C code that doesn't use itself
low-level OS interfaces (like direct USB access), which is why it can
be compiled using Emscripten without code adaptations.
This commit contributes to the Emscripten/WebAssembly migration
effort tracked by #233.
> ccid: Enable compilation under Emscripten

- Makefile
- smart_card_connector_app/src/pp_module.cc
- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.h
This commit allows to compile the "pcsc_lite_server" component
(which is a webport of the PC/SC-Lite daemon) under Emscripten.
Brief overview of the changes:
* Replace the usage of Native Client specific pp::Instance class with
the toolchain-agnostic GlobalContext class;
* Replace the usage of Native Client specific pp::Var* classes with
the toolchain-independent Value class;
* Drop unneeded dependency on the compilation of "libusb" (it's not
required since the change that disabled installation of libusb headers
into a common directory);
* Change the top-level makefile to compile the server regardless of the
chosen toolchain.
as tracked by #233.
> pcsc-lite: Migrate server/daemon to Emscripten

- common/make/internal/executable_building_emscripten.mk
This commit enables several Emscripten debugging features when the code
is compiled in the CONFIG=Debug mode.
These debugging features (more extensive debug symbols, runtime memory
access checks, etc.) will aid developers to debug the applications.
There's no change for the Release builds, since many of these checks
introduce a significant runtime overhead.
This commit contributes to the WebAssembly migration effort, as tracked
by #177.
> Enable more Emscripten debugging capabilities

- clean-all.sh
This commit refactors the //clean-all.sh script to delegate the actual
build functionality to the //Makefile script.
Besides simplifying the script and removing duplicated information about
directories to be built, this also adds support of the
Emscripten/WebAssembly builds into clean-all.sh.
as tracked by #177.
> Rewrite clean-all.sh to use the top-level Makefile

- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
Implement a special case in the to/from Value conversions that converts
a null value into nullptr and vice versa.
This is a "fake" conversion in the sense that it's only used to denote
the type being null - there's no other payload involved. This special
case will be used in follow-up commits in order to support functions
whose input or output argument must always be null (such functions exist
in the PC/SC-Lite API). Previously, the Native Client's pp::Var::Null
type has been used for such arguments, but this commit adds a
toolchain-independent alternative that can be used in WebAssembly
builds.
tracked by #185.
> Add conversion of Value to/from nullptr

- smart_card_connector_app/src/pp_module.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/ready_message.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/ready_message.h
Change the implementation of the PC/SC-Lite server_clients_management
ready_message.{h,cc} files to use the toolchain-independent Value
class instead of the Native Client specific primitives.
This contributes to the Emscripten/WebAssembly migration effort, as
> Migrate ready_message.{h,cc} to Value

- clean-all.sh
Change the //clean-all.sh script to keep the //env intact by default.
This means that the SDKs downloaded by the //env/initialize.sh script
(Emscripten and Native Client SDK) are preserved.
This makes the clean-all.sh script more convenient to use, since
developers usually need to delete intermediate build artifacts but not
SDKs, and reinitializing SDKs is a time-consuming step.
The "-f" option is also added that reverts to the old behavior, cleaning
both build artifacts and the env.
> Make clean-all.sh preserve env by default

- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.h
Change the implementation of the PC/SC-Lite server_clients_management
client_request_processor.{h,cc} files to use the toolchain-independent
Value class instead of the Native Client specific primitives.
This contributes to the Emscripten/WebAssembly migration effort, as
> Migrate client_request_processor.{h,cc} to Value

- common/cpp/src/google_smart_card_common/value_conversion.h
Improve compilation error messages that appear when the caller misuses
the value_conversion.h file to convert a Value to/from an optional<>
object. Such conversions are intentionally unsupported (and only
supported for optional<> fields of structs and for optional<> remote
call arguments). This commit makes sure that misuses fail immediately
and provide an informative compilation error message that points to the
culprit code.
Before this commit, the failure would only occur at the linking stage,
since the optional<> class satisfies the std::is_class criteria and
therefore will accidentally be picked up by the struct-to-dictionary
conversion code.
This commit is a small developer-only improvement of the
toolchain-independent code that was added for the Emscripten/WebAssembly
project as …
> Better compile error for optional-to-Value convert

- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion.h
- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion_unittest.cc
Extend the RemoteCallArgumentsExtractor class to support extracting
optional arguments: for such arguments, the Value can be equal to null,
which denotes that the optional argument is unset.
This capability will be used in follow-up commits in order to support
receiving remote calls for functions with optional arguments.
as tracked by #233.
> Support optional in RemoteCallArgumentsExtractor

- smart_card_connector_app/build/nacl_module/Makefile
- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application.h
- smart_card_connector_app/src/entry_point_nacl.cc
Refactor the Smart Card Connector app's core code into a Native Client
specific entry_point_nacl.cc and a toolchain-independent
application.{h,cc} piece.
This commit is a preparation for implementing another - Emscripten
specific - entry point for WebAssembly builds. This migration effort is
> Extract NaCl-specific entry point of Connector app

- Makefile
This commit allows building the PC/SC-Lite server_clients_management
library in the Emscripten mode. Previously it was built only for
Native Client builds, but due to the landed series of commits it can be
compiled using any of the two toolchains now.
> Build PCSC server_clients_management in Emscripten

- smart_card_connector_app/build/nacl_module/Makefile
- smart_card_connector_app/src/entry_point_emscripten.cc
- smart_card_connector_app/src/entry_point_nacl.cc
Add implementation of the C++ entry point code for the Smart Card
Connector app in Emscripten builds. This entry point implements the
necessary bootstrapping and creates the Application class that
implements the toolchain-independent PC/SC-Lite daemon functionality.
> Implement Emscripten entry point for Connector app

- smart_card_connector_app/src/background.js
Add support of Emscripten modules into the Smart Card Connector's
background page JavaScript code. With this commit, the JS behavior will
depend on the TOOLCHAIN constant (which, in turn, is filled based on the
environment variable), loading either the Emscripten or the Native
Client module.
as tracked by #233.
> Support Emscripten in Connector's background JS

- Makefile
This commit allows building the while Smart Card Connector app in the
Emscripten mode. Previously it was built only for Native Client builds,
but due to the landed series of commits it can be compiled using any
of the two toolchains now.
Note that the Emscripten build isn't fully functional yet - this will be
addressed by follow-up commits.
> Build Connector app in Emscripten

- common/make/internal/executable_building_emscripten.mk
Enable the "DISABLE_EXCEPTION_CATCHING=0" flag when compiling C++ files
under Emscripten, so that the C++ exception support is enabled.
This flag was disabled by default since it affects performance and
binary size, but we're enabling this, as smart card middleware apps
reportedly rely on C++ exceptions. We don't set the flag only for
example_cpp_smart_card_client_app, since the flag must be used
consistently, which includes the common libraries that are linked into
it.
tracked by #220.
> Enable C++ exceptions in Emscripten builds

- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
Fix the crash that's happening in case
PcscLiteServerClientsManager::Detach() was used, with the crash
potentially happenning during the app shutdown.
The bug is that the destructor will be calling Detach() for the second
time, meanwhile that method is asserting against being called multiple
times. The fix is to replace the assert with an early exit.
> Fix shutdown bug in PcscLiteServerClientsManager

- common/cpp/src/google_smart_card_common/logging/logging.cc
This commit is a cosmetic improvement of log messages from the
Emscripten modules: the "NaCl module" prefix won't be printed
anymore in non-NaCl builds.
For the background, the reason why this prefix is added under Native
Client is that the NaCl logs are redirected to Chrome's own stderr logs.
Therefore, to simplify reading the logs, we added this distinguished
prefix in NaCl builds. In Emscripten, on the contrary, such prefixes are
useless as Chrome doesn't embed Emscripten logs into its own logs.
as tracked by #185.
> Omit "NaCl module" log prefix in Emscripten builds

- common/make/internal/executable_building_emscripten.mk
Set the "DISABLE_EXCEPTION_CATCHING=0" flag in Emscripten builds not
only in Debug but also in Release mode. The C++ exception support is
needed unconditionally.
tracked by #220.
> Enable C++ exceptions in Emscripten Release builds

- docs/updating-pcsc-lite.md
- third_party/pcsc-lite/patches/0001-Fix-compiler-warning.patch
- third_party/pcsc-lite/src/src/hotplug_libusb.c
Cherry-pick the following commit from the upstream PC/SC-Lite
repository:
199f8455745654d3856251a949ad630c4d1a3c13
Fix compiler warning
hotplug_libusb.c: In function ‘HPSearchHotPluggables’:
hotplug_libusb.c:498:4: warning: cast between incompatible function
types from ‘void (*)(int *)’ to ‘void * (*)(void *)’
[-Wcast-function-type]
498 |    (PCSCLITE_THREAD_FUNCTION( )) HPEstablishUSBNotifications, pipefd);
|    ^
This cherry-picked fix is necessary for the WebAssembly build of
PC/SC-Lite to work (tracking issue #233), since it fixes the wrong
function signature that's causing stack corruption when run under
Emscripten. (For some reason, this bug wasn't causing any issues
when run as a native binary or under Native Client.)
The cherry-picked patch file can be deleted once the upstream …
> Cherry-pick PC/SC-Lite bugfix for thread function

- third_party/ccid/naclport/build/Makefile
Make sure the Info.plist file is produced by the CCID webport's makefile
by default, since this file is used by other makefiles in this project.
This is a follow-up to change #302 (linked to the issue #233 that tracks
the Emscripten/WebAssembly migration), which mistakenly removed the
Info.plist file from being produced by default.
> Fix missing Info.plist file build error

- third_party/pcsc-lite/naclport/server/src/socketpair_emulation.cc
Fix a potential bug in PC/SC-Lite webport's socketpair_emulation.cc that
could lead to reading from a null shared pointer. The bug is that
std::move() and dereference are occurring within the same
sub-expression, for which C++ doesn't give guarantee about the ordering
between these two operations.
We don't have any evidence that this bug could occur in practice
(especially in the NaCl builds this code seemed to work reliable), but
it's important to fix this potential unspecified behavior anyway.
> Fix unordered move in socketpair_emulation

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- third_party/libusb/naclport/src/libusb_over_chrome_usb_unittest.cc
Delete "using" directives and declarations from C++ code where they're
not actually used. This is a pure refactoring change.
This was found via clang-tidy ("misc-unused-alias-decls" and
"misc-unused-using-decls" diagnostics).
> Drop unused "using" directives and declarations

- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
Make sure function parameters are named in the same way in the .h and in
the .cc file for the PcscLiteOverRequester class. This is a pure
refactoring change.
This was found via clang-tidy
("readability-inconsistent-declaration-parameter-name" diagnostic).
> Fix inconsistent parameter naming

- common/cpp/src/google_smart_card_common/formatting.cc
- common/cpp/src/google_smart_card_common/multi_string.cc
- third_party/libusb/naclport/src/libusb_contexts_storage.cc
Make sure that non-trivial local C++ variables that are returned by
value aren't marked as "const", since this is a pessimization that
prevents move'ing the returned object. This is mostly a refactoring,
since the performance difference must be negligible in these cases.
This was found via clang-tidy ("performance-no-automatic-move"
diagnostic).
> Cleanup returning const objects

- example_cpp_smart_card_client_app/src/application.cc
- example_cpp_smart_card_client_app/src/entry_point_nacl.cc
- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/entry_point_nacl.cc
- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
Add explicit casts to void in places that call
std::unique_ptr::release() without storing its result anywhere. This
clearly shows the programmer's intention, as opposed to potential places
where this could be done by mistake. This is a pure refactoring change,
made in order to improve readability and to silence the clang-tidy
diagnostic.
This was found by the "bugprone-unused-return-value" clang-tidy
diagnostic.
> Explicitly cast unowned release() to void

- example_cpp_smart_card_client_app/src/application.h
- smart_card_connector_app/src/application.h
Fix two C++ headers to have the include guard that was missing.
This is a pure refactoring change.
This was found by clang-tidy (the "llvm-header-guard" diagnostic).
> Add missing header guards

- common/cpp/src/google_smart_card_common/value_conversion.h
- third_party/libusb/naclport/src/libusb_tracing_wrapper.h
Fix a couple of occasions where a C++ single-argument constructor
isn't marked as "explicit". This is a pure refactoring change.
This was found by clang-tidy (the "google-explicit-constructor"
diagnostic).
> Mark constructors as explicit when possible

- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.h
Fix the pcsc_lite_over_requester.h header to not contain the unnamed
namespace - such namespace usage isn't canonical and can lead to symbol
duplication (across every .cc file that included it). Also, while we're
here, move the string constant from the .h file to the .cc file. This is
a pure refactoring change.
This was found by clang-tidy ("google-build-namespaces" and
"misc-definitions-in-headers" diagnostics).
> Avoid unnamed namespace in a header file

- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion.h
Fix the RemoteCallArgumentsExtractor's class copy constructor signature
to the canonical form: const-ref instead of a non-const-ref. This is a
pure refactoring change.
This was found by the "google-runtime-references" clang-tidy diagnostic.
> Fix copy constructor signature

- common/cpp/src/google_smart_card_common/tuple_unpacking.h
Add inclusion of stddef.h into tuple_unpacking.h, since the latter uses
size_t, which is not a built-in type but rather a definition in one of
the standard header files. This is a pure refactoring change.
This issue was highlighted by the build error when running clang-tidy.
> Add missing include for size_t

- third_party/libusb/naclport/src/libusb_over_chrome_usb.cc
- third_party/libusb/naclport/src/libusb_over_chrome_usb.h
- third_party/libusb/naclport/src/libusb_over_chrome_usb_unittest.cc
Change a few C++ class methods to be static methods or global-namespace
functions, in cases when they don't use any of the class internal state.
This is a pure refactoring change.
This was found by clang-tidy (the
"readability-convert-member-functions-to-static" diagnostic).
> Make methods static when possible

- common/cpp/src/google_smart_card_common/messaging/typed_message_router.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
- third_party/libusb/naclport/src/chrome_usb/api_bridge.h
- third_party/libusb/naclport/src/libusb_over_chrome_usb.h
- third_party/libusb/naclport/src/libusb_tracing_wrapper.h
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/pcsc_lite_tracing_wrapper.h
- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.h
Add the "override" specific to C++ methods where they were missing
(mainly for destructors). This is a pure refactoring change.
This was found via clang-tidy (the "modernize-use-override" diagnostic).
> Add missing override specifiers

- clean-all.sh
Speed up the clean-all.sh script by running make with "-j10", which
makes it process directories in parallel. This is the same number of
parallel processes that is used in the make-all.sh script.
> Parallelize clean-all.sh

- env/initialize.sh
Fix the "unbound error" occurring in env/initialize.sh in case when the
existing NaCl SDK is present but the environment doesn't contain the
NACL_SDK_ROOT variable.
This is a follow-up to the PR #178 where the problem was introduced,
attributed to tracking issue #177.
> Fix env/initialize.sh env error with present NaCl

- env/constants.sh
Update the env initialization scripts to use a newer Emscripten
version - 2.0.13. This version brings a few relevant bugfixes
(notably, fixes for some threading-related crashes).
This version was tested a bit manually with the applications from this
repository and showed positive results.
> Uprev pinned Emscripten to 2.0.13

- docs/building.md
Add a note into the docs that CMake needs to be installed when compiling
the code from this repository under Emscripten.
This commit contributes to the WebAssembly/Emscripten migration effort
tracked by #177.
> Document CMake dependency

- common/make/internal/executable_building_emscripten.mk
This commit attempts to avoid passing useless flags to the Emscripten
compiler and linker (emcc), by maintaining compilation and linking flags
separately instead of putting all of them together. This makes the build
logs slightly more readable (as the number of command-line flags becomes
less on average) and also avoids nonsensical no-op flags (like
EXPORT_NAME pointing to the name of a static library).
The main information about which Emscripten flags are needed on which
stage is present in this file:
https://github.com/emscripten-core/emscripten/blob/master/src/settings.js
This commit is expected to bring no functional differences on the
resulting build program. The tracking issue is #177.
> Don't pass Emscripten linker flags to compiler

- common/js/src/messaging/port-message-channel.js
Fix the JS error that was occurring in the
"testSubstituteArrayBuffersRecursively" JavaScript test, caused by some
global object not being mocked. The fix is to silence this error by
adding a check of that global object, which also makes the production
code slightly more bullet-proof.
This is a follow-up to PR #226, which introduced this test.
> Fix JS exception in ArrayBuffer substitution test

- common/make/internal/executable_building_emscripten.mk
Allow the Emscripten module to use more memory than the default limit
(which currently is 16 MiB), by dynamically increasing the memory at
runtime when needed thanks to the "ALLOW_MEMORY_GROWTH=1" flag.
This functionality emits a link-time warning that it can slow down the
program due to it using Pthreads as well, but it should be of a minor
concern in our case (because it only seems to affect JS-to-C++
communication).
This commit also specifies the "ABORTING_MALLOC=1" flag, since it's
safer to fail fast and the default when using "ALLOW_MEMORY_GROWTH=1" is
the opposite.
This change contributes to the WebAssembly/Emscripten migration effort,
tracked by #177.
> Allow dynamic memory growth in Emscripten modules

- common/make/internal/executable_building_emscripten.mk
Make the Makefile scripts display the correct error message when the
Emscripten build is requested without the required environment variables
being set.
The problem was a syntax error in the $(error) function invocation, as
the multi-line message was missing the backslash escape.
This change contributes to the WebAssembly migration effort tracked
by #177.
> Fix error message when Emscripten env is unset

- common/make/internal/executable_building_emscripten.mk
Replace the "-g4" compiler/linker flag with "-g" when using
Emscripten. Apparently, "-g" started to produce more useful debug
information than "-g4" in recent Emscripten versions, in particular
regarding the recently added DWARF debug format support:
https://github.com/emscripten-core/emscripten/issues/13534
Note that the debug source maps are only produced at "g4", but we
never supported them properly in this project (in particular, due to
DevTools not being able to load them in Extensions/Apps - see
https://crbug.com/974543).
This contributes to the WebAssembly/Emscripten migration effort, as
tracked by #177.
> Use g instead of g4 with Emscripten

- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
Replace the "PC/SC-Lite client handler for ..." text in log messages
with just "PC/SC from ...". This makes the log messages shorter a bit
while preserving all information, which helps readability.
This change contributes to the logging improvements tracked
by #146.
> Shorten log prefix for incoming PC/SC commands

- common/cpp/src/google_smart_card_common/logging/syslog/syslog.cc
Delete the "[syslog]" prefix printed in every log message that's created
via the syslog() call. This prefix is not really useful - the original
idea was to visually disambiguate the logs printed by C++ code from the
logs emitted by third-party C code that uses syslog. In reality, there's
not much ambiguity there, so this prefix was just cluttering the logs.
This change contributes to the logging improvements tracked
by #146.
> Remove prefix from the syslog log messages

- common/js/src/logging/logging.js
Make the number of log messages retained for the Log Export to be twice
as much as before: in Release builds, it becomes 2000 messages now.
This should help in investigating some customer issues, because
apparently sometimes real-world logs contained information just around
the zone that was cut off.
This change is still a conservative change, because we need to take
memory consumption in mind. Extra 1000 messages added here would mean
100-200 KB of extra memory, which sounds tolerable.
> Double the log buffer capacity

- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_debug_dump.cc
Stop printing structure names in PC/SC logs, in cases where the
type is already clear from the context. Also remove some unneeded
extra braces.
Example of changes:
* BEFORE: SCardListReaders: returning 0x00000000 ["Command successful."], mszReaders=MultiString["Foo 00 00"]
* AFTER: SCardListReaders: returning 0x00000000 ["Command successful."], mszReaders=["Foo 00 00"]
* BEFORE: SCardGetStatusChange(hContext=0x595DF1EC, dwTimeout=60000, rgReaderStates=0xFEB403D8([SCARD_READERSTATE(szReader="Foo 00 00", pvUserData=0x00000001, dwCurrentState=SCARD_STATE_CHANGED|SCARD_STATE_PRESENT|SCARD_STATE_INUSE)]))
* AFTER: SCardGetStatusChange(hContext=0x595DF1EC, dwTimeout=60000, rgReaderStates=0xFEB403D8[{szReader="Foo 00 00", pvUserData=0x00000001, …
> Remove SCard struct names and extra braces from logs

- common/cpp/src/google_smart_card_common/logging/function_call_tracer.cc
- common/cpp/src/google_smart_card_common/logging/function_call_tracer.h
Print a function call index (a shared monotonically incrementing
counter) when logging function call tracer.
This should simplify investigating log messages collected in the field,
since it'll be possible to correlate the "called..." and the "returning"
log messages, therefore knowing which input parameters were passed to
the completed call and being able to distinguish between multiple calls
with the same parameters.
> Log function call indices

- common/js/src/logging/log-formatting.js
- common/js/src/logging/logging.js
Stop printing relative times (like "[  0.007s]") in the JavaScript logs.
These times aren't really necessary now that we're printing absolute
times since #108.
The only remaining benefit of relative times was that they allowed
to distinguish logs from multiple instances in case they work
concurrently and their logs are squashed together. However, in
practice this was only relevant in a specific scenario (reading
Chrome OS system logs from a device that is locked and has the
NaCl-based smart card applications installed both in-session
and on the Login Screen). Assuming this a rare scenario that will
anyway disappear with the NaCl deprecation, it seems fine to
reduce the log clutter by removing the relative times.
This change contributes to the logging improvements tracked
by #146.
> Remove relative time from JS logs

- common/make/internal/executable_building_emscripten.mk
Suppress the link-time warning emitted by Emscripten due to our usage of
multi-threading together with dynamic memory growth:
warning: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code
slowly, see https://github.com/WebAssembly/design/issues/1271
We took this warning into consideration and decided to trade the
performance in favor of lower memory consumption. (In reality, the
performance loss is likely small, since a big chunk of the run time is
spent on interprocess communication.)
So reduce the build log spam by silencing this warning, which was
emitted many times - once for every target binary or static library.
This change is a small improvement to the WebAssembly build
support that is tracked by #177.
> Silence Emscripten Pthreads performance warning

- common/make/common.mk
This suppresses the first-run dialogs when running Chrome for executing
tests. In particular, this allows to skip the blocking popup "make
Chrome the default browser" that was introduced in recent Chrome
versions, and which required a manual mouse click to proceed to the
tests.
> Suppress the "default browser" popups in test runs

- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.cc
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.h
Delete old NaCl-specific code from the PC/SC-Lite webport's
scard_structs_serialization.{h|cc} files. They are not needed anymore,
now that all remaining code was cleaned from doing direct
"C++-struct <-> NaCl-specific-type" conversions, and switched to using
the toolchain-independent "Value" type.
This is a pure refactoring CL. Tis contributes to the
WebAssembly/Emscripten migration effort tracked by #220.
> Remove NaCl specifics from scard_structs_serialization

- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.cc
- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion.cc
- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion.h
- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion_unittest.cc
Add the missing safety check that prevents a huge integer in a Value
object from being converted to a double Emscripten/JavaScript number
with a loss of precision.
This improvement is part of the WebAssembly migration effort, tracked
by #185.
> Strengthen int conversions to Emscripten val

- common/cpp/src/google_smart_card_common/global_context_impl_emscripten.cc
Correct the comment about the allegedly non-portable code in
global_context_impl_emscripten.cc that converts pointers to integers and
back. Apparently, it's a valid C++, so it's not a hack that only works
under Emscripten.
This is a pure cleanup commit; it contributes to the WebAssembly
migration effort tracked by #185.
> Fix comment about non-portable Emscripten code

- common/js/src/logging/crash-loop-detection-unittest.js
- common/js/src/logging/crash-loop-detection.js
Improve the crash loop detector for the case when the crash happens in
the C/C++ code compiled under Native Client. Before this commit, the
crash loop detection would be triggered too late, after Chrome Native
Client system already began the throttling. This means that instead of
useful logs that contain information before the actual crash, the only
information would be like this:
>   Failed to load NaCl module with the following message: NaCl module
>   load failed: ServiceRuntime: failed to start
With the following information in Chrome logs:
>  NaCl process launch failed: Process creation was throttled due to
>  excessive crashes
This commit avoids this situation by tightening the crash loop detection
constants, so that the detector is triggered earlier and therefore
avoids this dead …
> Detect NaCl crash loops before Chrome throttles us

- prepare-binaries-for-github-release.py
Fix this error shown when running this script in recent versions:
>  IOError: [Errno 2] No such file or directory:
>  './example_js_standalone_smart_card_client_library/js_build/Debug/google-smart-card-client-library.js'
The root cause is that, since #274, compiled JavaScript files are put
into toolchain-specific directories. For example, instead of a single
"Debug" directory there are now two directories "emscripten_Debug" and
"pnacl_Debug" (for the reasons explained on that change).
In case of google-smart-card-client-library.js, the code in both
directories is the same, so we're free to choose any of them. I'm
proceeding with "emscripten_Debug", since, eventually, we'll drop the
NaCl support completely.
> Fix paths in prepare-binaries-for-github-release.py

- third_party/libusb/webport/src/libusb_over_chrome_usb.cc
Change the USB wrapper (used in the webport of libusb, which is
transitively used for the CCID driver and therefore the Smart Card
Connector app) to stop asserting that chrome.usb.getConfigurations() can
only return a single active configuration. Instead, just proceed with
the first configuration among those that are marked as active.
Meanwhile multiple active configurations is most likely a bug in the
chrome.usb API (https://crbug.com/1218141), we need this workaround
until that issue is fixed in Chrome, since currently the Connector app
ends up in a crash loop when such device is attached.
> Workaround for chrome.usb.getConfigurations issue

- third_party/webports/src/src/build_tools/pip_install.sh
- third_party/webports/src/src/requirements.txt
Python 2 isn't maintained anymore, so more and more stuff stops working.
But as NaCl env build scripts are using it (and no one is interested in
migrating them to Pytnon 3), this commit fixes the issues that are
happening right now:
* pip should be fetched from a different URL (a special URL for a
2.7-compatible version),
* some module called "astroid" should be installed with the version
before 2.0, otherwise it fails with syntax errors.
> Fix env/initialize.sh Python 2 errors

- common/cpp_unit_test_runner/src/build_emscripten.mk
Fix the unit test build scripts to only pass the MODULARIZE flag to the
Emscripten linker, and stop passing it to the compiler. The latter
has been ignoring this flag anyway, and also newer Emscripten versions
started to emit errors when a useless flag like this is supplied.
This commit unblocks updating to a newer Emscripten version, and
contributes to the WebAssembly migration effort tracked by #185.
> Only pass MODULARIZE to Emscripten linker in tests

- env/constants.sh
Switch the version hardcoded in the env initialization scripts to use
the currently up-to-date version of Emscripten. It brings various
improvements that the Emscripten team made recently, and at the same
time doesn't regress on our use cases (we couldn't update earlier due to
a few blockers in the previous releases, like Clang crashes).
> Update Emscripten to 2.0.24

- docs/updating-pcsc-lite.md
- third_party/pcsc-lite/patches/0001-Fix-IFD_NOT_SUPPORTED.patch
- third_party/pcsc-lite/src/src/prothandler.c
Cherry-pick the following commit from the upstream PC/SC-Lite
repository, which fixes a 1.9.1 regression:
>   7730f6c54d7fb6a910d291e2d48c92d2a5abf688
>   SetProtocol: Handle IFD_NOT_SUPPORTED from the driver
> 
>   If the driver returns IFD_NOT_SUPPORTED from the function
>   IFDHSetProtocolParameters() it indicates the "command" is not
>   supported.
>   It is different from IFD_PROTOCOL_NOT_SUPPORTED that indicates the
>   "prorocol" is not supported.
> 
>   The problem was with a ACR38U CCID and a memory card. The
>   SetParameters() fails but the card can still be used using the default
>   protocol.
> 
>   The behaviour is identical to what we had before the commit
>   5d58577093f56dbcfbf754940f885ed8fcdba206.
> 
>   Thanks to Godfrey Chung for the bug report
>   "pcsc-lite 1.9.1: …
> Cherry-pick PC/SC-Lite bugfix for unsupported commands

- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Update the heuristic we use in the Smart Card Connector app for hiding
failure readers from the UI.
The background on this heuristic is the following: some USB devices are
composite devices, which means they expose several different interfaces
for different purposes (e.g., one having bInterfaceClass=11
(Chip/SmartCard) and another bInterfaceClass=2 (Communications)). The
CCID driver we use is implemented in a way that it tries to connect to
every interface. Failures on unrelated interfaces are handled by the
driver in roughly the same way as failures on unsupported smart card
interfaces. We want to inform the user about the latter but not the
former, which is why we implemented the heuristics: let's hide the
failed readers that have the interface number greater than zero.
After updating …
> Fix heuristics for hiding spuriously failed reader

- format-code.sh
Change the format-code.sh developer script to also automatically reformat
any change JavaScript file.
In the past, all JS code written in this repository was formatted
manually. The plan is to switch to the clang-based automatic formatting,
and the first step on this route is to apply it to every changed file.
This contributes to the refactoring effort tracked by #264.
> Enable *.js reformatting in format-code.sh

- common/js/src/container-helpers.js
- common/js/src/logging/debug-dump.js
- common/js/src/requesting/remote-call-message.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
Refactor JavaScript code to use Array.isArray() instead of
goog.isArray().
goog.isArray() got deprecated and removed from the recent
versions of the Closure Library.
This contributes to the refactoring effort tracked by #264.
> Replace usages of goog.isArray

- common/js/src/container-helpers.js
- common/js/src/logging/debug-dump.js
- common/js/src/messaging/mock-port.js
- third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
- third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
Refactor JavaScript code to use goog.functions.isFunction()
instead of goog.isFunction().
goog.isFunction() got deprecated and removed from the recent
versions of the Closure Library; for whatever reason, they decided to
add a synonym "goog.functions.isFunction".
This change contributes to the refactoring effort tracked by #264.
> Replace usages of goog.isFunction

- common/js/src/messaging/mock-port.js
- third_party/pcsc-lite/naclport/server_clients_management/src/readiness-tracker.js
Fix a couple of occasions in the JavaScript code where a private member
wasn't marked as such (via @private).
This is expected to be a non-function change, which contributes to the
refactoring effort tracked by #264.
> Add missing @private

- common/integration_testing/src/google_smart_card_integration_testing/integration-test-controller.js
- common/js/src/deferred-processor.js
- common/js/src/logging/log-buffer-forwarder.js
- common/js/src/logging/log-buffer.js
- common/js/src/messaging/message-channel-pair.js
- common/js/src/messaging/message-channel-pool.js
- common/js/src/messaging/port-message-channel.js
- common/js/src/messaging/single-message-based-channel.js
- common/js/src/messaging/typed-message.js
- common/js/src/nacl-module/nacl-module-messaging-channel.js
- common/js/src/nacl-module/nacl-module.js
- common/js/src/requesting/remote-call-message.js
- common/js/src/requesting/request-receiver.js
- common/js/src/requesting/requester-message.js
- common/js/src/requesting/requester.js
- common/make/js_building_common.mk
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook.js
- third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
- third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
- third_party/pcsc-lite/naclport/js_client/src/api.js
- third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/known-apps-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/readiness-tracker.js
Refactor JavaScript code to specify "@const" for all class attributes
that are never reassigned. Also promote the "jsdocMissingConst" Closure
Compiler diagnostic, which complained about private properties that can
be marked as @const, to be an error.
This is intended to be a non-function change, contributing to the
refactoring effort tracked by #264.
> Add missing @const

- smart_card_connector_app/src/background.js
Add the chrome.app.runtime.onLaunched event listener only in the app
mode. Skip that in the extension mode, since launching is an
app-specific concept, and browser actions are used for extensions
instead.
> Enable launch functionality only in the app mode

- common/make/packaging_common.mk
- example_cpp_smart_card_client_app/build/Makefile
- example_js_smart_card_client_app/build/Makefile
- smart_card_connector_app/build/Makefile
Rename the common/make/app_building_common.mk file to
packaging_common.mk, since we're going to add support for other
packaging modes besides the (legacy) Chrome App.
task #379.
> Rename {app_building => packaging}_common.mk

- smart_card_connector_app/build/Makefile
- smart_card_connector_app/src/create_app_manifest.py
- smart_card_connector_app/src/manifest.json.template
Add the support of conditionals into the Connector's
manifest.json.template, allowing to switch between extension- and
app-specific blocks in this file depending on the PACKAGING build
variable.
Do this by introducing a simple "${if ...} ... ${endif}" syntax into
create_app_manifest.py, with the regexp-based implementation. The
implementation is very basic and, e.g., doesn't support nested
conditions.
task #379.
> app/extension conditions in manifest.json.template

- smart_card_connector_app/src/manifest.json.template
Change the Connector's manifest.json.template to only request the
App-specific permissions in the "app" packaging mode. This allows to
avoid warnings in Chrome when loading the "extension" version.
task #383.
> Differentiate app-/extension-specific permissions

- smart_card_connector_app/src/background-main-window-managing.js
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/window-apps-displaying.js
- smart_card_connector_app/src/window-devices-displaying.js
Make the data passing (connected readers and connected client
applications) between the Connector's background page and the popup
window work in both "app" and "extension" packaging modes.
This is achieved by changing the mechanism for passing data: instead of
manipulating the popup's global variables (in the
chrome.app.window.create() callback - which was obviously an
App-specific mechanism), let the popup read them from the background
page's globals.
task #383.
> Fix data passing from background to popup window

- common/js/src/logging/log-buffer.js
- common/js/src/logging/logging.js
- common/js/src/popup-window/popup-opener.js
This fixes the log collection and exporting functionality in the
"extension" packaging mode of the Smart Card Connector. The goal is to
collect the logs from all windows and pages in the background page, and
also to allow exporting them when the user clicks "Export logs" in the
UI.
Implementation-wise, this is achieved by switching to a different
mechanism for communicating between the background page and other
windows. The old app-specific mechanism worked like this: the background
page holds a log buffer that it injects into every opened window by
setting a global property on it. The new mechanism used in this commit
is the inverse of this: every window calls
chrome.runtime.getBackgroundPage() and grabs the log buffer.
Some additional complexity in this change is caused by the fact that …
> Fix log collection in Connector's extension mode

- common/js/src/messaging/single-message-based-channel-unittest.js
- common/js/src/messaging/single-message-based-channel.js
Fix the issue with incorrect serialization of byte fields when using
single-message-based communication channels. The root cause is that
we did internal migration in the Smart Card Connector app to start using
ArrayBuffers for representing such fields, however due to the
cross-extension messages not supporting them we needed to transform this
into integer arrays before sending this. While #226 did this for
port-based communications, the single-message-based communication left
broken, resulting in some fields, like "atr", being received as "{}"
instead of the array of integer-bytes.
This fixes #393.
> Fix ArrayBuffer bug in single-message-based comm

- common/js/src/logging/logging.js
Skip calling chrome.runtime.getBackgroundPage() when setting up logging
(originally added in #391), so that this code doesn't throw an exception
when this method is unavailable. This should never happen in production
currently, but might happen if the code is running outside an app/extension.
task #390.
> Don't call getBackgroundPage in non-app/extensions

- prepare-binaries-for-github-release.py
Update the prepare-binaries-for-github-release.py script to use the
correct directory name for input artifacts. Since #380, the directory
name has the pattern "$(PACKAGING)_$(TOOLCHAIN)_$(CONFIG)" (e.g.,
"app_pnacl_Release"), meanwhile it used to be just
"$(TOOLCHAIN)_$(CONFIG)".
> Fix GitHub binary preparation script for packaging

- common/js/src/packaging.js
The packaging.js script should import the GoogleSmartCard.Logging
namespace. Closure Compiler doesn't explain about this due to whatever
reason, however it began to produce broken code sometimes, namely code
that throws this exception sometimes:
Uncaught TypeError: Cannot read properties of undefined (reading
'check')
Basically, the code from packaging.js uses code from logging.js, but
somehow Closure Compiler misses that and produces the resulting file
with packaging.js coming before logging.js.
This is a follow-up to #380 where packaging.js was originally
introduced, and contributes to the app-to-extension migration effort,
in particular task #379.
> Fix missing import

- common/js/src/extension-id-unittest.js
- common/js/src/extension-id.js
Add a small helper for checking whether a string is (purely based on its
format) an extension ID.
The plan is to use this helper in follow-ups in order to distinguish
between extension IDs and generic web origins. Specifically, we're
adding the support of receiving smart card commands from web pages,
which means we'll store two kinds of permissions granted by the user:
ones based on Extension IDs and ones based on web origins; when loading
these persisted permissions, we'll need to determine the kind of every
stored item.
> Add helper for checking string being extension ID

- common/js/src/messaging/messaging-origin-unittest.js
- common/js/src/messaging/messaging-origin.js
Introduce a concept of a "messaging origin", which is a unique
identifier of a remote endpoint that sends messages to us. Practically,
it's going to be used for identifying which extension or which website
is sending PC/SC commands to us, that is, to the Smart Card Connector.
An origin is a suitable abstraction that allows to make most of code
agnostic to whether the sender is an extension/app or a web page.
> Add messaging origin helpers

- smart_card_connector_app/src/_locales/en/messages.json
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog.css
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Change the dialog to make it agnostic to whether the client application
is an extension/app or a web page. Also improve the wording.
> Generalize PC/SC permission prompt

- smart_card_connector_app/build/Makefile
- smart_card_connector_app/src/create_app_manifest.py
- smart_card_connector_app/src/manifest.json.template
When building the Smart Card Connector in CONFIG=Debug, automatically
append the "key" property with the real Smart Card Connector's public
key.
This is useful in development and manual testing scenarios, since it
allows to load the just-built application under the production extension
ID ("khpfeaanjngmcnplbdlpegiifgpfgdco").
> Use "mimicking" ID for Connector in Debug builds

- smart_card_connector_app/src/window-apps-displaying.js
- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Switch the JSON config that describes all client applications that are
"trusted" to list origins instead of extension IDs. This change is part
of the general plan to switch to origins, allowing us to support
requests from web pages in the same way as how we supported them from
extensions.
Also rename a few source files and classes to better reflect the new
function: "KnownApp" => "TrustedClientInfo", "KnownAppsRegistry" =>
"TrustedClientsRegistry". We don't rename the JSON config since it'll
break github links in various old docs and conversations.
> Switch known_client_apps.json to origins

- common/js/src/messaging/port-message-channel.js
- smart_card_connector_app/src/background.js
Refactor the class to use a more generic notion of "origins" instead of
"extension IDs".
> Switch PortMessageChannel JS class to origins

- common/js/src/messaging/messaging-origin.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Refactor the class to use a more generic notion of "origins" instead of
"extension IDs".
The important detail here is that we're switching the persistent storage
format: for every client app for which the user clicked "allow" we'll now
store an origin instead of an extension ID. In order to preserve
backwards compatibility and not forget about clients previously
approved by the user, we're performing the migration on-the-flight
when loading the persistent storage.
> Switch UserPromptingChecker JS class to origins

- common/cpp/src/google_smart_card_common/cpp_attributes.h
- common/cpp/src/google_smart_card_common/ipc_emulation.cc
- common/cpp/src/google_smart_card_common/ipc_emulation.h
- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
- third_party/pcsc-lite/naclport/server/src/winscard_msg_nacl.cc
Make methods in the ipc_emulation report errors via return values,
instead of returning them via output arguments or via both. Also delete
global functions-aliases, in favor of callsites directly calling the
singleton's methods. Rename the methods to be more specific about what
they're doing, and drop the word "manager" from the IpcEmulationManager
class name.
This commit contributes to the WebAssembly migration effort, tracked by
issue #233.
> Refactor methods in ipc_emulation

- common/make/internal/executable_building_emscripten.mk
The --bind flag causes an error in recent Emscripten releases when
passed to the compiler. It's a linker-only flag, so change our build
scripts to only pass it to the linker.
This change contributes to the WebAssembly migration effort, tracked
by #177.
> Pass --bind only to the Emscripten linker

- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/ipc_emulation.cc
- common/cpp/src/google_smart_card_common/ipc_emulation.h
- third_party/pcsc-lite/naclport/server/build/Makefile
- third_party/pcsc-lite/naclport/server/src/winscard_msg_nacl.cc
Add a fake implementation of the pipe() function, in order to work
around the Emscripten issue with all pipes being created as
non-blocking - which is a non-standard behavior that was causing crashes
inside the PC/SC-Lite daemon.
Also wire up this fake pipe() implementation, together with
corresponding fake write()/read()/close(), with the third-party code in
hotplug_libusb.c, by redefining the standard names to our own helpers.
This is hacky, but allows to not maintain complex patches that'd need to
be reapplied to the upstream.
This commit contributes to the WebAssembly migration effort, tracked by
issue #233.
> Emulate pipe() IPC function

- common/cpp/src/google_smart_card_common/ipc_emulation_unittest.cc
Add basic unit tests for the IPC emulation functionality: creating a
pair of in-memory files, writing and reading in scenarios where no
blocking should occur.
> Add tests for ipc_emulation

- smart_card_connector_app/build/executable_module/Makefile
- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application.h
- third_party/libusb/webport/build/Makefile
- third_party/libusb/webport/src/public/libusb_web_port_service.cc
- third_party/libusb/webport/src/public/libusb_web_port_service.h
Rename LibusbOverChromeUsbGlobal to LibusbWebPortService. Also move it
from "google_smart_card_libusb/global.{h,cc}" to
"public/libusb_web_port_service.{h,cc}", and change files that include
it to specify full path - for making the code easier to follow.
This is a pure refactoring change. It's preparatory work for the WebUSB
support effort tracked by #429.
> [usb] Rename LibusbOverChromeUsbGlobal

- third_party/libusb/webport/build/Makefile
- third_party/libusb/webport/build/tests/Makefile
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
- third_party/libusb/webport/src/public/libusb_web_port_service.cc
- third_party/libusb/webport/src/public/libusb_web_port_service.h
- third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Rename the LibusbOverChromeUsb class to LibusbJsProxy, to anticipate the
upcoming change to support both chrome.usb and WebUSB APIs.
This is a pure refactoring change. It's preparatory work for the WebUSB
support effort tracked by #429.
> [usb] Rename LibusbOverChromeUsb

- smart_card_connector_app/src/background.js
- third_party/libusb/webport/src/chrome_usb/api_bridge.h
- third_party/libusb/webport/src/chrome_usb/chrome-usb-backend.js
- third_party/libusb/webport/src/libusb-proxy-receiver.js
Add a JavaScript class for handling the Libusb requests sent from the
C++ code. Redirect the C++ code to send requests to this class instead
of the ChromeUsbBackend JS class.
Currently the new JsProxyReceiver class only has a stub implementation
that forwards all requests to ChromeUsbBackend. Follow-up commits will
change it, by introducing an abstraction layer that abstracts away
differences between chrome.usb and WebUSB APIs.
> [usb] Add JsProxyReceiver

- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
- common/cpp/src/google_smart_card_common/requesting/async_request_unittest.cc
- common/cpp/src/google_smart_card_common/requesting/async_requests_storage_unittest.cc
- common/cpp_unit_test_runner/src/build_emscripten.mk
- third_party/googletest/webport/build/Makefile
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Fix the configuration issues that prevented the usage of
multi-threading in unit tests. This required a few "magic" flags to
Emscripten and tweaking the GoogleTest build parameters, but also we had
to wait until Emscripten fixes a few toolchain issues.
This commit also reenables all multi-threading tests to be run on
Emscripten as well, as they were previously NaCl-only. Given that the
Debug mode is 1-2 orders of magntiude slower in Emscripten than the
Release mode, the commit also tweaks the parameters in stress tests.
> [wasm] Fix&enable multi-threading in tests

- common/js/build/Makefile
- example_cpp_smart_card_client_app/build/Makefile
- third_party/libusb/webport/build/Makefile
- third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
Add missing dependencies into the Makefiles, so that tests aren't
attempted to be built before the libraries they're testing. Without
this, there were flaky link errors.
> [build] Tests are built after the main code

- common/make/js_building_common.mk
Explicitly tell the Closure Compiler to make the resulting files to
conform to the JavaScript specification not newer than year 2015,
because our app's minimum_chrome_version is still 48 (released in
2015/2016).
This is an additional safety measure: most likely we aren't using
unsupported constructs anyway, but the explicit flags will make sure of
that.
> [build] Specify output JS language version

- smart_card_connector_app/src/background.js
The Google JavaScript Style Guide requires to always specify brackets
when invoking constructors. Fix a couple of places in our code that
violate that.
This is a pure refactoring commit.
> [style] Call JS constructors with brackets

- third_party/libusb/webport/src/libusb_js_proxy.cc
Don't leak the libusb_device_handle memory when the handle closing
failed. Such failures should never happen under normal circumstances,
but it's still better to avoid such leaks.
> [usb] Fix memory leak on close failure

- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
- third_party/libusb/webport/src/libusb-proxy-data-model.js
- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
- third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Add structures and boilerplate for the device config passing into the
libusb-to-JS adaptor, and provide its implementation for the chrome.usb
API.
> [usb] Get device configs via new JS proxy

- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/libusb_opaque_types.h
Implement opening/closing a device via the new libusb-to-JS adaptor and
its chrome.usb implementation.
> [usb] Open/close devices via new JS proxy

- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
Implement claiming a USB interface via the new libusb-to-JS adaptor and
its chrome.usb implementation.
> [usb] Claim interface via new JS proxy

- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
Implement releasing a USB interface via the new libusb-to-JS adaptor
and its chrome.usb implementation.
> [usb] Release interface via new JS proxy

- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
Implement resetting a USB device via the new libusb-to-JS adaptor and
its chrome.usb implementation.
> [usb] Reset device via new JS proxy

- third_party/libusb/webport/src/libusb-proxy-data-model.js
- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
- third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Add data model and implement the JS side of the USB control transfers in
the new libusb-to-JS adaptor.
The C++ side is not wired up with this new code yet.
> [usb] Add types for control transfer

- third_party/libusb/webport/src/usb_transfer_destination.cc
- third_party/libusb/webport/src/usb_transfer_destination.h
Refactor the UsbTransferDestination struct to stop using the chrome.usb
entities internally, and also to expose factory methods that don't use
chrome.usb entities.
This is a preparation for switching the callsites away from using
chrome.usb. It's preparatory work for the WebUSB support effort tracked
by #429.
> [usb] Decouple USB destination from chrome.usb

- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/libusb_opaque_types.h
Change our libusb_bulk_transfer/libusb_interrupt_transfer implementation -
which perform synchronous transfers - to redirect to our asynchronous
transfer implementation.
Also delete various helpers for sync transfers which became unnecessary
now.
This helps streamlining various USB transfer flows. When migrating to
the new libusb-to-JS adaptor, we'll only need to take care of the
asynchronous code path. It's preparatory work for the WebUSB
support effort tracked by #429.
> [usb] Do sync bulk/interrupt transfers via async

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
The code in TrustedClientsRegistry made an incorrect dereference of
"this" inside a local function. Fix this by changing the function to be
a lambda (a.k.a. "arrow function"), which inherits "this" from the outer
scope.
The bug was introduced in #412. Not sure why it wasn't visible earlier -
probably the recent changes of JS compilation levels made the compiler
produce slightly different code. Also it's unclear why the compiler
didn't emit a warning on this mistake.
> [js] Fix bad "this" in TrustedClientsRegistry

- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_opaque_types.h
- third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Migrate the LibusbJsProxy code to switch away from
chrome_usb::TransferResult to LibusbJsTransferResult.
This is expected to be a pure refactoring change. It's preparatory work
for the WebUSB support effort tracked by #429.
> [usb] Use new libusbjs transfer type

- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
Contrary to the chrome.usb API docs, the transfer result's "data" field
is always provided, even for output transfers - for them it's set to an
empty array buffer. Fix our code to stop being confused by that, since
we were misinterpreting this as a zero-length write, effectively the
failure to do output transfers.
This commit is part of the WebUSB support effort tracked by #429.
> [usb] Fix chrome.usb empty output transfer results

- third_party/libusb/webport/src/libusb-proxy-data-model.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
- third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Add types for the wire format of bulk and interrupt USB transfers in the
libusb-to-JS adaptor, and implement these transfers in the chrome.usb
adaptor.
The C++ side is not wired up with this new code yet.
> [usb] JS base for bulk/interrupt transfers

- third_party/libusb/webport/src/libusb_js_proxy.cc
We need to call libusb_handle_events_completed() in a loop: this
function doesn't promise that the specified transfer (identified by the
"completed" variable) completes, but it only promises to process one
asynchronous event from any transfer in flight.
Before this fix, it could've happened that we returned to the caller
before the transfer actually finishes.
This commit is part of the WebUSB support effort tracked by #429.
> [usb] Fix synchronous transfer event loop

- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/libusb_opaque_types.h
- third_party/libusb/webport/src/usb_transfers_parameters_storage.cc
- third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Add implementation of USB transfer timeouts into the libusb-to-JS
proxy. Two main aspects of this are: (1) waiting for the transfer result
shouldn't exceed the timeout, and (2) data that's read after an input
transfer is timed out should be rerouted to later transfers.
The goal is to stop relying on the JavaScript counterpart to enforce the
timeouts, since, unlike chrome.usb, WebUSB doesn't support timeouts.
Luckily, "2" was already implemented by us in the past (for the
cancellation to work), so implementing timeouts in this commit isn't a
radical change.
> [usb] Implement transfer timeouts in proxy

- common/make/internal/executable_building_emscripten.mk
Use the Closure Compiler to minify the JavaScript files produced by
Emscripten. This reduces the executable_module.js file size by 55% (from
177KB to 80KB), which should make the .crx file be installed faster
and the JS code to be loaded faster.
> [wasm] Minify the Emscripten JS files

- smart_card_connector_app/src/window-devices-displaying.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Improve the heuristic that we use for hiding failed devices from the UI.
The previous one - based on interface numbers - turned out to not work
for some popular devices like YubiKeys, so we ended up displaying two
items for them: a successfully initialized and a failed device, because
it's a composite device for which only the third interface is smart card
related.
The new heuristic is based on display names: if we're trying to show
multiple entries that have the same display name but some are failed and
others succeeded, then the failures are likely spurious.
For posterity, the last time we touched this heuristic was #362.
> [ux] Improve heuristic for spurious USB failures

- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
Finish the migration of the LibusbJsProxy code from the old
ChromeUsbApiBridge by letting the transfer requests be sent through the
new libusb-to-JS proxy.
> [usb] Wire up transfers with libusb-to-JS

- third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Use 64-bit integers for storing bulk/interrupt transfer length. The
length we used before - 16 bits - is only sufficient for control
transfers, and we incorrectly used it for all types of transfers,
causing the length to be clamped due to integer overflow.
> [usb] Fix output transfer length overflow

- common/js/src/executable-module/emscripten-module.js
Fix a corner case that could happen when the Emscripten code fails to
load. We were raising an unnecessary error in that case, which would
slightly pollute logs:
TypeError: Cannot read properties of null (reading 'delete')
at GoogleSmartCard.EmscriptenModule.disposeInternal
The fix is to only call the 'delete' method when the
googleSmartCardModule_ member is already non-null. This will protect
against cases when the load failure occurs before this member is
assigned.
> [wasm] Fix Emscripten load failure handling

- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
All subclasses of the LibusbToJsApiAdaptor JS class should implement all
methods, hence mark it as "@abstract" in order to emit compilation
warnings when this is violated.
Temporarily add empty method implementations into the
LibusbToWebusbAdaptor JS class, in order to silence the warnings until
we finish implementing the class.
This is a pure refactoring change. It's part of the WebUSB support
effort tracked by #429.
> [usb] Mark LibusbToJsApiAdaptor as abstract

- smart_card_connector_app/src/background.js
- third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook-unittest.js
- third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook.js
- third_party/libusb/webport/src/libusb-proxy-hook.js
- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/libusb/webport/src/libusb-to-js-api-adaptor.js
Port ChromeLoginStateHook to the new libusb-to_JS adaptor, so that
Libusb doesn't see any devices when the devices is locked. For this, add
an abstract definition for the hook class and implement the new
loginState hook via it. Thanks to the better libusb-to-JS API and
extensive use of promises, the hook is now implemented in a more
type-check-friendly way.
This commit is part of the WebUSB support effort tracked by #429.
> [usb] Port loginState hook to new adaptor

- smart_card_connector_app/build/Makefile
- smart_card_connector_app/build/js_unittests/.gitignore
- smart_card_connector_app/build/js_unittests/Makefile
- test-all.sh
Add build script boilerplate for compiling and running JavaScript
unit tests from the //smart_card_connector/src/ directory.
Currently there are no JS unit tests there, but they will be added in
follow-up commits.
> Build JS unit tests for the Connector application

- common/cpp/src/google_smart_card_common/numeric_conversions.h
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Add compile-time assertions into some of the C/C++ code that performs
data conversion to/from libusb structs and to/from libusb-to-JS adaptor
structs. This should prevent bugs with accidental data clamping, similar
to #469.
Also make some of the libusb-to-JS structs have a more precise sizing,
as a few fields were violating the checks added by this commit.
This commit is part of the WebUSB implementation effort, tracked
by #429.
> [usb] Compile-time checks for struct field sizes

- smart_card_connector_app/src/manifest.json.template
This commit adds a content_security_policy key into manifest.json file
when the EXTENSION packaging mode is used. This allows the WebAssembly
module to be loaded in that mode, since by default the extension CSP
forbids this.
Note that this is not required in the APP packaging mode, since App's
default CSP is not so strict:
https://source.chromium.org/chromium/chromium/src/+/main:extensions/common/manifest_handlers/csp_info.cc;l=61;drc=1e0c2a218eb71bef788fd87b0e7a4e9e93ecfe1d
> [wasm] Use content security policy in extension

- smart_card_connector_app/build/Makefile
- smart_card_connector_app/src/manifest.json.template
Add cross_origin_embedder_policy and cross_origin_opener_policy
properties into manifest.json, which allow to configure the extension's
Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy
correspondingly.
These settings will be required by new versions of Chrome for extensions
that use WebAssembly with multi-threading. See, for example:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes
Normally these settings are configured via HTTP headers, but inside the
extension this isn't possible. But the Chrome Extensions team added
special manifest entries that allow to achieve the same COOP/COEP
configuration as if it was done via headers:
https://groups.google.com/u/0/a/chromium.org/g/chromium-extensions/c/Auo0HwzsyG0/m/TIpq …
> [wasm] Specify COOP/COEP when using WebAssembly

- common/cpp/src/google_smart_card_common/numeric_conversions.h
Refactor the compile-time assertions in the recently added
AssignWithTypeSizeCheck(). Also add a missing #include.
This is a pure refactoring change - a follow-up to #475.
> [common] Clean up type checks in numeric_conversions.h

- smart_card_connector_app/build/Makefile
- smart_card_connector_app/src/manifest.json.template
Reverts GoogleChromeLabs/chromeos_smart_card_connector#477
As it was discovered, the COOP policy causes multiple issues,
both in App and Extension modes: http://crbug.com/1275140,
http://crbug.com/1275145.
Hence reverting this commit for now, until the discussion on the
linked issues suggests the best path forward.
> Revert "[wasm] Specify COOP/COEP when using WebAssembly"

- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Add implementation of the "getConfigurations" command into the
LibusbToWebusbAdaptor JavaScript class.
Thanks to the previous refactoring work, no other changes are needed in
order to let the CCID driver obtain the device configurations via this
WebUSB integration. However, there's one major deficiency: the
"extra_data" field is not set, because WebUSB doesn't expose this
information; backfilling it will be done in a follow-up change.
> [usb] Implement getConfigurations via WebUSB

- common/js/src/logging/debug-dump-unittest.js
- common/js/src/logging/debug-dump.js
Make the JavaScript DebugDump helpers robust against circular
references in the input data. Achieve this by remembering the set
of already visited objects during the depth-first-search-like
traversal.
Previously, we only had an ad-hoc protection against such issues, by
checking for a few well-known types that typically contain circular
references, like the built-in Document type. Another ad-hoc protection
was catching and suppressing all exceptions thrown during the
traversal in the Release. The current commit doesn't delete these, since
the former makes logs more readable and the latter is a useful safety
belt.
> [common] Fix circular ref handling in JS debugDump

- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Log some WebUSB-related errors at the "fine" level, so that these errors
are surfaced in the Debug mode, but don't flood the application's logs
in production.
> [usb] Add debug-only logging of some WebUSB errors

- common/js/src/logging/debug-dump-unittest.js
- common/js/src/logging/debug-dump.js
Optimize the JavaScript DebugDump helper that deals with ArrayBuffers
and make the output format more compact (use a single "0x" instead of
prepending "0x" before every byte and using the ", " separator).
The previous implementation was doing lots of overhead by passing every
byte through a bunch of type and boundary checks. All of that is
unnecessary, as we know that after the type casting we're dealing with
an array of unsigned single-byte integers.
We don't have any measurements, but the inefficiency of the old version
could actually be user-visible, since we have a lot of log statements
that are calculated even in the Release mode (unlike when using C/C++,
it's not possible to automatically completely skip log message
calculation in JavaScript, even when we know that we're below the …
> [common] Optimize ArrayBuffer debug dumping

- common/js/src/logging/debug-dump-unittest.js
- common/js/src/logging/debug-dump.js
Fix the regression introduced by #481: the dump() function was throwing
this error when called with a boolean:
TypeError: Invalid value used in weak set
The reason is that WeakSet, used by us in order to detect circular
references, doesn't support non-objects. And also that we also never
handle the boolean value explicitly - it was dumped by the fallback JSON
serialization (which might've been a small performance issue itself).
This commit fixes both aspects: it dumps booleans explicitly, but also
adds a safety fallback for non-objects before triggering WeakSet
operations.
> [common] Fix boolean debug dumping in JS

- common/js/src/logging/debug-dump-unittest.js
- common/js/src/logging/debug-dump.js
Improve the debugDump JavaScript helper to produce better formatting for
typed arrays (like Uint8Array) and to produce a non-empty dump for
DataViews.
Dumping a sample DataView: before:
{}
after this commit:
DataView[0x01FF]
Dumping a sample Uint8Array: before:
{"0": 0x01, "1": 0xFF}
after this commit:
Uint8Array[0x01FF]
> [common] Improve debug logging of JS typed arrays

- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Polyfill the missing "extraData" information that's not returned by
WebUSB but is part of the libusb interface and is used by the CCID
driver. Do this by making a special "GET_DESCRIPTOR" control transfer to
the device and parsing the bytes out of it.
For the background, each USB device exposes a hierarchy of descriptors
(basically, metadata to be used by the host): configuration descriptors
==> interface descriptors ==> endpoint descriptors. Additionally there
might be class-/vendor-specific descriptors, like 0x21 is a smart card
reader specific descriptor type, and it contains stuff like whether
there's a PIN support in the reader. Such class-/vendor-specific
descriptors aren't returned by WebUSB currently, but the libusb library
that we're trying to emulate does expose it as field …
> [usb] Fetch extraData manually when using WebUSB

- common/js/src/messaging/message-channel-pool.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Wrap calls of some of listeners into try-catch, so that even when some
of them throw error it doesn't prevent others from being notified and,
more importantly, it doesn't bubble the exception throw the whole stack.
A real example where this helps is when the PC/SC server notifies that
the list of readers changes. This notification triggers the UI update,
which can throw an exception when the UI is already closed (while this
can be addressed separately, it's still an example of something we want
to defend against). If we don't catch the exception, it bubbles back
into the PC/SC-Lite server code, causing the reader initialization to be
aborted.
> [pcsc] Make exceptions in listener not break logic

- common/js/src/logging/debug-dump-unittest.js
- common/js/src/logging/debug-dump.js
Bail out from JavaScript debugDump when the "chrome" global object is
passed.
If some JS code accidentally passes the "chrome" object to the debugDump
function, the function was attempting to recursively dump its properties.
The resulting dump isn't of any use (it'll contain a list of Extensions
API functions), so it'd be a waste of resources, and additionally it'll
trigger console warnings due to accessing deprecated functions. Hence
handle the case of the "chrome" global object explicitly, even if no
code should normally pass it.
> [common] Skip the "chrome" global from dumping

- smart_card_connector_app/src/window-devices-displaying.js
Add implementation for prompting the user to grant a permission in the
configuration when WebUSB is used.
Due to the WebUSB limitations, we can't show the prompt directly after
the button click in the browser action, therefore we're opening a new
tab with the same window, letting the user to click the button again and
select the device. This is a bad UX, but it's a temporary measure until
Chrome is changed to allowlist the Smart Card Connector for accessing
all smart card readers.
> [usb] Device selector dialog in WebUSB

- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Log calls of WebUSB methods. Despite that we're already logging USB
commands at the libusb layer, this commit also adds logging at the place
we're calling into WebUSB, since there's some nontrivial functionality
between these two ends.
> [usb] Log WebUSB calls

- common/js/src/nacl-module/nacl-module.js
Stop trying to modify the Native Client embed's "offsetTop" property,
since it triggers an exception when the code uses "use strict":
TypeError: Cannot set property offsetTop of #<HTMLElement> which has
only a getter
This illegal assignment was silently ignored till #443 that added some
Closure Compiler parameters that specify the input/output language
version. Apparently, these new parameters also lead to the resulting
code containing "use strict", which in turn resulted in this exception
and the breakage when compiled in NaCl mode.
The fix is to write to value to a random other property, because we
don't actually care about the result: we only want an access to the
"offsetTop" property to be not optimized away by Closure Compiler, and
this access is itself a workaround for an old …
> [nacl] Fix illegal offsetTop modification

- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Switch the polyfill that fetches extraData from direct calls to WebUSB
open()/close() methods to using device handles. This allows to make sure
that we don't try to open a device twice (if a concurrent request is
started later), and that we don't close a device that's still in use
(again by some concurrent operation).
Also while doing this, apply a small optimization: don't open-close the
device for each configuration descriptor, but do this once for all
descriptors of a single device.
> [usb] Fetch WebUSB extraData via handles

- common/make/internal/executable_building_emscripten.mk
Reverts GoogleChromeLabs/chromeos_smart_card_connector#435.
Another bug was discovered in Emscripten related to this flag:
https://github.com/emscripten-core/emscripten/issues/15692
Until that issue is resolved, reverting our usage of the flag, so that
the Smart Card Connector works when built in Release mode.
> Revert "[wasm] Minify the Emscripten JS files"

- smart_card_connector_app/src/background.js
Make sure that the Smart Card Connector's background page is never
unloaded, even when the user and other applications don't communicate
with it. This allows to make sure that the Connector is responsive when
requests arrive to it.
This change is only needed for the Emscripten/WebAssembly mode, since
when using NaCl Chrome automatically keeps the page alive.
> [wasm] Keep background page forcibly

- common/make/js_building_common.mk
- smart_card_connector_app/src/manifest.json.template
Bump the Smart Card Connector's requirements be "Chrome >=96".
This is the first version of Chrome that allowlists the Smart Card
Connector to access smart card readers via WebUSB: crbug.com/1233881.
Hence explicitly declare this is a hard dependency, and also adjust the
flags passed to Closure Compiler accordingly, so that it can produce a
more modern JavaScript code without too many polyfills - which is
slightly smaller (-3%), easier to debug and probably slightly faster.
> [connector] Require Chrome >=96 in extension

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
This PR removes the close button "x" in the extension mode since the popup already has a title bar with a close button.
> Remove close button in extension mode

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
This PR undoes an unwanted width change to the permission prompt popup window.
> Undo unwanted change to permission popup width

- common/js/src/messaging/message-channel-pair-unittest.js
- common/js/src/messaging/message-channel-pair.js
Fix a corner case in the MessageChannelPair which could lead to the
"cannot read property of undefined" exception in some error handling
scenarios.
The problem was that if one channel of the pair gets destroyed quickly
after the message is sent to it, by the time it's delivered (which
happens asynchronously) we were trying to find the message handler using
already cleared data members. An example when this can happen is when
the Emscripten module fails to load (repro example: set a breakpoint in
DevTools shortly after we start loading the module, wait a minute after the
breakpoint is hit and then continue), and the exception would be triggered
while trying to deliver a PC/SC command message to the module.
The fix has two parts: first, check the disposal state right before
delivering the …
> [common] Fix error handling in MessageChannelPair

- third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook.js
Downgrade the logging about the lack of the chrome.loginState API from
warning to info - it's a non-fatal error, and it's expected when run on
desktop OSes.
This warning has confused a number of people because chrome://extensions
surfaces all warnings as if they were errors.
> [logging] Lower severity of loginState message

- common/js/src/background-page-unload-preventing/background-page-unload-preventing.js
- smart_card_connector_app/build/Makefile
- smart_card_connector_app/src/background.js
Fix the logic that forcibly keeps the Smart Card Connector'
background page alive. It was enabled in #499, however it turns out it
didn't work correctly for two reasons: first, we didn't copy the
needed .js+.html files into the Connector, and, second, the Connector's
background page gets confused by a messaging port opened by the iframe.
This commit addresses both of the problems, by invoking the necessary
build command in the makefile and by fixing the background page to
ignore the iframe's port. Additionally the commit improves some comments
and downgrades the failure to stay alive from a fatal exception to a
warning (we shouldn't do harakiri just because of the suspend event).
> [wasm] Fix background page keepalive

- common/cpp/src/google_smart_card_common/ipc_emulation.cc
- common/cpp/src/google_smart_card_common/ipc_emulation_unittest.cc
Fix the ipc_emulation library to allow reads/writes to in-memory files
when both the buffer is null and the size is zero. Before this commit,
the library was crashing on these.
The example case in which this could happen is when the Smart Card
Connector is receiving a command, like SCardControl, which has a buffer
parameter equal to an empty array. In that case our C++ handler creates
a zero-sized std::vector, calls data() on it and passes the result to
the C PC/SC-Lite code, which in turn writes this data to an in-memory
file. The C++ Standard allows data() to return nullptr when the size is
zero, hence we were hitting the crash in ipc_emulation.
The fix is to simply quickly exit when the read/write size is zero. We
don't even check the file correctness before doing this - …
> [wasm] Fix crash on zero-size read/write

- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
Explicitly abort the compilation if the used version of Emscripten is
too old. Our env/initialize.sh already installs a reasonably good
version, so this commit adds protection for the case the developer ran
this script a long time ago or is trying to use their own old Emscripten
checkout.
> [wasm] Abort if Emscripten is too old

- common/make/js_building_common.mk
Specify the use_types_for_optimization flag as true to Closure Compiler.
This allows to optimize the resulting file significantly better - at
least the size is decreased by 13%. For the background, originally in
this project we only used "safe" options of Closure Compiler and
disabled all optimizations, but the paradigm shifted and we started to
pay more attention to minimizing and speeding up the resulting program.
> [js] Compile using use_types_for_optimization

- smart_card_connector_app/src/window-devices-displaying.js
This PR fixes readers not being unsubscribed when SCC window is closed in the extension mode.
This is to prevent onReadersChanged() to be called when the UI is closed, since it'll try to update a not-existing-anymore UI controls, causing an exception.
> Unsubscribe reader when extension popup is closed

- env/constants.sh
Uprev the pinned third-party dependency - Emscripten - to 3.1.2.
This update is not strictly required, but Emscripten seems to have fixed a few
bugs and also got updated to use LLVM 13.
> Update Emscripten to 3.1.2

- third_party/closure-library/src/closure/goog/testing/testcase.js
Patch the Closure Library locally in order to fix an error in the unit
test framework when optimizations are on: the framework fails to call
the setUp() and tearDown() methods due to property renaming.
We'll try to upstream the fix separately from this local patch.
> [js] Fix Closure Library jsunit in optimized mode

- common/make/js_building_common.mk
Stop specifying the "--language_out" flag to Closure Compiler, since
its recent versions complain about using it together with the
"--browser_featureset_year" flag. This commit leaves only
"--browser_featureset_year" used in our code.
Also start using the 2020 version of JavaScript (ECMAScript) in
more build configurations, and only stick to the old 2012 version in the
"App+PNaCl" build. Both of Emscripten and WebUSB require a fresh (at
least from 2020) version of Chrome.
> [js] Use JavaScript 2020 in more configs

- common/js/src/container-helpers-unittest.js
- common/js/src/messaging/message-channel-pinging.js
- common/js/src/messaging/port-message-channel-unittest.js
- common/js/src/requesting/requester-unittest.js
- smart_card_connector_app/src/window-apps-displaying.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Fix a few tests to make them work in the advanced optimizations mode of
Closure Compiler. This paves the way for enabling this mode in unit
tests in Release builds - currently tests are built without
optimizations, which puts us under risk of shipping broken code.
The challenge with unit tests is that many mocking tricks are broken
when the compiler renames fields and methods, inlines function calls
and substitutes constants. Hence in this commit we go back to classic
methods like "overrideXForTesting" and class inheritance in a few
places - these approaches are guaranteed to work with any kind of
optimizations.
Other issues fixed in this commit are mostly related to quoting object
properties where needed, in case the test injects or expects data in
particular format.
> [js] Fix unit tests for optimized mode

- common/js/src/popup-window/popup-opener.js
The runModalDialog function in popup-opener doesn't receive
chrome.app.window.CreateWindowOptions anymore - it's WindowOptions since
the recent refactoring performed in #404.
> [js] Fix runModalDialog signature

- common/make/js_building_common.mk
Enable Closure Compiler's aggressive optimizations for unit tests when
building in the Release mode.
This makes sure that the unit tests are running in the same
configuration as the code we ship, making it able for us to catch errors
caused by optimizations (which can happen as the compiler makes some
implicit assumptions about the code) in tests.
> [js] Run release tests with optimizations

- common/js/src/messaging/message-channel-pool.js
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/window-apps-displaying.js
This PR fixes apps not being unsubscribed when SCC window is closed in the extension mode.
This is to prevent onUpdateListener() to be called when the UI is closed, since it'll try to update a not-existing-anymore UI controls, causing an exception.
> Unsubscribe app when extension popup is closed

- third_party/closure-library/src/closure/goog/testing/testcase.js
- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Add a few kiosk apps that use smart card communication. Autoapprove
their permissions (without asking the user), in order to mitigate the
issue with invisible prompts in the kiosk mode when the Smart Card
Connector runs as a secondary app (normally the solution to this
problem is policy-for-extensions, however it doesn't exist for
secondary kiosk apps).
> [allowlist] Autoapprove permission for kiosk apps

- smart_card_connector_app/build/Makefile
Build the human_readable_supported_readers.txt file by default, instead
of requiring the developer to run "make package".
This makes it a bit more convenient for developers, and also it doesn't
slow anything down as the file is cheap to build.
> Automatically rebuild supported readers TXT file

- common/js/src/popup-window/in-popup-main-script.js
- smart_card_connector_app/src/window-about-showing.js
- smart_card_connector_app/src/window-devices-displaying.js
- smart_card_connector_app/src/window-help-showing.js
- smart_card_connector_app/src/window-logs-exporting.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
Fix the UI button listeners (like "About", "Help") to correctly work and
not throw exceptions.
The problem was that the "e.preventDefault()" calls were throwing
errors: apparently Closure Library passes not Event but
goog.events.BrowserEvent objects, and in the Release build the minifier
renames properties and methods of the goog.events.BrowserEvent class.
Hence the incorrect type signature we gave in the code confused the
compiler and didn't let it rename the "preventDefault()" calls into the
minified names.
> Fix UI buttons not reacting

- common/make/common.mk
- env/initialize.sh
- prepare-binaries-for-github-release.py
- smart_card_connector_app/src/create_app_manifest.py
- smart_card_connector_app/src/create_human_readable_supported_readers.py
Switch most of the build scripts to using Python3 instead of simply
calling "python" (and assuming it's Python ±2.7).
What this commit doesn't address is the NaCl builds, since they use the
unmaintained third-party build scripts that still rely on Python 2.
Fixing those will be a separate effort.
> Use Python 3 in build scripts

- third_party/webports/src/src/requirements.txt
Workaround Python 2 errors occurring when initializing NaCl webports, by
requiring two modules ("logilab-common" and "lazy-object-proxy") not go
beyond their last Python2-supporting versions.
This commit is similar to #360. New errors will probably continue to
appear over time, as more and more pip modules drop Python 2
compatibility. The only solution is stopping the usage of NaCl, which
will happen in some mid-term future.
> Pin more Pip2 modules for NaCl webports

- format-code.sh
The repo's main branch is now called "main" - reflect this in the
format-code.sh script.
> Update the main branch name in format-code.sh

- common/js_test_runner/run-js-tests.py
Implement a script that allows running JavaScript tests from the console
and get the results back. This script, once integrated with our
makefiles, will allow to fully automate the test execution, simplifying
developer flows and allowing to run them in Continuous Integration.
> Add script for running JS tests via Selenium

- common/js/src/messaging/single-message-based-channel-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry-unittest.js
Add unit tests for the "ManagedRegistry" class that's reading the
configured policy and exposes the list of admin-force-allowed client
IDs.
This is a preparatory step for fixing the regression #540.
> Add tests for PC/SC client list policy registry

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
Fix the regression introduced in the effort to switch to generic
messaging origins (#377). The regression is that we accidentally
switched the policy syntax from the list of extension IDs to the list of
origins, like "chrome-extension://something". This is a breaking
change for existing customer deployments who use the policy,
because the policy effectively becomes ignored.
This commit brings the backwards compatibility back, so that we still
recognize the policies that mention lists of extension IDs. Using the
new, origin-based, syntax in the policies is allowed too, although
not enforced.
This fixes #540.
> Bring back support of extension IDs in policies

- env/.gitignore
- env/initialize.sh
Fetch a Chromedriver in the env/initialize.sh script. This is a helper
tool that allows the Selenium test framework communicate to Chrome and
control the test pages running in it.
Chromedriver is fetched based on the current Chrome version, according
to the instruction:
https://chromedriver.chromium.org/downloads/version-selection
> Initialize Chromedriver in env

- common/make/internal/executable_building_emscripten.mk
Stop using the Make >=4.3 only functionality in Emscripten build
scripts.
This commit is analogous to #541 - it was an oversight that there's one
more place left that's using the "&:" syntax.
> Drop one more Make 4.3 usage in Emscripten builds

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry-unittest.js
Add tests for the scenarios when unrelated keys are changed in the
chrome.storage.
> More tests for PC/SC client list policy registry

- common/make/internal/executable_building_emscripten.mk
- third_party/googletest/webport/build/Makefile
Fix a possible flakiness in the Googletest makefile, caused by the fact
it attempts to write into LIB_DIR (env/emsdk/lib/{Debug|Release})
without making sure it's already created. So if Googletest builds happen
before other libraries create LIB_DIR, the compilation will fail.
The fix is to add a dependency on the sentinel "dir.stamp" file that
acts as a declaration to create the parent directories. For consistency,
use this approach not only in the Googletest's makefile, but also in
executable_building_emscripten.mk.
> Mkdir the target dir in Googletest makefiles

- common/cpp_unit_test_runner/src/build_emscripten.mk
Stop using the Make >=4.3 only functionality in cpp_unit_test_runner
build scripts in Emscripten mode.
This commit is analogous to #541 and #550.
> Drop one more Make 4.3 usage in unit test runner

- common/make/js_building_common.mk
This commit is the final step in making the JavaScript tests run
via Selenium. In this change we integrate the previously prepared tools
and change the Makefile to run them: the helper Python script that runs
Selenium (that's installed as a Pip module into env/python3_venv),
executes Chromedriver (that's downloaded into env/).
> Run JS tests via Selenium

- third_party/ccid/webport/build/Makefile
- third_party/libusb/webport/build/Makefile
- third_party/pcsc-lite/naclport/cpp_client/build/Makefile
- third_party/pcsc-lite/naclport/server/build/Makefile
Use the "-xc" compiler flag when compiling C (not C++) source files.
This is needed when compiling with recent compiler versions (e.g., Clang
13); previously the compiler was automatically selecting the language
based on the input file's extension.
> Explicitly specify the "C" compilation language

- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
Fix weird compilation errors appearing when using a new Clang and
libstdc++. They are caused by some of PC/SC-Lite headers making
preprocessor definitions that collide with the Standard C++ Library's
symbols.
> Fix preprocessor issue with PC/SC and std headers

- third_party/ccid/webport/build/Makefile
- third_party/libusb/webport/build/Makefile
- third_party/pcsc-lite/naclport/cpp_client/build/Makefile
- third_party/pcsc-lite/naclport/server/build/Makefile
Revert change #555. As it turned out, explicitly specifying the
language isn't needed when using the correct command-line
interface (e.g., "clang" instead of "clang++" for both C and C++
sources).
> Revert "Explicitly specify the "C" compilation language"

- third_party/googletest/webport/build/Makefile
Update Googletest's makefile to support the TOOLCHAIN=coverage mode.
> Support building Googletest for coverage

- common/cpp_unit_test_runner/include.mk
- common/cpp_unit_test_runner/src/build_coverage.mk
Update the common/cpp_unit_test_runner/ build scripts to support the
TOOLCHAIN=coverage mode.
> Support cpp_unit_test_runner for coverage

- .github/workflows/makefile.yml
Pass "-j30" to Make in the Continuous Integration script when building
in the WebAssembly mode, so that the builds finish faster.
This is possible now that we fixed the issue with Make version
incompatibility (where parallel builds could corrupt files due to us
using the "&:" directive on Make <4.3).
> Parallelize WebAssembly builds in CI

- common/make/internal/executable_building_coverage.mk
- third_party/googletest/webport/build/Makefile
Tell Clang to build and link the code in the 32-bit mode in
TOOLCHAIN=coverage builds.
This fixes compilation errors caused by the fact that the "long" type is
the same as "int64_t" in 64-bit builds, which causes some of our
function overloads to become duplicates of each other. Also 32-bit mode
is what NaCl and WebAssembly builds use, hence it's better to use the
same in the coverage builds too.
> Use 32-bit mode in Coverage builds

- smart_card_connector_app/src/create_app_manifest.py
Fix a missing newline character at the end of the stderr log
message printed by create_app_manifest.py.
> Add missing line break in manifest creation log

- third_party/googletest/webport/build/.gitignore
- third_party/googletest/webport/build/Makefile
Fix the inconvenient behavior that Googletest would be fully recompiled
every time the developer switches between modes (e.g., when compiling in
CONFIG=Debug, then in CONFIG=Release, and the going back to
CONFIG=Debug, we were starting the whole rebuild from scratch). This
issue was caused by the fact that we reused the same temporary build
directory for all toolchains and configs. When switching configs, the
old temporary directory was overwritten, making Make think the installed
libraries are out-of-date too.
The commit fixes this by using a dedicated directory name, like
"our-artifacts-emscripten-Debug".
> Avoid useless rebuilds of Googletest

- .github/workflows/makefile.yml
- common/make/js_building_common.mk
Append the execution of tests (both C++ and JavaScript) into the
Continuous Integration script.
This is possible now that the test execution is fully automated.
Note that we don't run tests in the NaCl mode yet: these still
require manual intervention at the moment, and automating these
will be done as a separate effort.
> Run tests in CI

- common/cpp/src/empty_main.cc
- example_cpp_smart_card_client_app/build/executable_module/Makefile
- smart_card_connector_app/build/executable_module/Makefile
Normal builds (WebAssembly/Emscripten) don't need a main() function,
because the framework takes care of the startup itself. In the coverage
builds, however, we're building using stock Clang, and it fails the
linking stage if there's no main() provided.
Note that the empty main() is just fine for coverage builds, since all
we care about is building an executable that the LLVM instrumentation
can see. All we want from it in these binaries is to account for all
functions that were present in corresponding object files (in order
to get a realistic coverage of the whole codebase, not only of the
files with unit tests).
> Stub out main() in Coverage builds

- .github/workflows/makefile.yml
Extend the Continuous Integration script to install the dependencies
needed for building in the TOOLCHAIN=coverage mode.
We also need to do "apt-get update" in the beginning, since by default
Github Actions VMs come with outdated Apt state (and installing some
packages will result in 404 errors).
> Install coverage deps in CI

- coverage-report.sh
Add a script "coverage-report.sh" that builds the code in the
TOOLCHAIN=coverage mode, merges the collected raw profiles (*.profraw),
and creates the resulting coverage report.
> Script for creating a coverage report

- common/make/internal/executable_building_coverage.mk
The "fcoverage-mapping", "fprofile-instr-generate" flags should be
passed not only to the Clang compiler, but also to the linker too.
Otherwise, no coverage reports are collected, even though the
code is compiled with an instrumentation.
> Pass coverage flags to Clang linker too

- clean-all.sh
Extend the clean-all.sh script to also clean the coverage artifacts
(only relevant to developers who previously built with
TOOLCHAIN=coverage locally).
> Clean coverage artifacts in clean-all.sh

- make-all.sh
Now that we don't build .crx files by default in makefiles, change the
make-all.sh script to also stop copying them into the
"built_app_packages" directory.
Presumably, these .crx files became mostly useless, because all
development flows are much easier when done via .zip files. Hence
there's very little value in putting the .crx files in the
"built_app_packages" directory.
> Stop copying .crx files in make-all.sh

- common/make/internal/executable_building_coverage.mk
Enable Clang's Address Sanitizer in TOOLCHAIN=coverage builds.
ASan is not strictly related to coverage, however it's useful to have
unit tests run under it as another way to assess correctness of our
code. (Meanwhile Emscripten nominally supports ASan too, and that'd in
theory give us even better assessment of code in real-world scenarios,
in practice Emscripten's ASan breaks with many mysterious errors. Stock
Clang's ASan is much more stable and predictable in that regard,
even though we're limited to unit tests with it.)
> Enable ASan in coverage builds

- Makefile
- common/make/packaging_common.mk
- make-all.sh
Change the build scripts to automatically pack the built Smart Card
Connector and the C++ Example App into .zip files. This commit removes
the need in doing this as a separate extra "make package" step.
As a bonus, we resolve the TODO about copying .zip files from
Emscripten builds.
> Build .zip packages by default

- docs/updating-ccid.md
Remove the mention of special build steps in order to generate
human_readable_supported_readers.txt from the docs.
Since #529, this file is always generated automatically.
> Drop doc on manual generation of supported readers

- .github/workflows/makefile.yml
- common/make/packaging_common.mk
Extend the Continuous Integration script to upload all built .zip
packages (for the applications built in various build modes) as build
artifacts. This makes it possible for developers to obtain the .zips
from a reliable and consistent environment (Github Actions VMs),
rather than to rely on themselves to compile the code correctly locally.
Additionally flatten the contents of the "built_app_packages" directory
(removing the "Debug"/"Release" subfolders), so that the upload step can
just take individual files from it and upload them as separate
artifacts. Also include the packaging mode ("app"/"extension") into the
.zip name, to avoid any potential confusion.
> Upload built app .zips in CI

- .github/workflows/makefile.yml
Fix the Continuous Integration script to not swallow errors from the
"coverage-report.sh" script.
If this script failed, we were ignoring this and proceeding to
subsequent steps of the CI script, eventually posting a misleading "All
tests passed" comment on the Pull Request. The reason was that the
coverage step was encoded as a multi-line text, which GitHub interprets
as separate Bash commands, so that only the last command determines the
overall step's exit code. The fix is to use the folded-style YAML text
(">") and add "&&" between commands, so that any failure is bubbled up.
> Don't discard coverage failures in CI

- common/cpp/src/google_smart_card_common/ipc_emulation.cc
- common/cpp/src/google_smart_card_common/ipc_emulation.h
- common/cpp/src/google_smart_card_common/ipc_emulation_unittest.cc
- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.cc
- third_party/pcsc-lite/naclport/server/src/google_smart_card_pcsc_lite_server/global.h
- third_party/pcsc-lite/naclport/server/src/server_sockets_manager.cc
- third_party/pcsc-lite/naclport/server/src/server_sockets_manager.h
For unit testing purposes, the model "create singletons+threads and
never shut them down" that we're using for the production code isn't
suitable. This commit implements the proper teardown for a few classes
in //common/ and //third_party/pcsc-lite/.
> Implement graceful teardown of PC/SC's classes

- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application.h
- third_party/pcsc-lite/naclport/server/build/Makefile
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.h
- third_party/pcsc-lite/naclport/server/src/readerfactory_nacl.cc
This is a pure refactoring commit. The "global.{h,cc}" was a poor naming
scheme for the file and the corresponding class, so rename them to
"pcsc_lite_server_web_port_service.{h,cc}". Also rename their folder
from "google_smart_card_pcsc_lite_server" to just "public", which
reflects that these .h files can be included by code from other
subtrees.
Also while editing #include's pointing to it switch to using full
include paths like "third_party/pcsc-lite/etc.". This is a better and a
more maintainable naming scheme.
The new naming/inclusion scheme is inspired by Chromium's code
base.
> Rename global to pcsc_lite_server_web_port_service

- common/cpp_unit_test_runner/src/build_coverage.mk
Make sure the coverage profile path is set to an absolute path, so that
even if the unit test decides to change the working directory the
.profraw file is still created in the old place.
> Don't lose coverage profiles if test does chdir

- .github/workflows/makefile.yml
Enable Continuous Integration for all Pull Requests regardless of their
base branch.
Previously, we used to enable it only for the PRs into the "main"
branch, which precluded using CI for chains of PRs.
> Run CI on all PRs regardless of the base branch

- common/cpp/src/google_smart_card_common/value.cc
- common/cpp/src/google_smart_card_common/value.h
- common/cpp/src/google_smart_card_common/value_unittest.cc
Implement comparison operation for the C++ Value class. To avoid any
confusion (e.g., "is floating-point 123.0 same as integer 123?") the
operation is defined as a regular method, rather than an overloaded
operator.
This new operation will be used by follow-up changes for implementing
new unit tests.
> Add Value::StrictlyEquals()

- third_party/ccid/webport/build/Makefile
- third_party/pcsc-lite/naclport/server/build/Makefile
Change the PCSCLITE_HP_DROPDIR constant to specify a relative file path
(without a leading slash).
This is needed in order to be able to run the PC/SC-Lite code in unit
tests, where, unlike running without a Chrome Extension/App, we can't
create a virtual file system with this folder in root. We also don't
want to conditionally change this constant depending on test/non-test
environment, hence using this trick with a relative file path.
> Use relative path to PC/SC-Lite config files

- common/cpp/src/google_smart_card_common/value_unittest.cc
Cover the case of a boolean Value object with unit tests. It was an
oversight as all other Value types were already tested.
> Add unit tests for a boolean Value

- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Add unit tests for LibusbDeviceReset() method of LibusbJsProxy. For
this, we also resurrect a helper test class that prepares an environment
with a single connected fake device.
> Add tests for libusb device resetting

- common/cpp/src/google_smart_card_common/value_conversion.cc
- common/cpp/src/google_smart_card_common/value_conversion.h
Do a small refactoring in the "value_conversion" component: name the
fields as "error_encountered" instead of "succeeded", as it better
reflects this field refers to all conversion steps.
> Rename value conversion field to error_encountered

- .github/actions/build-dependencies-installation/action.yml
- env/initialize.sh
Further optimize the Continuous Integration jobs to skip installing
irrelevant build dependencies in the env/initialize.sh script. For
example, Emscripten installation is not needed when building for
Coverage.
> Install toolchain-specific deps in CI

- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Add unit tests for LibusbControlTransfer() method of LibusbJsProxy,
which performs synchronous control transfers to/from USB devices.
> Add tests for libusb control transfers

- Makefile
- coverage-report.sh
- smart_card_connector_app/build/Makefile
- smart_card_connector_app/build/executable_module/Makefile
- smart_card_connector_app/build/executable_module/cpp_unittests/.gitignore
- smart_card_connector_app/build/executable_module/cpp_unittests/Makefile
- smart_card_connector_app/src/application_unittest.cc
Add build infra boilerplate for building C++ unit tests in the
smart_card_connector_app/ folder. The tests themselves will be
implemented in follow-up changes.
We'll use this test location for half-integration tests that start the
PC/SC-Lite daemon with fake USB devices and exercise PC/SC commands.
> Boilerplate C++ tests in smart_card_connector_app/

- .github/workflows/makefile.yml
Build and test code in Debug and Release modes in Continuous
Integration, as opposed to only using the Release mode (the
default).
That way, we make sure all unit tests pass with tighter
debug-only assertions, and also that no PR breaks the
Debug-only build mode.
Note that we don't cause a slowdown of CI, because
GitHub will spawn separate workers (VMs) for these
new jobs and run them concurrently.
> Build in both Debug and Release modes in CI

- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application.h
- smart_card_connector_app/src/entry_point_emscripten.cc
- smart_card_connector_app/src/entry_point_nacl.cc
Implement a way to shut down the smart_card_connector_app's Application
object without leaking any memory.
This won't be used in production code, as the Smart Card Connector
app/extension never shuts down (and even if some flow triggers the
executable module graceful shutdown, we intentionally leak the objects
to avoid shutdown crashes in background threads). But this proper
shutdown will be used in unit tests of the Application class.
> Implement proper shutdown for Application class

- Makefile
Googletest is needed to be built before building Smart Card Connector's
C++ unit tests (in build configurations in which we have to build
Googletest ourselves: emscripten and coverage).
This commit guarantees this is the case, preventing a potential build
flakiness.
> Fix build ordering for Connector unittests

- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Resurrect a stress-test for LibusbJsProxy that runs hundreds of control
transfers concurrently in multiple threads - we used to have bugs
related to dispatching transfer results under load.
As part of the change, we also make TestingGlobalContext thread-safe,
so that it correctly handles C++-to-JS messages sent concurrently.
> Resurrect libusb control transfer stress-test

- third_party/pcsc-lite/naclport/server/src/config.h
Work around warnings from compiling original PC/SC-Lite sources:
warning: implicit declaration of function 'asprintf' is invalid in C99
The reason they appeared in our builds (but not in upstream) is that
asprintf is a GNU extension. In order to have it declared, one has to
define "_GNU_SOURCE" before including any standard library headers. The
original PC/SC-Lite code satisfies this, but our webport violated it by
adding includes into our version of config.h that's included before
the "#define _GNU_SOURCE" line in hotplug_libusb.c.
The fix is to simply replicate "#define _GNU_SOURCE" at the top of our
config.h file.
> Fix warnings on asprintf calls in PC/SC-Lite

- common/cpp/src/google_smart_card_common/requesting/requester_message.cc
- common/cpp/src/google_smart_card_common/requesting/requester_message.h
- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
- smart_card_connector_app/src/application_unittest.cc
Add a smoke unit test that starts the smart_card_connector_app's
Application object, and checks it successfully completes the
background initialization.
Note that the test is still half-complete because the started
PC/SC-Lite daemon is unable to find the config files. A follow-up
change will fix that later.
> Smoke test for Connector Application

- common/make/internal/executable_building_coverage.mk
Pass the "fno-omit-frame-pointer", "fno-optimize-sibling-calls" flags to
Clang when building in the "coverage" mode. These flags are recommended
by the ASan docs in order to enhance stack trace quality.
> Better stack trace quality in ASan

- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
Update TestingGlobalContext::IsMainEventLoopThread() to closer match the
real-world implementation: it should always return false if called from
a background thread.
This allows us to write multi-threaded tests without silencing their
assertions of kind "this code must never be called on main thread".
> No eventloop in bg threads in TestingGlobalContext

- common/cpp_unit_test_runner/src/build_coverage.mk
Run the unit tests in the "out" directory when using
TOOLCHAIN=coverage.
This allows to implement unit tests that read resource files in the same
way regardless of the toolchain: using relateive file paths
(./executable-module-filesystem/...).
> Chdir for unit tests in coverage mode

- third_party/pcsc-lite/naclport/server/build/Makefile
Update one more global file path to a relative file path: the
FAKE_PCSC_NACL_SOCKET_FILE_NAME constant that point to the
"fake_socket_file" (for the background, the only purpose of this file is
to mimick the presence of the Unix socket file that PC/SC-Lite normally
uses for IPC; we mock out the actual IPC, but the file presence checks
can't be mocked out without patching the PC/SC-Lite sources).
Using relative paths allows to run the same code in unit tests in
"coverage" mode, which doesn't have a virtual file system for exposing
files under absolute paths in "/".
> Use relative path for fake_socket_file

- third_party/pcsc-lite/patches/0001-memory-leak-sReadersContexts.patch
- third_party/pcsc-lite/patches/0002-memory-leak-libusb-device-list.patch
- third_party/pcsc-lite/patches/0003-double-free-CFBundleName-on-shutdown.patch
- third_party/pcsc-lite/patches/0004-reset-ara-kiri-hot-plug-flag.patch
- third_party/pcsc-lite/patches/0005-memory-leak-reader-ful-name.patch
- third_party/pcsc-lite/src/src/hotplug_libusb.c
- third_party/pcsc-lite/src/src/readerfactory.c
Pull several fixes that we committed into the upstream PC/SC-Lite
project. These make it possible to have unit tests that exercise the
PC/SC-Lite daemon code without leaking or corrupting memory and without
one test affecting the results of subsequent ones.
We also commit the .patch files in order to track the changes we're
doing with original 1.9.7 sources locally. The .patch files can be
deleted after the upstream releases a new version and we import it.
> Backport PC/SC-Lite upstream shutdown fixes

- common/cpp/src/google_smart_card_common/nacl_io_utils.cc
- common/cpp/src/google_smart_card_common/nacl_io_utils.h
- smart_card_connector_app/src/entry_point_nacl.cc
Split the initialization of Native Client's nacl_io library into two
parts: one that initializes the library itself and another that uses it
for mounting folders.
The second part will be used by follow-up changes for executing it in
unit tests (they already have nacl_io initialized by the "ppapi_simple"
framework, and attempting to initialize it twice would cause a crash).
> Refactor nacl_io initialization

- common/make/internal/executable_building_nacl.mk
- smart_card_connector_app/build/executable_module/Makefile
Make nacl_io manifest be created in NaCl builds by default, and not only
for the //smart_card_connector_app/ builds. This will allow a follow-up
change to enable the resource files in unit tests.
In order to access resource files through a virtual file system under
NaCl, one needs a nacl_io manifest file (basically, a text file that
contains a list of present file names and their sizes).
> Always produce nacl_io manifest in NaCl builds

- common/make/executable_building.mk
- common/make/internal/executable_building_coverage.mk
- common/make/internal/executable_building_emscripten.mk
- common/make/internal/executable_building_nacl.mk
- smart_card_connector_app/build/executable_module/Makefile
Add a common makefile macro for adding a static resource file into the
resulting executable module file system. The macro has different
implementations depending on the toolchain (e.g., for Emscripten we
tell linker to "preload" the files into a .data archive, and for
Coverage we just copy the file).
The benefit is simplifying the smart_card_connector_app's Makefile by
removing toolchain-specific details from it. Additionally, it allows us
to add resource files to unit test binaries without much hassle (it'll
be done in a follow-up change).
> Refactor resource file packaging build rules

- common/cpp_unit_test_runner/src/build_emscripten.mk
- common/make/executable_building.mk
- common/make/internal/executable_building_coverage.mk
- common/make/internal/executable_building_emscripten.mk
- common/make/internal/executable_building_nacl.mk
- smart_card_connector_app/build/executable_module/Makefile
Run the unit tests in the "out" directory when using
TOOLCHAIN=emscripten, so that the .data file (containing preloaded
resource files needed at runtime) can be loaded without specifying any
path.
This change is analogous to #624, which did the same for coverage
builds.
> Chdir for unit tests in emscripten mode

- common/cpp_unit_test_runner/src/build_emscripten.mk
- common/make/executable_building.mk
- common/make/internal/executable_building_coverage.mk
- common/make/internal/executable_building_emscripten.mk
- common/make/internal/executable_building_nacl.mk
- smart_card_connector_app/build/executable_module/Makefile
- smart_card_connector_app/build/executable_module/cpp_unittests/Makefile
- smart_card_connector_app/src/application_unittest.cc
Add an extended version of the smoke test for the Smart Card Connector,
which additionally exercises the code for establishing and releasing an
SCARDCONTEXT. We use direct C function calls in this test, as we don't
aim to test the JS-to-C++ pipe for PC/SC commands here.
> Unit test for establishing SCardContext internally

- common/cpp/src/google_smart_card_common/value.cc
- common/cpp/src/google_smart_card_common/value.h
- common/cpp/src/google_smart_card_common/value_conversion.h
- common/cpp/src/google_smart_card_common/value_conversion_unittest.cc
- common/cpp/src/google_smart_card_common/value_debug_dumping_unittest.cc
- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion.cc
- common/cpp/src/google_smart_card_common/value_emscripten_val_conversion_unittest.cc
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion.cc
- common/cpp/src/google_smart_card_common/value_nacl_pp_var_conversion_unittest.cc
- common/cpp/src/public/value_builder.cc
- common/cpp/src/public/value_builder.h
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
Add more convenient constructors for array/dictionary values that accept
Value instances by value, instead of having them wrapped into
unique_ptr.
> Refactor Value constructors to use less unique_ptr

- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
Increase the sleep timeout in the PC/SC-Lite shutdown code that we
copied from upstream. This should make it much less likely that we exit
the shutdown function before the background "hotplug_libusb" thread
actually finishes, which was causing flakiness with some probability.
A proper fix will need to be found later.
> Workaround PC/SC-Lite shutdown timing issues

- .github/workflows/makefile.yml
Set Bash' pipefail option in order to preserve the coverage script's
original error code despite piping it like "| tee".
Without this, the tool's exit code is effectively ignored and the job
succeeds regardless of that.
> Don't swallow error in coverage CI job pipe

- .github/workflows/makefile.yml
Change the Continuous Integration config to disable the "fail-fast"
default behavior. It's useful to see the results from all configurations
even if one failed (especially because Release builds usually fail
faster but leave less useful logs than Debug ones).
> Don't skip CI jobs if some failed

- common/cpp/src/google_smart_card_common/logging/logging.cc
Crash immediatelywhen some assertion fails, instead of sleeping
for 1 second, in TOOLCHAIN=coverage builds. This makes it much
simpler to investigate test failures.
We continue to use sleeping in WebAssembly/NaCl builds, because there it
increases the chances that logs of the event that led to the crash reach
the JavaScript side.
> Don't sleep before abort() in coverage builds

- third_party/libusb/webport/src/libusb_js_proxy_data_model.h
Use "enum class" in all Libusb-JS types instead of the old unsafe enums.
It was an oversight to use the old enums for two types.
> Use enum class for Libusb-JS types

- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
Implement fake USB simulation of an arbitrary smart card reader (we took
Gemalto), and write a test that verifies PC/SC-Lite successfully
initializes it and returns via SCardListReaders.
> Emulate Gemalto reader in unit tests

- coverage-report.sh
Fix coverage-report.sh to actually insert "-object" flags between paths
to analyzed binaries.
Before this fix, we were passing all binaries separated by a space (the
code in coverage-report.sh was wrong and actually a no-op), for which
llvm-cov doens't complain, however produces incorrect (lower) coverage.
> Fix coverage flag passing

- coverage-report.sh
Fix an extra space passed after -ignore-filename-regex that led llvm-cov
to misinterpret the path as a path to binary.
> Fix coverage ignored paths

- smart_card_connector_app/src/testing_smart_card_simulation.cc
Populate all fields in the unit-test fake Gemalto device description
(version, names, serials).
While it's not strictly required for making the test fully functional,
it's useful to keep the test closer to real-world devices.
> Emulate full description of Gemalto device

- .github/workflows/makefile.yml
Schedule an additional invocation of Continuous Integration every day at
midnight. The first goal is to increase chances of catching test
flakiness in the landed code. The second goal is to detect any
regressions in the CI script (e.g., due to GitHub's Ubuntu uprev) before
the next person will upload a PR.
> Run CI in background once a day

- smart_card_connector_app/src/application_unittest.cc
Let request IDs be automatically generated from the counter instead of
hardcoding them in the test statements. Not only this makes the tests
less verbose, but it also allows to prevent potential ID conflicts
between different test helpers.
> Autogenerate request IDs in Connector unit tests

- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/logging/logging_unittest.cc
Add unit test coverage for debug assertion and "notreached" macros from
//common logging.h.
The tests are implemented using GTest "death" tests, which makes them
actually running in TOOLCHAIN=coverage builds and no-op in other builds.
> Unit-test C++ logging assertions

- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Resurrect unit tests for LibusbJsProxy asynchronous input control transfers:
basic successful scenario and cancellation.
> Resurrect async input control transfer tests

- common/cpp/src/google_smart_card_common/logging/logging.cc
- common/cpp/src/google_smart_card_common/logging/logging.h
- smart_card_connector_app/src/testing_smart_card_simulation.cc
Make the Smart Card Connector C++ unit tests assert when seeing an
unexpected USB request, instead of replying with an USB error.
This simplifies investigating test failures and development of new ones,
since our goal is to be prepared for everything that PC/SC&CCID can send
in tests, and when there's some gap it's hard to understand which USB
transfer was the culprit.
> Assert on unexpected USB transfers in unit tests

- smart_card_connector_app/src/application_unittest.cc
Add unit tests for SCardGetStatusChange calls arriving from JavaScript
for basic scenarios with a single reader and no card.
> Unit-test GetStatusChange client request w/o card

- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
Add the most basic simulation of an arbitrary smart card (Cosmo ID 7.0
currently) into the Smart Card Connector unit tests. All we simulate at
the moment is the presence of the card and its ATR (answer-to-reset).
> Simulate Cosmo ID 7.0 card presence in unit tests

- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
Add a unit test for a SCardConnect call arriving from JavaScript in the
scenario with a reader and a card inserted into it. We simulate the
protocol negotiation that selects the T1 protocol in this case.
> Unit-test Connect with a fake card via protocol T1

- common/make/packaging_common.mk
Don't create useless subdirs in built_app_packages. It's a remnant of
the old build script that was putting .zip files into subdirs called
like "emscripten-Debug", but since #584 we don't do that anymore.
> Stop creating subdirs in built_app_packages

- common/cpp/src/google_smart_card_common/requesting/remote_call_adaptor.cc
- common/cpp/src/google_smart_card_common/requesting/remote_call_adaptor.h
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
Delete a few unused C++ functions from RemoteCallAdaptor and
ClientsManager. These were found via coverage reports.
> Delete unused code

- common/make/internal/executable_building_emscripten.mk
Enable link-time optimizations when building for WebAssembly via
Emscripten.
Despite that this causes the 5% increase of the resulting binary size,
we're presumably winning on performance. And the 5% size regression is
negligible at our sizes at the order-of-several-hundreds-KBs (especially
given that PNaCl binaries used to be typically about 100% bigger).
> Use LTO in Emscripten builds

- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
Add unit tests for the SCardGetStatusChange calls arriving from
JavaScript in case a card gets dynamically inserted into a reader.
> Unit-test GetStatusChange with card insertion

- common/cpp/src/google_smart_card_common/messaging/typed_message_router_unittest.cc
Add missing test coverage for the scenario when a TypedMessageRouter
receives a message with a wrong format (not a dictionary with fields
"type" and "data").
> Unit-test malformed messages in MessageRouter

- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Extend the LibusbJsProxy unit tests to check there's no issue caused by
an input USB transfer reply received from the JS side after the
transfer got already canceled.
> Unit-test USB reply for already-canceled transfer

- common/cpp/src/google_smart_card_common/optional_test_utils.h
- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
Add unit test for the Smart Card Connector for the scenario in which it
receives a PC/SC request with an unknown function name.
This change includes the refactoring that was needed in order to
properly parse failure response messages (previously the tests were
parsing both requests and response messages in the same way, assuming
that the "payload" field is always present).
> Unit-test Connector unknown PC/SC function call

- smart_card_connector_app/src/application_unittest.cc
Add unit tests for the Smart Card Connector receiving two SCardConnect
client requests with different protocols. The test verifies the second
call only succeeds if SCardDisconnect with SCARD_RESET_CARD is called
in between.
> Unit-test Connect with card protocol mismatch

- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion.cc
- common/cpp/src/google_smart_card_common/requesting/remote_call_arguments_conversion.h
Move some of the code from remote_call_arguments_conversion.h from .h to
.cc. This code was part of template functions which made it being
repeated many times in the resulting object files, which leads to binary
size bloat (at least on NaCl toolchain that we still use in production)
and to reduced code coverage metrics (for debug assertion messages).
> Avoid binary code bloat in remote_call_arguments

- third_party/libusb/webport/src/libusb_tracing_wrapper.cc
- third_party/libusb/webport/src/libusb_tracing_wrapper.h
Fix LibusbTracingWrapper hitting use-after-free errors when canceling an
already completed (but not destroyed yet) transfer.
The problem was caused by leaving a dangling pointer to the wrapped
transfer in the LibusbTracingWrapper. Before this fix, we were cleaning
the dangling pointer when LibusbFreeTransfer is called, but that left a
time window during which the dangling pointer is still here and can lead
to use-after-free: after the transfer is completed but before it's
freed.
This bugfix contributes to the bugfixes tracked by #685. The
regression unit test is part of #684.
> Fix USB tracing wrapper: cancel completed transfer

- third_party/libusb/webport/src/libusb_tracing_wrapper.cc
Fix the LibusbTracingWrapper class to not crash on a debug assertion
when a cancellation of a not-yet-submitted transfer is requested.
The callsites shouldn't normally trigger such calls, but apparently the
original Libusb interface does support them, and we also support that in
the real LibusbJsProxy implementation.
This bugfix contributes to the bugfixes tracked by #685. The
regression unit test is part of #684.
> Fix USB tracing wrapper on unsent transfer cancel

- third_party/pcsc-lite/patches/0001-Fix-SCardReleaseContext-failure-on-orphan-handles.patch
- third_party/pcsc-lite/patches/0002-Fix-SCardDisconnect-on-orphan-handle.patch
- third_party/pcsc-lite/patches/0003-Improve-SCardReleaseContext-fix.patch
- third_party/pcsc-lite/patches/0004-Improve-SCardDisconnect-fix.patch
- third_party/pcsc-lite/src/src/winscard.c
- third_party/pcsc-lite/src/src/winscard_svc.c
Cherry-pick the fixes that I and the upstream maintainers made in
PC/SC-Lite in order to fix spurious SCardDisconnect() and
SCardReleaseContext() errors when a reader is unplugged (as described
at #681).
> Pull upstream PC/SC-Lite fixes for orphan handles

- example_cpp_smart_card_client_app/src/background.js
- example_cpp_smart_card_client_app/src/window.js
Add missing quotes for dictionary keys in the
example_cpp_smart_card_client_app code.
They were forgotten when we changed the build scripts to enable advanced
optimizations in Closure Compiler. The advanced optimizations allow the
compiler to shorten dictionary keys in situations when it thinks the
rename is safe (and the compiler doesn't know how to look into usages in
JavaScript code that runs in other pages or in C++ code).
> Fix Release-mode JS string bugs in example_cpp app

- smart_card_connector_app/src/application_unittest.cc
Add a regression unit test for the PC/SC-Lite bugs when it failed to
close the handle and release the context after the reader got unplugged
(see #681).
> Unit-test Disconnect&ReleaseContext after unplug

- third_party/pcsc-lite/naclport/js_client/src/context.js
Make sure the addOnDisposeCallback() method is exposed as unminifed
method name on the GoogleSmartCard.PcscLiteClient.Context class.
That way, it can be used by unminifed code, which is one scenario that
we support: the example_js_standalone_client_library that we distribute,
built in Release mode. The regression probably happened in #420, when
we enabled aggressive optimizations in Closure Compiler.
> Fix JS minification bug in PC/SC Context JS class

- common/js/src/logging/debug-dump.js
- common/js/src/logging/logging.js
- common/js/src/random.js
Fix the common JS library to stop triggering exceptions when running in
a Service Worker environment. The main difference is that DOM-related
types (like Node) and objects (like |document|) are absent.
Specifically, we fix these places:
* The logging code that used to take the log origin from
|document.location.href| (under Service Workers it should be
|self.location.href|);
* The debug dumping code that should check for type presence before
using any DOM-related type;
* The random generation helper that used to access WebCrypto via
|window.crypto| (under Service Workers it should be |self.crypto|).
This should fix the main blockers for #696.
> Fix //common/js/ for Service Workers

- example_js_standalone_smart_card_client_library/Makefile
- example_js_standalone_smart_card_client_library/README.rst
- example_js_standalone_smart_card_client_library/src/es-module-exports.js
- prepare-binaries-for-github-release.py
Change //example_js_standalone_smart_card_client_library/ to produce a
new flavor of the library: an ES module that can be import'ed in other
code.
This new flavor provides the same functionality as before, but can be
loaded in environments in which ES modules are preferred (e.g., Chrome
Manifest V3 Extension Service Workers).
This resolves the main blocker for #700.
> Support building standalone JS lib as ES module

- third_party/pcsc-lite/naclport/server_clients_management/src/client_handles_registry.h
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.h
Remove SCARDCONTEXT/SCARDHANDLE from internal tracking lists when
the PC/SC-Lite core responds with SCARD_E_INVALID_HANDLE.
This shouldn't happen normally, but we already hit bugs in the
PC/SC-Lite that lead to this in the past. In general, we should follow
what the PC/SC-Lite core tells us, and when our data structures diverge
we should fix our structure to follow the PC/SC-Lite's state.
This commit acts as another layer of defence against issues described
in #681.
> Gracefully handle unexpected revoked PC/SC handles

- common/cpp_unit_test_runner/src/build_analysis.mk
Let developers quickly run particular C++ test(s) by specifying a
GTest filter in the command line:
GTEST_ARGS="--gtest_filter=*Foo" make test
This is particularly useful now that we have expensive tests in
application_unittest that take a couple of minutes to run.
We only support this for C++ tests and only in analysis builds
(TOOLCHAIN=coverage/TOOLCHAIN=asan_testing), since passing command-line
parameters is not trivial in other configurations.
> Allow filtering GTest tests in analysis builds

- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Refactor libusb_js_proxy_unittest to use common helpers for the frequently
repeating parts: fake JS reply dictionaries, transfer initialization
boilerplate, etc.
This is possible now that we have many test cases written and it's
visible which parts are actually easy to reuse and which not.
> Refactor LibusbJsProxy test repetitive parts

- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Resurrect Libusb tests for the scenario when asynchronous control
transfers (either input or output) fail on the JS side.
> Resurrect Libusb async control transfer error test

- smart_card_connector_app/src/manifest.json.template
We'll likely not deploy this version on WebStore, however a new release
is made for distributing a fixed standalone smart card client library
(for the regression #699).
> Release Connector App 1.3.8.0

- common/make/internal/executable_building_emscripten.mk
Silence the following warning that's emitted when compiling in the Debug
mode with TOOLCHAIN=emscripten:
emcc: warning: running limited binaryen optimizations because DWARF
info requested (or indirectly required)
[-Wlimited-postlink-optimizations]
> Suppress emscripten linker warning in Debug

- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Extend the workaround for transient USB errors to also cover the
failures in claimInterface. This fixes flaky issues with the Smart Card
Connector on the ChromeOS Lock Screen, in case when the Connector is
also installed in-session and happens to be slow to shutdown USB
connections when the session is being locked.
For the background, this workaround existed for errors in the openDevice
function since a long time. By default, PC/SC-Lite doesn't retry the USB
connections, and adding them would introduce a complex patch that's hard
to maintain. So we implemented a trick-based workaround: each time our
Libusb wrapper sees an error, it increments the "bus_number" field for
the next time this device is listed (this field's value is anyway a
complete fake as Chrome USB APIs never exposed the …
> USB transient error workaround for claimInterface

- third_party/libusb/webport/src/libusb_js_proxy.cc
Print a log message when a USB transfer function
(control/bulk/interrupt) returns an error. This will simplify
investigating bug reports, at the cost of extra verbosity as some errors
(e.g., when a device is unplugged) are expected.
> Log USB transfer errors

- common/make/js_building_common.mk
Set the goog.Promise.LONG_STACK_TRACES definition to "true" in Debug
builds for JavaScript code.
This adds a bit more debugging information when dealing with errors in
asynchronous code.
> Enable goog.Promise.LONG_STACK_TRACES for Debug

- third_party/pcsc-lite/naclport/server/build/Makefile
- third_party/pcsc-lite/naclport/server/src/utils_webport.cc
Fix spurious error logs about attempting to read a non-existing
"/var/run/openct/status" file.
This file was read by the PC/SC-Lite as an attempt to troubleshoot USB
errors, because the OpenCT daemon on Linux grabs access to USB devices
and therefore conflicts with the PC/SC-Lite daemon. These checks don't
make sense in ChromeOS, and while harmless they were triggering file
access error logs in the JavaScript console. The commit suppresses all
this by substituting the original CheckForOpenCT() function with our
own stub.
> Fix spurious openct warnings

- .github/actions/build-dependencies-installation/action.yml
- .github/workflows/makefile.yml
Set timeouts for all jobs in our GitHub workflow, so that the bots can
never hang indefinitely in case of any issue. Also set a bit tighter
timeouts on unit test steps, to make issues there pop up faster.
> Add timeouts on GitHub Actions

- third_party/ccid/patches/0002-Declare-Alcor-95x0-readers-supported.patch
- third_party/ccid/src/readers/supported_readers.txt
Declare Alcor 9540/9560 readerrs as supported, so that the Connector app
attempts to connect to them automatically, without an extra user gesture
("add reader").
Meanwhile the CCID driver's website and some internet sources claim this
reader has issues, we haven't observed them. With the current state of
things, it's better to allow such a reader to reduce user hurdles (and
if the user does experience issues with it they can always uninstall the
Connector app).
We call the reader as "95x0" in the config, because both 9540 and 9560
share the same (vendorID; productID) tuples, which makes the CCID driver
unable to distinguish between them; hence we use a string that would
work in the UI for either of them.
Chromium tracking bug: https://crbug.com/1337303.
> Declare Alcor 95x0 readers supported

- common/cpp/src/google_smart_card_common/logging/syslog/syslog.cc
- smart_card_connector_app/src/manifest.json.template
- third_party/libusb/webport/src/libusb_js_proxy.cc
Downgrade a bunch of logs to the INFO level, so that when a smart card
reader is unplugged there are no warnings/errors appearing in the
application log. This is mainly to avoid confusing users who see a red
"Errors" button in chrome://extensions whenever we log a warning/error
and might interpret it as a real problem (which in this case it's not).
> Avoid warning logs on USB device unplugging

- common/cpp/src/google_smart_card_common/nacl_io_utils.cc
- common/cpp/src/google_smart_card_common/nacl_io_utils.h
- smart_card_connector_app/src/application_unittest.cc
Fix crashes in smart_card_connector_app's application unittests due to
attempts to repeatedly remount / and /tmp directories. Before this
commit, only one test was passing and the subsequent ones were crashing
due to the leftover mounts.
Now we're unmounting the directories in each test's teardown. Also we
ignore the unmount() errors because they're fine in these test
scenarios, and in general there's little value to crash on these.
> Fix application_unittest setup under PNaCl

- common/js/src/requesting/request-receiver.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
Shorten some log messages printed by the JavaScript client-handler and
request-receiver code. Downgrade some of them to "info" or "fine" levels
to avoid spamming the log dumps with spurious errors and stop confusing
users who see "errors" displayed at chrome://extensions.
This commit contributes to the log clutter reduction tracked by #146.
> Clean up PC/SC request receiver JS logs

- make-all.sh
- test-all.sh
There's no need to duplicate the functionality across these two scripts,
and there were subtle differences that caused errors.
Testing is the same as compiling, except that we specify the "test"
target.
> Refactor test-all.sh to use make-all.sh

- smart_card_connector_app/src/application_unittest.cc
Add unit test coverage for BeginTransaction and EndTransaction in the
most basic scenario (no sharing violation involved).
> Unit-test Begin/EndTransaction in basic scenarios

- smart_card_connector_app/build/executable_module/cpp_unittests/Makefile
- smart_card_connector_app/src/application_unittest.cc
Add initial unit test coverage for the SCardGetAtrrib PC/SC method. The
test checks that calling it with SCARD_ATTR_ATR_STRING returns the
card's ATR (answer-to-reset).
> Unit-test GetAttrb for ATR

- third_party/pcsc-lite/naclport/server_clients_management/src/admin-policy-service.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompt-dialog-main.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/readiness-tracker.js
Make logs slightly more readable by shortening some of PC/SC-related
PcscLiteServerClientsManagement.* logger names.
> Shorten PcscLiteServerClientsManagement in logs

- common/js/src/logging/log-buffer.js
This commit removes the passing of goog.log.LogRecord objects between
windows, replacing it with passing their fields separately (message,
timestamp, etc.). The direct passing of objects can never work reliably
in Release mode due to Closure Compiler's optimizations that can rename
object fields differently for different targets.
The symptom of the problem addressed by this commit is that the log
messages from the Smart Card Connector's UI (window.html) had "NaN"
timestamps.
> Fix NaN timestamp in logs from window.html

- env/clean.sh
There are a few new paths that we initialize in env/initialize.sh these
days, and they should also be removed by env/clean.sh.
> Add new paths to env/clean.sh

- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
This fixes the compilation issue with Emscripten 3.1.23: the
__EMSCRIPTEN_major__ macro is undefined by default now, and
our code wrongly assumed that the Emscripten version is too old.
> Add missing emscripten/version.h include

- smart_card_connector_app/src/application_unittest.cc
One of previous commits forgot to format code via clang-format before submitting. Fix it now.
> Reapply clang-format in application_unittest

- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
Add DriveLock Smart Card Middleware (CSSI) [BETA] to the list of the trusted clients.
> Add DriveLock Beta extension to the allowlist

- smart_card_connector_app/src/create_app_manifest.py
- smart_card_connector_app/src/manifest.json.template
Allow writing comments in the manifest.json.template file which is used to generate the Smart Card Connector's manifest.json.
Comments will help documenting how and why various things are configured in the manifest.
> Add comments to manifest.json source template

- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
Add the Kiosk apps from Ujambo (in its different flavors: production, development, "acceptance") to the list of trusted client IDs, and autoallow the permission to talk to smart cards.
This allows, in particular, to use the Smart Card Connector together with them as a secondary kiosk app (in this mode it has neither any UI nor access to admin policies).
> Allowlist Ujambo Kiosk apps

- common/js/src/logging/logging.js
Fix the following crash when running our JavaScript client library in a context that has chrome.runtime.* APIs but there's no background page:
Unchecked runtime.lastError: You do not have a background page.
We should just gracefully exit the callback in that case: this code is trying to set up log forwarding from foreground to background pages, which is not needed in this case.
This fixes #755.
> Fix client lib when there's no bg page

- common/js/src/logging/log-buffer-forwarder.js
Migrate the //common/js/src/logging/log-buffer-forwader.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate LogBufferForwarder to ES6 class

- common/js/src/messaging/message-channel-pair.js
Migrate the //common/js/src/messaging/message-channel-pair.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate MessageChannelPair to ES6 class

- common/js/src/nacl-module/nacl-module-log-messages-receiver.js
Migrate the
//common/js/src/nacl-module/nacl-module-log-messages-receiver.js
file from legacy Closure Compiler classes to ES6 classes.
This is a pure refactoring change. It's is part of the effort to
modernize the code base, as recent Closure Compiler versions
stopped supporting the legacy class syntax.
> Migrate NaclModuleLogMessagesReceiver to ES6 class

- common/js/src/messaging/single-message-based-channel.js
Migrate the //common/js/src/messaging/single-message-based-channel.js
file from legacy Closure Compiler classes to ES6 classes.
This is a pure refactoring change. It's is part of the effort to
modernize the code base, as recent Closure Compiler versions
stopped supporting the legacy class syntax.
> Migrate SingleMessageBasedChannel to ES6 class

- common/js/src/messaging/port-message-channel.js
Migrate the //common/js/src/messaging/port-message-channel.js file
from legacy Closure Compiler classes to ES6 classes.
This is a pure refactoring change. It's is part of the effort to
modernize the code base, as recent Closure Compiler versions
stopped supporting the legacy class syntax.
> Migrate PortMessageChannel to ES6 class

- common/js/src/messaging/mock-port.js
Migrate the //common/js/src/messaging/mock-port.js file from
legacy Closure Compiler classes to ES6 classes.
This is a pure refactoring change. It's is part of the effort to
modernize the code base, as recent Closure Compiler versions
stopped supporting the legacy class syntax.
> Migrate MockPort to ES6 class

- common/js/src/nacl-module/nacl-module-messaging-channel.js
Migrate the
//common/js/src/nacl-module/nacl-module-messaging-channel.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate NaclModuleMessageChannel to ES6 class

- common/js/src/requesting/request-receiver.js
Migrate the
//common/js/src/requesting/request-receiver.js
file from legacy Closure Compiler classes to ES6 classes.
> Migrate RequestReceiver to ES6 class

- common/js/src/requesting/requester.js
Migrate the //common/js/src/requesting/requester.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate Requester to ES6 class

- common/js/src/requesting/requester-unittest.js
Migrate the //common/js/src/requesting/requester-unittest.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate Requester unittest to ES6 class

- common/integration_testing/src/google_smart_card_integration_testing/integration-test-controller.js
Migrate the
//common/integration_testing/src/google_smart_card_integration_testing/integration-test-controller.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate IntegrationTestController to ES6 class

- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-backend.js
Migrate the
//example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-backend.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate BuiltInPinDialog.Backend to ES6 class

- common/js/src/requesting/requester-message.js
Migrate the //common/js/src/requesting/requester-message.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate RequesterMessage to ES6 class

- third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
Migrate the
//third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js file from legacy Closure Compiler classes to ES6 classes.
> Migrate NaclClientBackend to ES6 class

- .github/workflows/makefile.yml
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
Fix compilation errors and timeouts in ASan and coverage jobs
in Continuous Integration. They started after Github Actions
updated to newer Ubuntu jammy.
Specifically, we bump `libstdc++-10-dev-i386-cross` to
`libstdc++-12-dev-i386-cross`. Also we increase test timeouts as
for some reason Debug builds got much slower.
> Fix build on Github Actions jammy

- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/libusb_opaque_types.h
When making an inbound USB transfer request to the JavaScript side (chrome.usb or WebUSB), try to avoid using excessively small transfer lengths. Specifically, round up the transfer length to the nearest multiple of the packet size.
The background for this issue is that the JS APIs don't support timeouts and cancellation properly, which is why it can sometimes happen that an early API call is resolved with the data that was logically intended for a later call. If the early call specified a shorter expected length, it'd fail completely with an error ("babble" in WebUSB or "Inbound transfer overflow" in chrome.usb), leading to a loss of that data.
This is intended to mitigate (partially or fully) #779.
> Fix for inbound USB transfer overflow

- common/cpp/build/tests/Makefile
- common/cpp/src/google_smart_card_common/join_string.h
- common/cpp/src/google_smart_card_common/join_string_unittest.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_handles_registry.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_handles_registry.h
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.h
Add warning logs into Smart Card Connector whenever a client application emits illegal concurrent PC/SC requests: an SCARDCONTEXT must only be used from a single thread (with the only exception of SCardCancel that can be called concurrently).
This is preparation for disallowing concurrent PC/SC calls in the future as planned in #136. Concurrent calls are not allowed by the PC/SC API specification, and the PC/SC-Lite's implementation breaks in subtle ways when this is violated.
> Connector warns on concurrent PC/SC calls

- .allstar/README.md
- .allstar/binary_artifacts.yaml
Add Allstar config override in order to suppress spurious bug reports about binary files stored in our repository. Those binary files are fetched as-is from trusted upstream repositories.
This fixes #786.
> Suppress Allstar reports on trusted binaries

- .allstar/binary_artifacts.yaml
Presumably, there was a format error that led to Allstar ignoring our config: repo-level ignore lists should be called `ignorePaths`, not `ignoreFiles` (apparently the latter is only for org-level configs).
This fixes #786.
> Update format in Allstar config

- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
Similarly to #639, further increase the magic sleep delay when running in the ASan (Address Sanitizer) mode. It's a hack that should fix random test failures, until a proper fix is found.
> Workaround flaky ASan memory leaks in tests

- common/cpp_unit_test_runner/src/build_emscripten.mk
Don't pass the "--experimental-wasm-bulk-memory" and "--experimental-wasm-threads" flags to Node.JS when running unit tests of WebAssembly-compiled code. These flags are obsolete and cause errors when passed to recent Node.JS versions.
This fixes #796.
> Fix CI errors due to --experimental-wasm-bulk-memory

- common/js_test_runner/run-js-tests.py
Fix our test launcher helpers to stop using the "desired_capabilities"
parameter that was deprecated in Selenium 3.
This fixes #797.
> Fix Selenium desired_capabilities obsolete flag

- .github/workflows/makefile.yml
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
Fix the magic constant in the test shutdown logic to actually
wait for 2x as long when running under Address Sanitizer.
The old code was incorrectly determining ASan, and in result
was waiting for the same timeout regardless of the ASan.
This fixes #799.
> Fix shutdown sleep for ASan builds

- third_party/libusb/webport/src/libusb_js_proxy.cc
Make following log debug-only instead of a WARNING:
"LibusbGetActiveConfigDescriptor request failed: No active config
descriptors were returned by JS API"
This log can be triggered when the USB device disappears suddenly (e.g., when transitioning to the ChromeOS Lock Screen). This is normal and doesn't deserve a warning log (which, e.g., results in showing a red "Errors" button at chrome://extensions).
> Downgrade GetActiveConfigDescriptor warning log

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
Integration tests were failing in the pnacl+Release mode, because Closure Compiler was renaming the test functions from "testSomething" to "a" or similar. The commit fixes this by putting the function names as string literals.
Note: This hasn't been noticed, since we don't run tests in "pnacl" mode on bots, and these integration tests weren't ported to "emscripten" either.
> Fix JS minification issue in C++-to-JS tests

- common/js/src/nacl-module/nacl-module.js
Detect the case when the NaCl module loading was silently ignored, and return an explicit error. This allows to clearly indicate error, e.g., when running tests in "pnacl" mode on desktop Chrome, as opposed to behaving as if the initialization takes infinitely long time.
We detect the error case by checking whether the `<embed>` that we create actually has NaCl-specific properties populated by the browser, i.e., "postMessage". That seems to be the simplest programmatic detection.
> Bail out loading NaCl module if unsupported env

- common/integration_testing/src/google_smart_card_integration_testing/integration-test-controller.js
Avoid crashing in the integration test's tearDown in case setUp didn't succeed and the binary module wasn't loaded successfully.
We shouldn't attempt to make C++ calls in case the module isn't loaded.
> Bulletproof C++-to-JS test's tearDown

- common/make/internal/executable_building_emscripten.mk
Use 1MiB of stack for all threads in C/C++ code when compiled in TOOLCHAIN=emscripten CONFIG=Debug. This should fix the stack overflow issues that were surfaced when trying to uprev Emscripten to 3.1.42 (either the stack consumption increased because of compiler change, or Emscripten became better at catching stack overflows).
By default recent Emscripten versions use very small stack (64KiB). The PC/SC-Lite code is actually trying to handle such tight environments by calling pthread_attr_setstacksize() with 256KiB for the "heavy" threads, however this turns out to be insufficient for Emscripten Debug builds.
Our fix doesn't touch this logic (assuming it's not ideal to patch PC/SC-Lite with Emscripten-specific things), and instead we tweak our build scripnts to pass an extra STACK_SIZE …
> Increase stack size in Emscripten+Debug mode

- common/make/internal/executable_building_emscripten.mk
- env/constants.sh
We expect that this uprev should prevent the following error log spam:
Pthread 0x0 completed its main entry point with an unwind, keeping
the worker alive for asynchronous operation.
> Uprev Emscripten to 3.1.42

- smart_card_connector_app/src/chrome-api-provider.js
- third_party/closure-compiler/src_additional/chrome_extensions.js
This CL add listeners of the following events to the `ChromeApiProvider`:
- chrome.smartCardProviderPrivate.onTransmitRequested
- chrome.smartCardProviderPrivate.onControlRequested
- chrome.smartCardProviderPrivate.onGetAttribRequested
- chrome.smartCardProviderPrivate.onSetAttribRequested
- chrome.smartCardProviderPrivate.onStatusRequested
- chrome.smartCardProviderPrivate.onBeginTransactionRequested
- chrome.smartCardProviderPrivate.onEndTransactionRequested
> Add listeners for connection events of chrome.smartCardProviderPrivate API

- common/make/internal/executable_building_emscripten.mk
Pass "-s RUNTIME_DEBUG=0" when linking Emscripten
code in Debug mode.
This is to suppress the very verbose logging that
recent versions of Emscripten runtime emit on some internal events (e.g., each time stack size changes). The RUNTIME_DEBUG flag, if not explicitly specified, gets auto-enabled when other *_DEBUG flags are,
which happened in our case as we use EXCEPTION_DEBUG.
> Use RUNTIME_DEBUG=0 in Emscripten+Debug

- common/make/internal/executable_building_emscripten.mk
Stop using the "-s EXCEPTION_DEBUG=1" flag in Emscripten (Debug) builds. This flag was transitively enabling some annoyingly verbose logging from Emscripten's internals. #817 attempted to fix this, but turned out to be insufficient.
> Drop EXCEPTION_DEBUG flag from Emscripten builds

- smart_card_connector_app/src/manifest.json.template
Note that this release is forked from the old 1.3.10.1 branch, so that we can perform the rollback on WebStore (i.e., publish 1.3.10.1's code under the new version 1.3.14.0).
> Release Connector 1.3.14.0

- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
This is a pure refactoring commit. Rename the impementation class to a more informational name, so that we can create an abstract "Checker" interface in a follow-up.
> Rename Checker to PolicyOrPromptingPermissionsChecker

- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/permissions-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
This is a pure refactoring commit. Introduce an abstract interface that allows to check whether a client (another extension) is allowed to send commands to Smart Card Connector. Change
PolicyOrPromptingPermissionsChecker to inherit from it. The abstraction will be used in follow-up changes to mock out the checker in tests.
> Add abstract PermissionsChecker interface

- .github/workflows/makefile.yml
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
As we're still observing flaky failures from the ASan+Debug test configuration, and as upstream PC/SC still doesn't have a proper solution to avoid this kind of teardown problem, further increase the magic sleep workaround we're using in tests.
The new formula will give x2 multipler when the build is either ASan or Debug, and x4 multiplier when both hold.
> Yet another magic sleep tweak for ASan+Debug tests

- smart_card_connector_app/src/background.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
This is a pure refactoring commit. Change the JS code to pass around a Promise instead of the whole ReadinessTracker object. This is sufficient in order to delay command processing until the server is ready, and is otherwise much simpler to mock out in tests.
> Pass Promise instead of ReadinessTracker

- third_party/pcsc-lite/naclport/server_clients_management/build/js_unittests/Makefile
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js
This unit test verifies that the ClientHandler object can be successfully created and disposed of.
> Implement smoke test for ClientHandler

- env/initialize.sh
Per [1], Chromedriver shouldn't be downloaded anymore by a two-stage process, which was first obtaining the closest Chromedriver version to the installed Chrome version, and then actually downloading the latter's package. Now, starting from Chrome 115, it's guaranteed that every official release of Chrome has a corresponding version of Chromedriver available.
[1] https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE
This also fixes #832, since the old way of downloading stopped working for Chrome >=115.
> Switch to new Chromedriver download URLs

- third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
When the reader suddenly becomes unknown in the ReaderTracker, we shouldn't emit a warning log, because it's happening legitimately when the reader is unplugged in the middle of the SCardGetStatusChange() call.
Hence log these messages at the "info" level instead.
This is another small improvement for #53.
> Downgrade warning logs for ReaderTracker removal

- common/make/common.mk
When no TOOLCHAIN environment variable is specified, assume "emscripten" by default.
Previously "pnacl" has been used by default, however it's becoming increasingly cumbersome for developers to use it.
Note that we continue shipping Smart Card Connector's pnacl version into production - this commit doesn't change that.
> Build scripts use Emscripten by default

- smart_card_connector_app/src/manifest.json.template
Bump the Smart Card Connector's minimum_chrome_version to "81", to reflect the fact that it cannot be installed onto older ChromeOS versions (due to the "invalid manifest" error).
The underlying root cause is the "chrome-untrusted://" URL that we've been using in the manifest.json since 1.3.9.3 (see #838). Unfortunately we didn't realize the backwards incompatibility issue back then, which means the current commit won't fix the issue for users on ChromeOS < 81. Still, it's better to fix the manifest to tell the real requirement now.
> Connector requires ChromeOS >=81

- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.cc
Under some circumstances PC/SC-Lite can return incorrect cbAtr, exceeding the maximum allowed MAX_ATR_SIZE. Fix this up, by treating it as zero, instead of crashing on an assertion.
The underlying root cause seems to be a race condition between the thread that handles SCardGetStatusChange() calls and the thread that manages global structures with reader information. When these read&write concurrently to the same structure, it can happen that the former reads the ATR length of the already-uninitialized reader. PC/SC-Lite's internal convention is that uninitialized reader structures have cbAtr equal to READER_NOT_INITIALIZED (which is MAX_ATR_SIZE + 1). Meanwhile we don't fix this race condition in this commit, we at least mitigate the consequences of the bug by substituting the invalid …
> Fixup instead of crashing on incorrect ATR size

- common/js/src/i18n-unittest.js
- common/js/src/logging/crash-loop-detection-unittest.js
- third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook-unittest.js
Use string literals for important function names in JavaScript unit tests ("setUp", "tearDown", "test...").
This makes sure that the compiler won't minify/rename them in Release builds, as renaming would make these functions unrecognized by the Closure Library test framework and effectively skipped silently.
> Escape test function names to prevent minification

- smart_card_connector_app/src/chrome-api-provider.js
This CL updates the typing in `smart_card_connector_app/src/chrome-api-provider.js`, since `ClientHandler` now accepts promise as a serverReadinessTracker. See  #830 for details.
> Update ServerReadinessTracker type to a promise in ChromeApiProvider

- README.md
- docs/building.md
- docs/connector-app-api.md
- docs/index-developer.md
- docs/index-third-party-application-developer.md
- docs/running-on-desktop.md
- docs/updating-ccid.md
- docs/updating-pcsc-lite.md
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- smart_card_connector_app/src/_locales/en/messages.json
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/chrome-api-provider.js
- smart_card_connector_app/src/window-main.js
- third_party/libusb/webport/src/chrome_usb/chrome-login-state-hook.js
- third_party/pcsc-lite/naclport/server/README.rst
This is the official name that's been preferred since a while. I haven't found official announcements, but a non-official one is https://9to5google.com/2022/04/29/google-prepares-chromeos-rebrand-to-drop-the-space/
> Use "ChromeOS" spelling in code and docs

- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Add a basic unit test for our libusb_get_active_config_descriptor() implementation (a.k.a LibusbJsProxy::LibusbGetActiveConfigDescriptor()).
The input parameters for the test are taken from an arbitrary real-world reader (SCM SCR 3310).
This commit is preparation for regression testing of #849.
> Unit-test libusb_get_active_config_descriptor

- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/smart-card-filter-libusb-hook-unittest.js
- smart_card_connector_app/src/smart-card-filter-libusb-hook.js
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
Only let the PC/SC see those USB device interfaces that have suitable properties. The exact criteria is replicated from what the CCID driver does internally: either the interface class should be "11" ("Smart Card") or both it should be "255" ("Vendor Specific") and the extra data length should be "54" (which is the standard length of the CCID descriptor).
The primary goal is to workaround issues with specific composite devices on modern ChromeOS versions. Before this commit, PC/SC would see all interfaces and attempt to connect via each of them. This used to cause no harm, except spurious errors (which we suppressed heuristically).
However, ChromeOS version 105 introduced behavior change, not allowing to connect to such composite devices more than once. In combination with our previously …
> Ignore non-smart-card USB interfaces

- smart_card_connector_app/src/chrome-api-provider.js
Connection state contains the number of reader insertion/removal events in upper 16 bits.
This is not used by smartCardProviderPrivate API, so we want to only look at lower bits. Otherwise, the equalities we check for connection states won't hold if upper bits are non-zero.
> Don't look at upper bits when converting connection state

- third_party/ccid/patches/0003-Check-num_altsetting-before-dereffing-altsetting.patch
- third_party/ccid/src/src/ccid_usb.c
Cherry-pick the "Check num_altsetting before dereffing altsetting" commit from the CCID Driver repository.
This is supposed to fix the occasional crashes we observe after applying the mitigation from #849.
> Cherry-pick upstream CCID fix for null-deref

- smart_card_connector_app/src/application_unittest.cc
Add a new test for the Smart Card Connector's PC/SC implementation that's parameterized by the simulated reader type. This lets us test some basic scenarios work correctly for a range of different devices.
This is a regression test for #849.
> Add PC/SC test running with every simulated reader

- .github/workflows/makefile.yml
Normally our continuous integration scripts post a comment on a Pull Request once all jobs successfully complete. However, this doesn't work when the PR is in a fork, as the "Resource not accessible by integration" permission error occurs
(https://github.com/peter-evans/create-or-update-comment#action-inputs).
This commit makes this job being completely skipped. That way, we avoid spurious errors for now, until we maybe figure out the right way to do it.
> [CI] Don't try posting comments in PRs in forks

- common/integration_testing/build/Makefile
Only build the NaCl-specific integration_test source file (integration_test_pp_module.cc) when the TOOLCHAIN=pnacl is specified.
This is preparation commit for enabling these tests on TOOLCHAIN=emscripten (tracked by #816).
> [JS-to-C++ test] Guard NaCl-specific sources build

- common/integration_testing/build/Makefile
- common/integration_testing/include.mk
- common/integration_testing/src/build_nacl.mk
- example_cpp_smart_card_client_app/build/integration_tests/Makefile
Move the existing NaCl build rules into a common location, and refactor them to be an implementation of a toolchain-agnostic makefile rule.
This is preparation for introducing Emscripten build support for the same tests, and also for new JS-to-C++ integration tests (tracked by #816).
> [JS-to-C++ test] Toolchain-agnostic build interface

- common/js_test_runner/run-js-tests.py
Add the "--serve-via-web-server" parameter to the "run-js-tests.py" script, allowing to run JS tests via "http://localhost" URLs pointing to a temporary local web server, as opposed to the "file://" URLs used before.
This is preparation for implementing Emscripten integration tests (tracked by #816), because the way how Emscripten modules are loaded involves operations that Chrome forbids on file:// URLs.
> [JS-to-C++ test] run-js-tests can host web server

- common/js_test_runner/run-js-tests.py
Add the "--chrome-arg" parameter to the "run-js-tests.py" script, allowing a build script to specify additional command-line parameters to be specified when launching Chrome[driver].
This commit contributes to #816, because by default Chrome doesn't allow multithreaded Emscripten programs: technically, SharedArrayBuffer isn't allowed unless the website specifies CORS headers, which would be too tedious to set up for our simple localhost server. Instead, we're going to force-allow the needed Chrome features via command line.
> [JS-to-C++ test] run-js-tests custom Chrome args

- Makefile
Now that the JS-to-C++ support for TOOLCHAIN=emscripten has been added, we can enable this in the top-level makefile.
This enables it for developers (`make test`) and Continuous Integration.
This commit contributes to #816.
> [JS-to-C++ test] Turn on tests in Emscripten build

- Makefile
- smart_card_connector_app/build/js_to_cxx_tests/.gitignore
- smart_card_connector_app/build/js_to_cxx_tests/Makefile
- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Add build scripts and an empty test for testing Smart Card Connector. This boilerplate can be used for adding functional tests in follow-ups as tracked by #869.
> [JS-to-C++ test] Boilerplate for testing Connector

- common/integration_testing/build/Makefile
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
Change IntegrationTestHelper::SetUp() to return its result asynchronously via a callback.
These asynchronous helpers will be used in follow-up PRs for doing startup/shutdown of the PC/SC server in JS-to-C++ tests of Smart Card Connector, tracked by #869.
> [JS-to-C++ test] Make helper SetUp async

- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.h
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
Change IntegrationTestHelper::TearDown() to report its completion asynchronously via a callback.
This change is similar to the previous change for SetUp(), except that teardown doesn't need to return any value, and that we have to properly account for callbacks in the bulk "tear down all helpers" operation.
> [JS-to-C++ test] Make helper TearDown async

- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Add a test that verifies the PC/SC server successfully started up.
Technically, the JS side does this by asking the C++ side to set up the "SmartCardConnectorApplicationTestHelper", and then waiting until the C++ side sends the "ready" message to the JS.
Follow-ups will use this approach for testing actual PC/SC functionality, as tracked by #869.
> [JS-to-C++ test] Test PC/SC server startup

- common/integration_testing/src/build_emscripten.mk
Specify a generous timeout when running JS-to-C++ tests in Emscripten mode (via run-js-tests.py, which in turn uses Chromedriver). The default timeout of 60 seconds is insufficient for anything more than a single test case with the PC/SC server startup+shutdown.
This contributes to #869.
> [JS-to-C++ test] Increase timeout in Python wrapper

- common/integration_testing/src/build_emscripten.mk
- common/js_test_runner/run-js-tests.py
Let the developer pass the MANUAL_TEST_DEBUGGING=1 environment variable to make the test runner's web page visible and also to leave it opened after the tests finish.
We gate this behavior under an environment variable because Continuous Integration and routine test executions shouldn't mess up with the UI or hang on failures.
> [JS-to-C++ test] Allow developer manual test debug

- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Extend the C++-to-JS test of the SCardEstablishContext() a little bit,
by checking the variant with explicitly passed optional arguments.
> [JS-to-C++ test] Test args of SCardEstablishContext

- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
Make a separate callback for each type of the observation: (a) just message, (b) request message, (c) response message. Previously all three types were using the same callback type, but the arguments were omitted or had different meaning depending on the case.
The refactoring should make the code clearer and simplify passing use-case-specific arguments. This is preparation for USB simulation in JS-to-C++ tests as tracked by #869.
> Refactor TestingGlobalContext callbacks

- common/integration_testing/build/Makefile
- common/integration_testing/src/build_emscripten.mk
- common/integration_testing/src/build_nacl.mk
- example_cpp_smart_card_client_app/build/executable_module/Makefile
- example_cpp_smart_card_client_app/build/integration_tests/Makefile
- third_party/libusb/webport/build/Makefile
- third_party/pcsc-lite/naclport/common/build/Makefile
- third_party/pcsc-lite/naclport/cpp_client/build/Makefile
- third_party/pcsc-lite/naclport/cpp_demo/build/Makefile
- third_party/pcsc-lite/naclport/server_clients_management/build/Makefile
Add the repository's root directory into the C/C++ search path.
This is preparation for the refactoring to use absolute include paths consistently, as tracked by #885.
> [headers] Add root dir to include search path

- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
Add a primitive for "rerouting" C++-to-JS requests in tests.
This will be used in follow-ups to refactor how application_unittests work today, i.e., how they stub out Libusb's requests with the TestingSmartCardSimulation class. We need this to make the latter easier to reuse for JS-to-C++ tests, as tracked by #869.
> Helper for rerouting requests in tests

- common/cpp/src/public/testing_global_context.cc
- common/cpp/src/public/testing_global_context.h
Make TestingGlobalContext, when it intercepts a request's response, pass the error message if it's populated instead of the payload.
This will be used by follow-ups to properly reroute request-response USB commands, including those that failed, in application_unittest. This commit contributes to #869.
> Test stub passes through response error messages

- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
Refactor TestingSmartCardSimulation to receive the incoming USB commands on its own receiver "testing_smart_card_simulation", instead of intercepting the "libusb" requests.
This change is no-op for the existing application_unittests, but it makes it easier to reuse TestingSmartCardSimulation in JS-to-C++ tests: we want those tests to follow the longer path:
[C++]Libusb => ... [JS] ... => [C++]TestingSmartCardSimulation
instead of the hacky shortcuts that we had to do in application_unittest:
[C++]Libusb => [C++]observer => [C++]TestingSmartCardSimulation
> TestingSmartCardSimulation owns request receiver

- smart_card_connector_app/build/js_to_cxx_tests/Makefile
Add the CCID driver's Info.plist config file into the output directory for smart_card_connector's js_to_cxx tests.
This is needed so that the PC/SC daemon can load the CCID driver at runtime and do anything useful. This is preparation for enabling USB simulation in tests as tracked by #869.
> [JS-to-C++ test] Pull CCID config file

- smart_card_connector_app/build/js_to_cxx_tests/Makefile
- smart_card_connector_app/src/application_integration_test_helper.cc
Instantiate TestingSmartCardSimulation in JS-to-C++ tests that use SmartCardConnectorApplicationTestHelper.
To note, it's still disfunctional because we need to wire it up with Libusb requests. This will be addressed in follow-ups.
> [JS-to-C++ test] Create TestingSmartCardSimulation

- third_party/libusb/webport/src/libusb_contexts_storage.cc
- third_party/libusb/webport/src/libusb_contexts_storage.h
- third_party/libusb/webport/src/libusb_error_name.c
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_js_proxy_data_model.cc
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/libusb_opaque_types.h
- third_party/libusb/webport/src/libusb_tracing_wrapper.cc
- third_party/libusb/webport/src/libusb_tracing_wrapper.h
- third_party/libusb/webport/src/public/libusb_web_port_service.cc
- third_party/libusb/webport/src/usb_transfer_destination.cc
- third_party/libusb/webport/src/usb_transfers_parameters_storage.cc
- third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Change `#include "foo.h"` (which implicitly relied on manipulated include search paths) to `#include "third_party/libusb/webport/src/"`.
> [headers] Include by abs path from libusb/webport/

- common/integration_testing/src/entry_point_emscripten.cc
- common/integration_testing/src/entry_point_nacl.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_helper.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.cc
- common/integration_testing/src/google_smart_card_integration_testing/integration_test_service.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge_integration_test_helper.cc
- smart_card_connector_app/src/application_integration_test_helper.cc
Change `#include <google_smart_card_integration_testing/...>` includes to `#include "common/integration_testing/src/..."`.
> [headers] Include by abs path from common/integration_testing/

- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application.h
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/pcsc_lite_tracing_wrapper.cc
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/pcsc_lite_tracing_wrapper.h
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_debug_dump.cc
- third_party/pcsc-lite/naclport/common/src/google_smart_card_pcsc_lite_common/scard_structs_serialization.cc
- third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.cc
- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.cc
- third_party/pcsc-lite/naclport/cpp_client/src/pcsc_lite_over_requester.h
- third_party/pcsc-lite/naclport/cpp_demo/src/google_smart_card_pcsc_lite_cpp_demo/demo.cc
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
- third_party/pcsc-lite/naclport/server/src/server_sockets_manager.cc
- third_party/pcsc-lite/naclport/server/src/winscard_msg_nacl.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/admin_policy_getter.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_handles_registry.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/client_request_processor.h
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.h
- third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/backend.cc
- third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/backend.h
- third_party/pcsc-lite/naclport/server_clients_management/src/google_smart_card_pcsc_lite_server_clients_management/ready_message.cc
Change `#include <google_smart_card_pcsc_...>` and same-directory `#include "foo.h"` includes to `#include
"third_party/pcsc-lite/naclport/..."`.
> [headers] Include by abs path from pcsc-lite/

- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application_integration_test_helper.cc
- smart_card_connector_app/src/entry_point_emscripten.cc
- smart_card_connector_app/src/entry_point_nacl.cc
Change same-directory `#include "foo.h"` includes to `#include "smart_card_connector_app/src/..."`.
> [headers] Include by abs path from smart_card_connector_app/

- smart_card_connector_app/build/js_unittests/Makefile
Exclude JS-to-C++ sources from compilation of js_unittests, because these integration-like tests need special setup and are executed in a separate target.
This commit contributes to #902.
> [JS unit tests] Fix connector_app test building

- Makefile
- smart_card_connector_app/build/js_unittests/Makefile
Build and execute JS unit tests under smart_card_connector_app/.
This commit contributes to #902.
> [JS unittests] Enable Connector tests

- clean-all.sh
Currently, in case the virtual environment wasn't initialised, e.g., `initialize.sh` was called with `-t emscripten` flag, clean-all breaks after an attempt to clean for toolchain='pnacl'.
This CL changes it to continue with other clean tasks.
> Continue clean for other toolchains if it breaks for pnacl

- third_party/libusb/webport/src/libusb_js_proxy.h
The comment was obsolete in it referring to chrome.usb. Some semi-recent changes made this C++ code support both WebUSB and chrome.usb.
This is non-functional change.
> [libusb] Fix outdated comment on chrome.usb

- common/cpp_unit_test_runner/src/build_emscripten.mk
- common/make/internal/executable_building_emscripten.mk
Tell Emscripten to only generate code for supporting "web"/"worker" environment by default, and only "node" when building C++ unit test runner.
This commit optimizes away unneeded support code from the resulting artifacts. The exact improvement is around a couple kilobytes, still there's no reason to avoid doing this.
For reference, the default value of the "ENVIRONMENT" Emscripten setting is "web,webview,worker,node".
> [wasm] Prune unneeded ENVIRONMENT support code

- common/make/internal/executable_building_emscripten.mk
Disabling generating Emscripten support code for non-Chrome browsers (at the moment, IE, Edge, Safari, Firefox). Our smart card applications only intend to target ChromeOS.
This doesn't result in noticeable size reductions, still should be a harmless tweak to enable.
> [wasm] Turn off support for non-Chrome browsers

- common/js/src/executable-module/emscripten-module.js
- common/make/internal/executable_building_emscripten.mk
Tell Emscripten to only generate code for the attributes of the Module class that we're actually using at runtime. This allows to optimize away code for unneeded ones.
In practice, this reduces the resulting files by a couple kilobytes.
> [wasm] Prune code for unneeded Module attributes

- common/make/internal/executable_building_emscripten.mk
Skip generating Emscripten support code for Chrome versions <96. There are multiple technical reasons why we won't ship WebAssembly builds to such ancient client versions, so let's benefit from it by letting Emscripten prune workarounds for them.
Note: the binary size reduction is almost negligible in practice.
> [wasm] Drop support for ancient Chrome

- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Fix the crash during the PC/SC server shutdown in case there's at least one connected JS client.
The underlying problem was that we didn't tear down the C++ client handling subsystem, and hence kept open pipes beyond the shutdown of all other systems. It was a test-only issue since the extensions never shut down in production (unless killed by the browser).
> [pcsc] Fix crash on shutdown with active client

- smart_card_connector_app/build/js_to_cxx_tests/Makefile
Fix the accidental inclusion of Libusb's unit tests into the Smart Card Connector's js_to_cxx_tests test target.
The Libusb unit tests are already tested by their own target //third_party/libusb/webport/build/js_unittests/.
> [JS-to-C++ test] Exclude libusb unit tests

- example_cpp_smart_card_client_app/src/application.cc
- example_cpp_smart_card_client_app/src/application.h
- third_party/pcsc-lite/naclport/cpp_client/src/google_smart_card_pcsc_lite_client/global.cc
Change `#include <google_smart_card_pcsc_lite_client...>` to `#include "third_party/pcsc-lite/..."`.
> [headers] Include by abs path from pcsc-lite cpp_client

- smart_card_connector_app/src/window-main.js
- smart_card_connector_app/src/window-status-displaying.js
Create a new window-status-displaying.js and move the logic that displays the "ChromeOS only" warning into it.
This is a pure refactoring change. It's a preparation for implementing crash warning UI as tracked by #926.
> [ui] Refactor OS warning UI into separate file

- common/js/src/messaging/message-channel-pool.js
- common/js/src/messaging/single-message-based-channel-unittest.js
- smart_card_connector_app/src/chrome-api-jstocxxtest.js
- smart_card_connector_app/src/chrome-api-provider.js
- smart_card_connector_app/src/testing-smart-card-simulation-libusb-hook.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Fix a few occurrences of missing semicolons in JS code. This is found via ESLint.
This is a pure refactoring commit.
> [js style] Fix missing semicolons

- smart_card_connector_app/src/_locales/en/messages.json
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/window-status-displaying.js
- smart_card_connector_app/src/window.css
- smart_card_connector_app/src/window.html
If the executable module crashes (and cannot recover by self-reloading), notify the user by displaying a warning in the Smart Card Connector's main window UI.
This fixes #926.
> [ui] Show warning in UI if application crashed

- third_party/pcsc-lite/naclport/server_clients_management/src/admin-policy-service.js
Fix exception thrown in AdminPolicyService in case the managed storage gets loaded after the object is already disposed of.
This doesn't happen normally, but in case the executable module crashed due to some issue this AdminPolicyService exception would be a red herring that confuses the developer.
> [policy] Fix crash if policy loaded after disposal

- common/js/src/executable-module/emscripten-module.js
If the Emscripten module crashed, we should avoid making new operations with it that can trigger new exceptions (which would be confusing and useless). Hence we do two improvements in this commit:
1. Don't try calling the C++ object destructor after the crash.
2. Discard messages that the module tries to send to the JS side after the module's disposal.
> [wasm] Improve handling of crashes

- common/js/src/logging/log-buffer.js
- common/js/src/messaging/message-channel-pair.js
- common/js/src/requesting/requester-unittest.js
- smart_card_connector_app/src/chrome-api-provider.js
- smart_card_connector_app/src/chrome-login-state-hook-unittest.js
- smart_card_connector_app/src/smart-card-filter-libusb-hook-unittest.js
Fix a few occurrences of extra semicolons in JS code. This is found via ESLint.
This is a pure refactoring commit.
> [js style] Fix extra semicolons

- common/js/src/messaging/port-message-channel-unittest.js
- common/js/src/messaging/single-message-based-channel-unittest.js
- common/js/src/requesting/requester-unittest.js
Whenever we already have a shorter alias defined in the file, prefer to use it in favor of the long name. This is a pure refactoring commit.
This is found via ESLint. It's part of the effort tracked by #937.
> [js style] Use aliases where already defined

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
Make sure to dispose of BridgeBackend in the bridge-integrationtest's teardown.
This was spotted while looking through the ESLint reports per #937.
> [JS-to-C++ test] Tear down BridgeBackend

- common/js/src/logging/crash-loop-detection-unittest.js
- common/js/src/logging/crash-loop-detection.js
- common/js/src/nacl-module/nacl-module.js
Instead of calling hasOwnProperty() on the target object, use the Object.prototype.hasOwnProperty.call() notation instead. This makes sure there's no shadowing possible.
This is found via ESLint. It's part of the effort tracked by #937.
> [js style] Fix no-prototype-builtins

- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
- third_party/pcsc-lite/src/src/hotplug_libusb.c
Fix flaky memory leaks and drop magic sleep in the PC/SC shutdown logic, in favor of deterministic signaling and waiting.
> [pcsc] Fix flaky shutdown

- common/integration_testing/src/public/integration_test_service.cc
Make sure to shut down the IntegrationTestService's request receiver before dropping a reference on it, so that use-after-free isn't possible in case there's a background thread still using it.
This is part of the test flakiness fixes tracked by #951.
> [JS-to-C++ test] Shut down request receiver

- common/js_test_runner/run-js-tests.py
Collect and dump all logs from the JS console in case the test fails, for easier investigation for the developer.
> [JS-to-C++ test] Print full JS logs on failure

- common/integration_testing/src/public/integration-test-controller.js
- common/js/src/container-helpers-unittest.js
- common/js/src/deferred-processor.js
- common/js/src/executable-module/emscripten-module.js
- common/js/src/i18n-unittest.js
- common/js/src/json.js
- common/js/src/logging/crash-loop-detection-unittest.js
- common/js/src/logging/logging.js
- common/js/src/messaging/message-channel-pool.js
- common/js/src/requesting/requester-unittest.js
- common/js/src/requesting/requester.js
- smart_card_connector_app/src/chrome-login-state-hook-unittest.js
- third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Fix the "new-parens" ESLint error.
This is part of the cleanup tracked by #937.
> [js style] Use brackets when calling constructors

- common/js/src/container-helpers.js
- common/js/src/i18n.js
- common/js/src/messaging/message-channel-pair.js
- common/js/src/messaging/message-channel-pool.js
- common/js/src/messaging/mock-port.js
- common/js/src/messaging/port-message-channel-unittest.js
- common/js/src/messaging/single-message-based-channel-unittest.js
- smart_card_connector_app/src/chrome-api-jstocxxtest.js
- smart_card_connector_app/src/chrome-api-provider.js
- smart_card_connector_app/src/window-devices-displaying.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
Use const instead of let whenever possible.
This is found and fixed via ESLint. This refactoring is part of the effort tracked by #937.
> [js style] Use const when possible

- common/js/src/logging/logging.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
Reformat JS code to fit into 80-column limit whenever possible (e.g., we leave long URLs as-is).
This is found via ESLint. This refactoring is part of the effort tracked by #937.
> [js style] Fix excessively long lines

- .eslintrc.yml
Add the initial config for ESLint - the JavaScript linter tool.
The config enables most of the standard rules, except those that cause major incompatibility with our Closure-based source code.
Follow-ups will add scripts and CI actions that use this config.
This commit is part of the effort tracked by #937.
> [js style] Add basic ESLint config

- .eslintrc.yml
Enable more of turned-off-by-default ESLint rules.
This commit is part of the effort tracked by #937.
> [js style] More ESLint rules

- common/js/src/promise-helpers.js
Remove @return from the function that doesn't return anything.
This was found by ESLint. This is part of the cleanup tracked by #937.
> [js style] Fix excessive return tag

- env/constants.sh
We don't require any particular improvements, however it's good to keep up with upstream to learn about possible issues earlier.
> Update Emscripten to 3.1.45

- third_party/pcsc-lite/naclport/cpp_demo/src/google_smart_card_pcsc_lite_cpp_demo/demo.cc
Change `#include <google_smart_card_pcsc_lite_cpp_demo...>` to `#include "third_party/pcsc-lite/..."`.
> [headers] Include by abs path from pcsc-lite cpp_demo

- format-code.sh
- scripts/internal/find-files-for-linting.sh
Create a separate helper script for finding manually maintained source files. Currently it's only used for running clang-format from format-code.sh, but we're planning to add a similar script for JS linting.
This contributes to the effort tracked by #937.
> Refactor logic for finding sources-to-be-linted

- scripts/eslint.sh
Add helper script that runs the ESLint NPM module on all currently modified JavaScript files.
This can be used manually by developers, and also follow-ups will automatically execute it on every CI run, as tracked by #937.
> [js style] Script for running ESLint

- Makefile
JavaScript code building and testing is only useful in relevant toolchains (currently emscripten and pnacl). It should be skipped in analysis builds that are currently focused on C/C++ code (asan_testing and coverage).
This would improve CI speed a bit by shaving off unnecessary operations in those jobs.
> [ci] Skip JS targets in sanitizer/coverage builds

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
Detect cases in KnownAppsRegistry when goog.net.XhrIo reports
isSuccess()==true, but at the same time getResponseText()==''. As
it turned out, this is also a possible way of signaling an error from
XhrIo.
This is a generic cleanup, since in production we don't expect any
errors happening there (because the fetched URL belong to our
own CRX).
> Handle more Xhrio failures

- env/initialize.sh
Don't initialize env's python3_venv and chromedriver when building for analysis (asan_testing and coverage).
This should reduce the analysis build job times a bit.
> [ci] Skip python3_venv and chromedriver in analysis

- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Verify the JavaScript API's SCardCancel() behavior on canceling a blocking SCardGetStatusChange() call.
> [JS-to-C++ test] Test SCardCancel success

- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
- smart_card_connector_app/src/testing-smart-card-simulation-constants.js
Verify the JavaScript API's SCardGetStatusChange() behavior on card insertion/removal events.
> [JS-to-C++ test] Test SCardGetStatusChange cards

- .eslintrc.yml
- common/js/src/requesting/requester.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Enable ESlint's no-invalid-this diagnostics, and refactor some code to avoid spurious warnings (no real bug detected though).
This contributes to the effort tracked by #937.
> [js style] Enable no-invalid-this linter

- .eslintrc.yml
Turn on a bunch of ESLint checks that are documented as "suggestions" ("these rules suggest alternate ways of doing things"). We skip those that trigger too many false positives or require fixing the code (better done in separate PRs).
This is part of the linting effort tracked by #937.
> [js style] Enable more ESLint suggestion checks

- .github/workflows/makefile.yml
When a PR is published that touches ESLint stuff (config, scripts, etc.),
the PR actions should run the linter on all files in the repository. That
way, the developer gets immediate feedback about the change, as
opposed to learning from errors after the PR gets merged into main.
This commit contributes to #937.
> [js style] PRs touching linting are checked on all

- .eslintrc.yml
- common/js/src/logging/crash-loop-detection-unittest.js
And fix the existing violation of this rule (in tests).
This commit contributes to #937.
> [js style] Enable ESLint guard-for-in

- smart_card_connector_app/src/chrome-api-jstocxxtest.js
Add tests to check that events with various `eventState`s and `eventCount`s are handled correctly.
Add test with optional timeout parameter passed.
> [chrome-api-jstocxxtest] Add more GetStatusChange tests

- clean-all.sh
Fix the following error `[-f: Command not found]` that was happening during clean, because of missing whitespaces.
> Fix clean-all.sh for pnacl

- env/initialize.sh
As in practice it's not guaranteed that every public Chrome release gets a corresponding Chromedriver release with the exact same version, we change env/initialize.sh to fetch using just milestone instead.
This is a different attempt to fix #1009. It's also a partial revert of #834 (as Chromedriver maintainers seem to have revived the convenient LATEST_RELEASE_ URLs).
> Choose latest Chromedriver per Chrome milestone

- smart_card_connector_app/src/application_unittest.cc
Remove test assertions that PC/SC handles and contexts must be nonzero.
This isn't guaranteed by the specs or the implementation, and while in theory frequent zeroes might be an indication of broken random generators, it's better to verify it in some other way.
> [PC/SC test] Don't assert handle/context non-zero

- smart_card_connector_app/src/testing_smart_card_simulation.cc
One code path in TestingSmartCardSimulation - the USB interrupt transfer that's intended to notify about card insertions/removals - was returning values of incorrect format, causing assertion failures down the stack.
Presumably this never caused observable test failures, since the tests happened to coincide with the CCID driver's internal task timing (which would mean the interrupt transfers are undertested as of now).
> [JS-to-C++ test] Fix flaky USB transfer exception

- format-code.sh
- scripts/format-code.py
Rewrite the format-code Shell script into Python, and make it support "--base=..." argument.
The refactoring is for better maintainability, and the "--base" arg allows reformatting the whole repository instead of the current diff.
> [style] format-code in Python, supports --base

- smart_card_connector_app/src/background.js
Add log on ChromeApiProvider successful creation. Log if provider needs to be created/destroyed due to policy.
> [Web API] Log on ChromeApiProvider creation/disposal

- smart_card_connector_app/src/chrome-api-jstocxxtest.js
- smart_card_connector_app/src/mock-chrome-api.js
Currently all expectations need to be set before any testing takes place, because there's no way to switch between replaying and recording mode in goog.testing framework. Because of that we couldn't factor out repeated pieces of code, such as establishing context, to a separate function.
This CLs adds `getFreshMock` method to allow refactoring in the follow-up CLs.
> [chrome-api-jstocxxtest] Add method to switch mocks back to recording

- .github/workflows/makefile.yml
`set-output` is [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
> Update set-output to GITHUB_OUTPUT

- Makefile
- common/integration_testing/include.mk
- common/js/build/js_to_cxx_tests/.gitignore
- common/js/build/js_to_cxx_tests/Makefile
- common/js/build/unittests/Makefile
- common/js/include.mk
- common/js/src/executable-module/executable-module-jstocxxtest.js
Add build target for //common/js/build/js_to_cxx_tests/, so that we can write tests for this common JS and C++ code.
This is preparation for implementing a regression test for #823.
> [JS-to-C++ test] Boilerplate for //common/js tests

- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
Add unit tests for the TrustedClientsRegistry
class which is responsible for querying information about the trusted client
application origins from the bundled JSON config.
> Trusted clients registry unit tests

- .github/actions/build-dependencies-installation/action.yml
- .github/workflows/makefile.yml
* Specify DEBIAN_FRONTEND=noninteractive to suppress spammy progress updates with percents.
* Use actions/checkout v4's "show-progress: false" to suppress spammy git progress updates.
* Bump actions/setup-python to v4, which fixes the "The `set-output` command is deprecated" warning.
* Bump peter-evans/create-or-update-comment to v3 just because.
> [ci] Reduce apt/git log spam, uprev github actions

- smart_card_connector_app/src/chrome-api-jstocxxtest.js
Move `createChromeApiProvider` to set-up.
> [chrome-api-jstocxxtest] Move creation of provider to set-up

- common/make/js_building_common.mk
We don't keep backwards compatibility with such old ChromeOS versions that requires JS syntax from 2012. Hence tell Closure Compiler to use the 2020 syntax, corresponding to Chrome 81 that we currently specify as "minimum_chrome_version" for Smart Card Connector production builds.
This slightly reduces the final CRX files (-2% for Smart Card Connector). Also we hope this should reduce the frequency of mysterious Closure Compiler failures (like "Partial alias created for namespace $jscomp.scope, possibly due to await/yield transpilation").
> [js] Use JS 2020, don't transpile to JS 2012

- scripts/format-code.py
Add new parameter "--check-only" to the format-code.py script.
It's primarily intended to be used in automated checks, like CI actions, for checking for improperly-formatted code.
> [style] format-code check-only mode

- .eslintrc.yml
- env/initialize.sh
- scripts/eslint.py
- smart_card_connector_app/src/chrome-api-jstocxxtest.js
- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Install and enable ESLint's "no-floating-promise" plugin, to prevent future bugs when an async function is forgotten to be awaited.
Also add a few awaits to silence the warnings, although in these places "await" wasn't strictly necessary.
> [js style] Add eslint-plugin-no-floating-promise

- common/js/src/executable-module/emscripten-module-js-epilog.js.inc
- common/js/src/executable-module/emscripten-module.js
- common/make/internal/executable_building_emscripten.mk
Disposing of EmscriptenModule forcibly terminates all Emscripten threads and workers.
This is to avoid resource usage beyond the point when the module should've been logically disposed of. In particular, this should fix flaky OOM failures in the js_to_cxx tests that we run in succession now.
> [wasm] Force-kill threads and workers on disposal

- .eslintrc.yml
This rule disagrees with clang-format in some cases, e.g. the "for(...; ;...)" kind of loop.
> [js style] Disable semi-spacing ESLint

- common/integration_testing/src/public/integration-test-controller.js
- common/js/src/deferred-processor.js
- common/js/src/executable-module/executable-module.js
- common/js/src/json.js
- common/js/src/messaging/single-message-based-channel-unittest.js
- common/js/src/popup-window/popup-opener.js
- common/js/src/promise-helpers.js
- common/js/src/requesting/request-receiver.js
- common/js/src/requesting/requester.js
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- example_js_smart_card_client_app/src/pin-dialog/pin-dialog-server.js
- smart_card_connector_app/src/chrome-api-provider.js
- smart_card_connector_app/src/chrome-login-state-hook-unittest.js
- smart_card_connector_app/src/testing-smart-card-simulation-libusb-hook.js
- smart_card_connector_app/src/window-apps-displaying.js
- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/pcsc-lite/naclport/cpp_client/src/nacl-client-backend.js
- third_party/pcsc-lite/naclport/js_client/src/api.js
- third_party/pcsc-lite/naclport/js_client/src/reader-tracker-through-pcsc-api.js
- third_party/pcsc-lite/naclport/server/src/reader-tracker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/permissions-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/trusted-clients-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/readiness-tracker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
Replace "goog.Promise" with "goog.Thenable" in type annotations.
The latter is more generic and allows both the (Closure-specific, now-deprecated) goog.Promise as well as the standard ECMAScript Promise. As we're trying to migrate the codebase to the latter, the more generic type annotation helps start this gradually.
> [js promise] Use Thenable in type annotations

- third_party/libusb/webport/src/libusb-proxy-hook.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Explicitly do "await" instead of returning a promise obtained from another function.
It's considered best practice, as it makes asynchronous points more explicit and also captures the current frame in the promise's stack trace.
This commit was prepared by enabling the "require-await" ESLint diagnostic, however we don't commit it because it has lots of false positives (on abstract classes, on functions returning "new Promise", on overrides that return result synchronously, etc.).
> [js style] await instead of returning promise

- common/js/src/promisify-extension-api.js
- third_party/libusb/webport/src/libusb-to-chrome-usb-adaptor.js
Make the "promisification" of Extension APIs available as a common helper that can be reused in other places beyond
libusb-to-chrome-usb-adaptor.js.
This is a pure refactoring commit.
> [js promise] Move promisify to common

- common/cpp/src/logging_integration_test_helper.cc
- common/js/build/js_to_cxx_tests/Makefile
- common/js/src/executable-module/executable-module-jstocxxtest.js
Add a test that crash in a C++ executable module gets correctly handled on the JS side, in particular marks the module as disposed.
This test verifies a slightly simpler scenario than the regression fixed in #823.
> [JS-to-C++ test] Test crashes

- common/js/src/requesting/requester-unittest.js
- common/js/src/requesting/requester.js
Improve the JS Requester class to gracefully handle this edge case: the send() call triggers not only an exception, but also the disposal of the message channel. The bug was that we were trying to reject the same request twice (first during disposal, second while handling the exception).
This is follow-up to the crash handling issue fixed in #823.
> JS Requester handles disposal-and-exception-while-sending

- common/js/src/async-asserts.js
- common/js/src/requesting/requester-unittest.js
- smart_card_connector_app/build/js_to_cxx_tests/Makefile
- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Test that a C++ crash in the executable module gets correctly handled in case there's an active PC/SC client. The module and the client should get disposed of without any unexpected exceptions.
This is a regression test for #823.
> [JS-to-C++ test] Test crash with active PC/SC client

- common/integration_testing/src/build_emscripten.mk
- common/js_test_runner/run-js-tests.py
- common/make/js_building_common.mk
Fix the tests executed via Chromedriver/Selenium to respect the CHOME_PATH make variable that lets specifying custom path to Chrome binary.
> [JS tests] Unify the used Chrome binary path

- third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js
The "Server message channel was disposed, disposing..." message should be a regular "info" log rather than "warning". In particular, this prevents warning log spam in the JS-to-C++ integration tests.
> [logging] Downgrade warning in server-request-handler.js

- common/js/src/promisify-extension-api.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
Simplify asynchronous code in UserPromptingChecker using the common promisify() helper function.
Also bullet-proof promisify() for environments that don't have full Chrome API definitions like `chrome.runtime` (this is also needed to make unit tests pass).
> [js promise] Use promisify in UserPromptingChecker

- smart_card_connector_app/src/application_unittest.cc
Add tests for the cases of calling SCardEndTransaction() when there's no actual transaction active.
> [PC/SC test] More EndTransaction errors

- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Add test cases for the successful/broken scenarios when the SCardConnect() is called multiple times with different protocols requested.
> [JS-to-C++ test] Test SCardConnect protocol mismatch

- smart_card_connector_app/src/application_unittest.cc
Add unit tests that verify the PC/SC shutdown process doesn't take unnecessarily long, especially in the "reader added shortly before the shutdown" scenarios.
This is regression test for #1078.
> Test for 10-minute shutdown hang

- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
Implement simulation of a new device - Yubico Yubikey 4C. There's no particular reason this device is chosen, except that to increase test coverage for various types of devices.
The simulation that's added is minimalistic and makes only the basic interactions (plug in/out, obtain ATR) work. More can be added later if necessary.
> [PC/SC test] Simulate Yubikey 4C

- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/managed_storage_schema.json
This CL makes ChromeApiProvider created by default, not guarded by the managed schema policy.
> [Web API] Remove expose_chrome_smart_card_api policy check

- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Similarly to https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/pull/1077,
refactor pcsc-api-jstocxxtest.js to group test cases together into constant
variables, to make the deeply nested structure of tests easier to follow.
This is a pure refactoring change.
> [JS-to-C++ tests] Refactor PC/SC test sources

- smart_card_connector_app/src/application_unittest.cc
Relax tests a bit to account for PC/SC-Lite not-well-defined behavior for event counters: depending on timing, the first few updates of the card presence may not be accounted.
This fixes #1095.
> [PC/SC test] Fix flakiness due to eventCount

- smart_card_connector_app/src/manifest.json.template
We also switch from the previous four-number version to a proper SemVer: MAJOR.MINOR.PATCH.
Not only SemVer is the more standard versioning scheme, but it also
happens to work better for logging, because groups of four
dot-separated numbers are stripped out from ChromeOS logs by
anonymizer tools.
> Release Connector 1.4.0

- third_party/pcsc-lite/naclport/server_clients_management/src/clients_manager.cc
When shutting down clients, we've always been printing zero, instead of the real number of clients. This change fixes this minor logging glitch.
> [logging] Fix wrong number in the clients_manager log

- smart_card_connector_app/src/application_unittest.cc
Duplicate the existing tests for SCardGetStatusChange() in the card insertion/removal scenarios, with introducing a variant of these tests that delays the card insertion/removal by some (hardcoded) interval.
This adds test coverage for some internal implementation codepaths, because the previously existing tests were only triggering events that are immediately discovered by SCardGetStatusChange before it enters the polling loop, and before it starts relying on asynchronous USB notifications from the reader (via interrupt USB transfers).
> [PC/SC test] Test delayed card events with GetStatusChange

- third_party/ccid/patches/0006-Fix-polling-transfer-restart-after-InterruptStop.patch
- third_party/ccid/src/src/ccid_usb.c
Cherry-pick the fix we landed into the upstream CCID repository (sadly, for the regression that we introduced previously there).
This fixes the polling_transfer functionality to continue working correctly after a card has been connected and disconnected once. The bug was that the polling_transfer was immediately canceled in such case, leading to the driver falling back to an active polling of the reader every 400ms instead of passive reading transfers that are restarted only every 10 minutes. On ChromeOS, this suboptimal behavior, combined with the fact that we make a new infinitely-timed chrome.usb API call for every transfer, led to the system resource exhaustion after a few hours and some other race conditions. (On non-ChromeOS platforms, the bug was less severe as the real Libusb …
> [ccid] Cherry-pick upstream fix for excessive polling

- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/usb_transfers_parameters_storage.cc
- third_party/libusb/webport/src/usb_transfers_parameters_storage.h
When choosing which of active Libusb transfers should receive a reply from the JS API, use the FIFO order rather than a random order. Also change the internal structures so that FIFO is used uniformly, which we'll use in follow-ups for correctly enqueueing JS API calls.
The FIFO order is more intuitive and better corresponds to Libusb behavior on other platforms. Moreover, the FIFO property will be crucial to avoid the situation when an enqueued JS API call is discarded because the transfer happened to be resolved by the call originally triggered by a different transfer.
This contributes to #462 and #1104.
> [libusb] Handle transfers in FIFO

- docs/updating-ccid.md
- docs/updating-pcsc-lite.md
Ludovic Rousseau's blog moved from blogspot.com to apdu.fr See https://blog.apdu.fr/posts/2023/05/blog-moved-to-httpsblogapdufr/
> Update blog URL in updating-pcsc-lite.md

- common/make/internal/executable_building_emscripten.mk
Set the stack size to 1 MiB in both Debug and Release modes.
Previously we were doing this only in Debug, and left the default 64 KiB otherwise, but with recent changes it turned out that we're besides this (tough) limit. In the future we might want to investigate whether something smaller than 1 MiB would make sense, however for now WebAssembly builds aren't shipped anywhere, and we just want to make the CI bots happy on follow-up changes.
This change contributes to #1104.
> [wasm] Increase default stack size in Release

- common/cpp/src/public/requesting/remote_call_adaptor.cc
- common/cpp/src/public/requesting/remote_call_adaptor.h
- common/cpp/src/public/requesting/remote_call_async_request.h
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/libusb_opaque_types.h
- third_party/libusb/webport/src/usb_transfers_parameters_storage.cc
- third_party/libusb/webport/src/usb_transfers_parameters_storage.h
Don't make new chrome.usb/WebUSB API calls in case there're already running equivalent ones (for input transfers).
Besides consuming Chrome resources, these extra calls were reportedly leading to hitting the OS kernel limits on the number of active transfers, which completely broke the USB communication in some cases.
This fixes #1104.
> [libusb] Avoid duplicate USB transfers

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-integrationtest.js
- smart_card_connector_app/src/chrome-api-jstocxxtest.js
- smart_card_connector_app/src/pcsc-api-jstocxxtest.js
Make the code in test cases' tearDown functions resistant to failures in setUps. This avoids spurious errors like "reading the dispose property of a null object" after the real test failures.
This commit is a no-op for the successfully built tree, it's only intended to improve troubleshooting of test failures.
> [JS-to-C++ tests] Bulletproof teardowns

- common/js/src/popup-window/popup-opener.js
Fix the PopupOpener.runModalDialog() function to correctly pass the optional window parameters.
They were ignored (this regressed in #518). One noticeable example was incorrect width of the PIN prompt in the example applications. Tracking issue #1126.
> [ui] Fix options passing in runModalDialog

- common/make/internal/executable_building_emscripten.mk
Emscripten's TOTAL_STACK parameter got renamed to
STACK_SIZE a while ago:
https://github.com/emscripten-core/emscripten/commit/e41f71699606d569970ad3501da8c53239468f3b
> Use STACK_SIZE Emscripten setting

- common/cpp/src/public/value_test_utils.h
- smart_card_connector_app/src/application_unittest.cc
- third_party/googletest/webport/src/polyfill_nacl.h
Add a test for repeating cycles of card insertion and removal.
Besides checking one of the basic scenarios of SCardGetStatusChange(), this also verifies that quickly succeeding reader init/deinit events don't lead to internal breakages. Specifically, this test has been used to find a racy use-after-free in the Libusb subsystem: #1098.
> [PC/SC test] Test repeated card insert/remove

- common/js/src/random.js
- smart_card_connector_app/src/background.js
Switch a couple of places that use the "window" object to use "globalThis" instead. The latter is a better equivalent because it works in Manifest V3 Service Workers as well (in a Service Worker, "self" should be used instead of "window"; "globalThis" is an alias to either of those).
This contributes to the effort tracked by #1129.
> [mv3] Use globalThis instead of window

- env/initialize.sh
Google changed the Chromedriver download domain to "storage.googleapis.com".
> [chromedriver] Update chromedriver download URL

- smart_card_connector_app/src/manifest.json.template
When built in the (currently experimental) PACKAGING=extension mode, Smart Card Connector's manifest.json will now use manifest_version=3.
The other parts of the file were edited in accordance to backwards-incompatible manifest format changes.
This patch contributes to the effort tracked by #1129.
> [mv3] Switch Connector's extension manifest to v3

- common/js/src/popup-window/popup-opener.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker-unittest.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/policy-or-prompting-permissions-checker.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js
A permissions prompting dialog should be automatically closed and the permissions check resolved if the managed storage gets updated with the relevant policy value while waiting for a response from the user.
> Resolve permissions check when managed policy gets updated

- common/js/src/executable-module/emscripten-module.js
- common/js/src/messaging/common.js
- common/js/src/object-helpers.js
- example_cpp_smart_card_client_app/src/background.js
- example_cpp_smart_card_client_app/src/built_in_pin_dialog/built-in-pin-dialog-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- smart_card_connector_app/src/chrome-api-provider.js
- third_party/libusb/webport/src/libusb-proxy-receiver.js
- third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/managed-registry.js
Add missing goog.require() declarations for symbols used in the file.
Sadly, such missing declarations aren't auto-detected by the Closure Compiler, but still lead to compilation errors when the inclusion order changes. This commit fixes some of manually spotted ones (detected via manual inspection and helper Shell scripts).
> Fix some undeclared JS deps

- .eslintrc.yml
- scripts/eslint.py
Set the ESLINT_USE_FLAT_CONFIG=false environment variable when running ESLint. This is to workaround the following errors after ESLint got updated to 9.0.0:
```
Invalid option '--resolve-plugins-relative-to' - perhaps you meant '--ignore-pattern'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
```
Also disable the `no-floating-promise` plugin since it starts
failing with the following error in ESLint 9.0.0:
```
TypeError: context.getScope is not a function
```
> [eslint] Workaround for 9.0.0 update

- third_party/ccid/patches/0003-Add-AvidCard-CAC-Smart-Card-Reader.patch
- third_party/ccid/src/readers/AvidCard_AvidCardCAC_A.txt
- third_party/ccid/src/readers/supported_readers.txt
Apply upstream's recent patch that adds support of the following reader:
AvidCard CAC Smart Card Reader (idVendor=0x04E6 idProduct=0x5824)
Note: this patch can be dropped later, once we update to a new CCID Driver's release that includes this change.
> [ccid] Cherry-pick patch for AvidCard CAC reader

- third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json
Use the up-to-date name when displaying prompts about connections from the DriveLock extension (the old title was "Charismathics").
> Rename DriveLock extension in trusted clients

- .github/workflows/makefile.yml
- make-all.sh
Change the helper scripts (make-all.sh, test-all.sh) and the Github Continuous Integration config to build in the "PACKAGING=extension" variant. We enable this only for the "TOOLCHAIN=emscripten" case.
> [mv3] Change scripts and CI to include extension

- common/js_test_runner/run-js-tests.py
This is to fix flaky errors we observe on the bots:
selenium.common.exceptions.TimeoutException: Message: timeout:
Timed out receiving message from renderer: 300.000
The commit bumps this from 300 seconds to 600 seconds.
This fixes #1151.
> [ci] Increase Webdriver page_load_timeout

- common/js/src/container-helpers-unittest.js
- common/js/src/container-helpers.js
- common/js/src/messaging/port-message-channel.js
- common/js/src/messaging/single-message-based-channel.js
- third_party/libusb/webport/src/libusb-proxy-data-model.js
- third_party/libusb/webport/src/libusb-to-webusb-adaptor.js
Perform data massaging when handling USB requests, so that they can be sent through message pipes. WebUSB uses ArrayBuffer and DataView types for input/output parameters, however for sending via extension messages we have to convert them to/from arrays of integers-bytes.
The underlying motivation is the migration to manifest v3 and WebAssembly, because due to multi-threading issues we have to move the WebAssembly module from the Service Worker (where most API calls, including WebUSB APIs will happen) into a separate Offscreen Document. So each USB request will have to be proxied as a request-response pair of messages between the Offscreen Document and the Service Worker.
> [libusb] Support proxying through message channels

- common/js/src/messaging/port-message-channel-waiter-unittest.js
- common/js/src/messaging/port-message-channel-waiter.js
- common/js/src/messaging/port-message-channel.js
This abstracts away the logic of waiting for a particularly-named chrome.runtime.onConnect event.
This helper will be useful for the mv3 code since all communication between extension's pages (Service Worker, Browser Action, popup windows, Offscreen Document) will need to be switched to message ports.
> Helper for waiting for incoming Port connection

- smart_card_connector_app/src/background.js
The Smart Card Connector's background script doesn't currently need to listen for chrome.runtime.onConnect events.
In the past it was needed for wiring up PC/SC calls that happen within the application (namely, from the ReaderTracker class), but they were later migrated to directly send messages to the executable module's channel.
This cleanup is useful in the context of manifestv3 migration, since we'll need to open and listen for a bunch of message pipes in various places, and this old code would've thrown asserts for them.
> Delete unneeded chrome.runtime.onConnect listener

- common/js/src/executable-module/emscripten-module.js
- common/js/src/messaging/delayed-message-channel-unittest.js
- common/js/src/messaging/delayed-message-channel.js
Move the logic of delayed message sending out from emscripten-module.js into a separate helper class.
This lets us reuse it in other places, namely for the communication with the Offscreen Document that's currently being implemented for manifestv3. Also this extracted code can be covered with unit tests now.
> Refactor out DelayedMessageChannel

- common/js/src/executable-module/emscripten-in-offscreen-doc-main-script.js
- common/js/src/executable-module/emscripten-module.js
- common/js/src/executable-module/emscripten-offscreen-doc.html
- common/js/src/executable-module/offscreen-doc-emscripten-module.js
- smart_card_connector_app/build/Makefile
- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/manifest.json.template
When built in the Emscripten+Extension mode, run the Emscripten module in the Offscreen Document instead of the Service Worker.
This is needed because multi-threaded Emscripten modules require creating Workers, which Chrome doesn't currently support from Service Workers - see https://crbug.com/40772041. Hence this commit moves the module into a separate Offscreen Document which doesn't have this limitation. The rest of the background logic remains in the Service Worker because Offscreen Documents have their own strict limitations (most importantly, only chrome.runtime APIs are exposed to them).
> [mv3] Put Wasm module into Offscreen Document

- common/js/src/executable-module/offscreen-doc-emscripten-module.js
Create the waiter for the messaging channel before opening the Offscreen Document, so that we don't miss the chrome.runtime.onConnect event.
> [mv3] Fix messages to Emscripten in Offscreen Doc

- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/application_unittest.cc
- smart_card_connector_app/src/testing_smart_card_simulation.cc
- smart_card_connector_app/src/testing_smart_card_simulation.h
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy.h
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
- third_party/libusb/webport/src/public/constants.h
- third_party/libusb/webport/src/public/libusb_web_port_service.cc
- third_party/libusb/webport/src/public/libusb_web_port_service.h
- third_party/pcsc-lite/naclport/server/build/Makefile
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.h
- third_party/pcsc-lite/naclport/server/src/readerfactory_webport.cc
Change the init retry mechanism to be triggered on any reader initialization error, as opposed to only doing it on openDevice/claimInterface errors. Additionally, attempt resetting the USB device after a few unsuccessful retries.
This should fix occasional flaky errors we see in the field, when there's a temporary conflict between the in-session and the login-screen instances of Smart Card Connector, which may cause failures at various USB functions and accidentally receiving a reply for a request sent by a different extension ("Invalid frame detected").
> [pcsc] Retry init on more errors, try USB reset

- common/js/src/messaging/port-message-channel.js
- common/js/src/popup-window/in-popup-main-script.js
- common/js/src/popup-window/popup-constants.js
- common/js/src/popup-window/popup-opener.js
- example_js_smart_card_client_app/src/pin-dialog/pin-dialog-server.js
This adds support of manifest v3 to the "popup-window" helpers. This is achieved by reimplementing the popup==>background page communication using message ports.
Previously, we used two other mechanisms for this communication:
* in the Chrome App build mode we injected callbacks into the popup's global state using the chrome.app.window.create() callback.
* in the Chrome manifest v2 Extension build mode we used "setSelfAsOpener" to let the popup call global functions in the opener page itself.
Neither works in manifest v3 Extensions, hence this commit implements a new approach that should work in all build modes.
> [mv3] Support popup windows - via message channels

- common/js/src/executable-module/offscreen-doc-emscripten-module.js
- common/js/src/messaging/message-waiter-unittest.js
- common/js/src/messaging/message-waiter.js
Create a small library function for for waiting on a specific incoming message. Cover it with unit tests.
This code will be reused for implementing the communication with popup dialogs in the manifest v3 mode.
> Refactor message awaiting

- prepare-binaries-for-github-release.py
The prepare-binaries-for-github-release.py script should now use the "extension_emscripten" files, because we stopped compiling the "app_emscripten" variant.
This was forgotten in
https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/pull/1140.
> Fix paths used when preparing Github release files

- common/js/src/messaging/message-channel-pinging.js
Consider a message channel dead only after 10 min of silence, regardless of Debug or Release build mode.
This should fix the observed rare event in Debug build, when communication between client extensions and Smart Card Connector was considered dead despite the pages staying alive seemingly. This problem is especially disruptive in the manifest v3 extension build mode, since closing message ports can lead to the termination of service workers.
> Increase dead message channel timeout

- .github/actions/build-dependencies-installation/action.yml
This changes the Python 3 version used in Continuous Integration
in Github Actions.
The 3.12 version end-of-life is more than 4 years from now, unlike
3.9 which had only about a year left.
> [ci] Bump Python to 3.12

- common/make/internal/executable_building_emscripten.mk
Emscripten's DEMANGLE_SUPPORT option got deprecated and became no-op in 3.1.54
(https://github.com/emscripten-core/emscripten/commit/971e903181da8ce09b3a9c17c284f692b392f9ae).
> [wasm] Drop the legacy DEMANGLE_SUPPORT option

- common/make/internal/executable_building_emscripten.mk
- env/constants.sh
The commit bumps the dependency.
It also adds the `EXPORTED_RUNTIME_METHODS` flag as Emscripten >=3.1.59 requires that (specifically, our code has been using the `Module.PThread.terminateAllThreads()` symbol).
> [wasm] Update Emscripten to 3.1.61

- .eslintrc.yml
This plugin has been fixed upstream to be compatible with ESLint 9.0.
Hence we can partially revert #1144 to reenable it as part of our lint checks.
> [eslint] Reenable no-floating-promise

- example_cpp_smart_card_client_app/build/Makefile
- example_cpp_smart_card_client_app/src/background.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- example_cpp_smart_card_client_app/src/manifest.json
- smart_card_connector_app/build/Makefile
Similarly to #1141 and #1160, we move the
example_cpp_smart_card_client_app's Emscripten module into an Offscreen Document when building in the PACKAGING=extension mode. The goal is to allow the WebAssembly module create background threads despite the manifest v3 restrictions.
> [example] Put Emscripten module into offscreen doc

- .github/actions/build-dependencies-installation/action.yml
Update the dependency that's used in our Continuous Integration script based on Github Actions.
This is to fix the following warnings:
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/setup-python@v4.
> [ci] Bump actions/setup-python to v5

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.h
- example_cpp_smart_card_client_app/src/manifest.json
Add the C++ definitions for the RSA-PSS family of signature algorithms into the example_cpp_smart_card_client_app.
These algorithms have been supported by the Chrome Extensions API since version 89. We put the same minimum_chrome_version into the example manifest.json, because this has been long enough to not care about supporting older clients.
> [example] Add RSA-PSS algorithms

- example_cpp_smart_card_client_app/src/background.js
- example_cpp_smart_card_client_app/src/manifest.json
Change the manifest to use the manifest v3 format of Chrome Extensions. Also fix some Apps-specific code to work as mv3 Extensions.
> [example] Switch to manifest v3 extension

- common/js/src/logging/log-buffer.js
- common/js/src/logging/logging.js
Use message passing for sending logs to the Service Worker (or the Background Page, when compiled for mv2 Apps) from all other pages of the extension.
This replaces the mv2-specific mechanism that collected all logs by directly accessing the background page's LogBuffer variable. This mechanism was a bit hacky, but had the benefit of being synchronous and zero-overhead; it's not viable in mv3 Service Workers so has to be deleted.
> [mv3] Collect logs from all pages via messaging

- common/js/src/logging/logging.js
Make the Service Worker / Background Page responsible for calling chrome.systemLog API with every log message.
Before this commit, every page made its own chrome.systemLog API calls for every of its own logs. However, this doesn't work with mv3 Offscreen Documents, as chrome.systemLog API isn't exposed to them.
> [mv3] Pass received logs to systemLog

- common/js/src/clipboard.js
- common/js/src/logging/log-buffer.js
- common/js/src/logging/logging.js
- smart_card_connector_app/src/window-logs-exporting.js
Make the log export UI mv3-compatible, by switching it from directly inspecting the background page's log buffer to using message passing.
> [mv3] Support logs export

- common/make/internal/executable_building_emscripten.mk
This seems to be the smallest power-of-two that's compatible with PC/SC-Lite and
CCID, since they require at least 256 KB plus some small amount needed by
Emscripten internally, and Emscripten doesn't allow the size to be dynamically
increased beyond the limit.
> [wasm] Reduce the stack limit to 512 KiB

- smart_card_connector_app/src/manifest.json.template
As we're switching to WebAssembly, adjust the minimum supported ChromeOS
version accordingly.
While in theory >=109 should be the greatest common denominator for both
the Chrome App build as well as Chrome mv3 Extension build, we haven't done
thorough tests on each of those versions, and given the active development
and bugfixing of the WebAssembly technology it'd be unwise to roll out our
wasm-based version to them. Hence we choose the threshold conservatively,
as the ChromeOS Stable version as of the time of writing this.
> [connector] Require ChromeOS 128 or later

- third_party/closure-compiler-binary/README.google
We don't expect any specific improvement, but upstream fixed a few bugs.
> [js] Update Closure Compiler to 20240317

- third_party/ccid/webport/build/Makefile
- third_party/pcsc-lite/naclport/server/build/Makefile
Move the compilation of these two mini-libraries from the CCID Driver to PC/SC-Lite.
Unlike in the upstream *nix implementation where both CCID and PC/SC-Lite ship with their own version of these mini-libraries, we have to choose one of the copies since we link everything into a single WebAssembly executable. Previously we semi-aribtrarily chose to put the compilation and linking into the CCID Driver's makefile, however this doesn't work out nicely with the plan to add more drivers. Our PC/SC-Lite Makefile is a better place for a shared thing like this.
> [pcsc] Compile simclist, tokenparser with PC/SC

- common/make/internal/executable_building_emscripten.mk
- env/constants.sh
Starting from this version, Emscripten stopped generating `.worker.js`
files - our build scripts had to be changed accordingly.
> [wasm] Update Emscripten to 3.1.68

- common/cpp_unit_test_runner/src/build_emscripten.mk
Like this: GTEST_ARGS="--gtest_filter=*Foo" make test
This is something we already supported in the "analysis" builds (e.g., TOOLCHAIN=asan_testing), so this commit just expands this to another build configuration. Note that JS-based tests, including JS-to-C++ tests, don't use GTest and ignore this parameter.
> [wasm] Allow passing GTest filter via command line

- third_party/pcsc-lite/naclport/build_configuration/Makefile
Change the "build_configuration" target's makefile to only look at the files tracked in Git, instead of looking at all files and folders.
The current behavior was subject for unrelated changes (e.g., when a temporary file is created by some other build step) that were triggering unnecessary rebuilds.
> [pcsc] Fix unnecessary build_configuration rebuild

- third_party/ccid/webport/build/Makefile
Append "CCID_" to all names of the IFDH functions in the CCID driver.
This is preparation for us introducing another driver, to avoid symbol clashes: every PC/SC-Lite driver exports the same set of IFDH functions, and we link everything statically in our webport (unlike it's done with separate .so libraries on *nix systems).
> [ccid] Rename all exported IFDH functions

- smart_card_connector_app/src/application.cc
- third_party/ccid/webport/build/Makefile
- third_party/ccid/webport/src/ccid_pcsc_driver_adaptor.cc
- third_party/ccid/webport/src/ccid_pcsc_driver_adaptor.h
- third_party/pcsc-lite/naclport/driver_interface/src/pcsc_driver_adaptor.h
- third_party/pcsc-lite/naclport/server/src/dyn_webport.cc
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.h
Add an abstraction that represents a driver, and change PC/SC-Lite to call it instead of directly referencing CCID's functions.
This is a refactoring that prepares us for introducing multiple drivers in the application. Note that on *nix PC/SC-Lite achieves the same by dynamically loading each driver's .so file - something we cannot do in the webport.
> [pcsc] Let drivers export their methods themselves

- smart_card_connector_app/build/Makefile
- smart_card_connector_app/build/executable_module/Makefile
- smart_card_connector_app/build/executable_module/cpp_unittests/Makefile
- smart_card_connector_app/build/js_to_cxx_tests/Makefile
- third_party/ccid/webport/build/Makefile
- third_party/ccid/webport/include.mk
- third_party/ccid/webport/src/ccid_pcsc_driver_adaptor.cc
- third_party/pcsc-lite/naclport/common/include.mk
- third_party/pcsc-lite/naclport/server/build/Makefile
- third_party/pcsc-lite/naclport/server/src/public/pcsc_lite_server_web_port_service.cc
Make single central constants for the PC/SC-Lite's driver installation directory and for the CCID config/.so installation paths.
This refactoring gets rid of multiple places in which these constants were previously hardcoded in various variations.
> [pcsc,ccid] Pass install paths from makefiles

- Makefile
- third_party/ccid/webport/build/Makefile
- third_party/driver-hid5021/webport/build/.gitignore
- third_party/driver-hid5021/webport/build/Makefile
Add a Makefile that compiles the HID 5021 CL driver's original Linux source code.
Note that the driver still isn't used in the Smart Card Connector for real, since it's not linked into the resulting executable and there's no C++ glue code yet.
> [hid5021] Compile driver's C sources

- common/cpp/src/public/ipc_emulation.cc
- common/make/internal/executable_building_analysis.mk
- common/make/internal/executable_building_emscripten.mk
- third_party/libusb/webport/build/tests/Makefile
Now that we stopped using the legacy NaCl toolchain, we can switch from
C++11 to more recent versions.
The commit enables C++20, since despite C++23 being already supported by
Emscripten we can't easily use it for ASan&coverage builds: CI bots still use
Ubuntu 22.04, and also typical developer machines still have an old Clang as
well.
> [c++] Switch to C++20

- smart_card_connector_app/build/executable_module/Makefile
- smart_card_connector_app/build/executable_module/cpp_unittests/Makefile
- smart_card_connector_app/build/js_to_cxx_tests/Makefile
- third_party/driver-hid5021/webport/include.mk
Package the HID 5021 CL driver's config file into the Smart Card Connector extension, as well as into the test targets.
> [hid5021] Install Info.plist config file

- common/make/internal/executable_building_emscripten.mk
Explicitly pass -s IGNORE_MISSING_MAIN=1 to Emscripten: apparently, this flag defaults to 0 when compiling in -sSTRICT.
Our production code doesn't have a main() function since the JS code calls us via Embind instead.
> [wasm] Specify IGNORE_MISSING_MAIN

- smart_card_connector_app/build/executable_module/Makefile
- smart_card_connector_app/build/executable_module/cpp_unittests/Makefile
- smart_card_connector_app/build/js_to_cxx_tests/Makefile
- smart_card_connector_app/src/application.cc
- smart_card_connector_app/src/manifest.json.template
Link the driver into Smart Card Connector's executable and instantiate the "adaptor" code to let our PC/SC-Lite webport actually make commands to it.
> [hid5021] Wire up the driver

- third_party/driver-hid5021/webport/build/Makefile
The SO_INSTALLATION_PATH constant wasn't passed correctly because the driver's makefile didn't include the corresponding include.mk.
> [hid5021] Fix the missing .mk include

- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_js_proxy_constants.cc
- third_party/libusb/webport/src/libusb_js_proxy_constants.h
- third_party/libusb/webport/src/libusb_js_proxy_unittest.cc
- third_party/libusb/webport/src/libusb_opaque_types.cc
Fix our webport of Libusb to report LIBUSB_ERROR_TIMEOUT instead of LIBUSB_TRANSFER_OTHER when a transfer times out.
This hasn't been critical for our existing usages so far (the CCID Driver doesn't really distinguish the timeout error from other errors), but the correct error code makes reading logs easier, and also the new drivers might want to check for this error code directly.
This fixes #47 (the 7-year-old TODO!).
> [libusb] Correct error code for timed out transfer

- common/cpp/src/public/requesting/async_request_unittest.cc
- third_party/libusb/webport/src/libusb_js_proxy.cc
- third_party/libusb/webport/src/libusb_opaque_types.cc
- third_party/libusb/webport/src/libusb_opaque_types.h
- third_party/libusb/webport/src/usb_transfers_parameters_storage.cc
- third_party/libusb/webport/src/usb_transfers_parameters_storage.h
- third_party/pcsc-lite/webport/server/src/winscard_msg_webport.cc
std::chrono::high_resolution_clock can, according to the Standard, be non-steady, i.e., non-monotonic, which isn't valid for our use cases when we measure operation timeouts.
In reality this is a pure cosmetic change now, given that Emscripten's C++ standard library defines high_resolution_clock as a steady_clock.
> [c++] Use steady_clock instead of high_resolution

- env/constants.sh
This brings long-awaited fixes for -sINCOMING_MODULE_JS_API and -sSTRICT.
> [wasm] Update Emscripten to 3.1.71

- .github/workflows/makefile.yml
This rule is unmaintained and deprecated.
The visible effect of this commit is that different artifacts are now packed together into combined .zip files, e.g., `built_app_packages.Release.extension.zip` will contain `smart_card_connector_app.zip`, `example_js_smart_card_client_app.zip` and `example_cpp_smart_card_client_app.zip`. This adds a bit of inconvenience but is no more than a cosmetic change.
> [ci] Stop using ittaakos/upload-artifact-as-is

- common/make/internal/executable_building_emscripten.mk
This Emscripten command-line parameter allows to optimize away Emscripten library code that isn't needed for a concrete application.
We couldn't use this parameter previously because of https://github.com/emscripten-core/emscripten/issues/20457, https://github.com/emscripten-core/emscripten/issues/21167 - both are resolved in Emscripten 3.1.71.
This fixes #1124.
> [wasm] Reenable INCOMING_MODULE_JS_API

- common/make/internal/executable_building_emscripten.mk
This stricter (and more well-optimized) compilation mode is finally working - 
#1237, #1236 were the remaining bits.
> [wasm] Use Emscripten -sSTRICT

- .github/workflows/makefile.yml
Hardcode the CI script to use ubuntu-24.04 instead of "latest".
The main goal is to freeze the known-to-be-compatible version to
make the CI work correctly for a longer time without manual
intervention. Additionally, we switch to a more modern version
proactively ("latest" is still at 22.04).
> [ci] Switch to ubuntu-24.04

- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/api_bridge.h
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/bridge-backend.js
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.cc
- example_cpp_smart_card_client_app/src/chrome_certificate_provider/types.h
Delete the compatibility code for ChromeOS <=85 from the Example C++ App.
On newer ChromeOS versions, the deleted code was a no-op.
Specifically, a new set of events and functions were added to
chrome.certificateProvider API in ChromeOS 86. Older definitions remained
but it's been preferred to switch away from them; moreover, MV3
extensions can only access new symbols.
We expect that all vendors who use this example have been requiring
"minimum_chrome_version: 86" or higher in manifest.json.
> [example] Drop legacy certificateProvider code

- example_cpp_smart_card_client_app/src/background.js
- third_party/pcsc-lite/webport/cpp_client/src/wasm-client-backend.js
Another remnant of NaCl in the file and class name. This code is still used in WebAssembly builds.
> [nacl] Rename PC/SC-Lite client backend

- smart_card_connector_app/src/manifest.json.template
Current ChromeOS LTS is 126, so use this as a requirement instead of the previously chosen 128.
This means we'll need to do backwards compatibility check for two more releases into the past.
> [connector] Reduce ChromeOS requirement to 126

- scripts/internal/find_files_for_linting.py
We don't want to run linters or formatters on the third-party code for the driver.
We still want them on our "glue" code, hence we only exclude the /src/ subdirectory.
> [hid5021] Exclude 3p code from linting

- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/window-constants.js
- smart_card_connector_app/src/window-devices-displaying.js
This replaces the approach based on injecting functions from the background page into window: this isn't compatible with MV3.
The implementation is actually simpler as well.
> [mv3] Send device list to window via messages

- .github/workflows/makefile.yml
Before this commit, the artifact was named "coverage-report-detailed.zip.zip".
> [ci] Drop the double .zip in coverage report

- .github/workflows/makefile.yml
The previous commit #1244 only applied to Emscripten builds; now do the same for all other jobs as well.
We had to update libstdc++ from 12 to 13 as well.
> [ci] Complete "Switch to ubuntu-24.04"

- smart_card_connector_app/src/window-main.js
Don't display an "x" ("delete") button in Smart Card Connector's UI when built in MV3 extension mode.
An extension's browser action popup is easy to close by clicking elsewhere, so the button is of very little use.
> [mv3] Delete the close button from the popup

- smart_card_connector_app/src/background.js
- smart_card_connector_app/src/window-constants.js
- smart_card_connector_app/src/window-status-displaying.js
This replaces the approach based on injecting functions from the background page into window: this isn't compatible with MV3.
> [mv3] Send crash event to window via messages

- smart_card_connector_app/src/manifest.json.template
This for a beta release on M139.
Soon, this should be updated back to M138.
> Update minimum Chrome version

- smart_card_connector_app/src/chrome-api-provider.js
Due to changes introduced by migration to extension, the returned binary data type changed from `ArrayBufer` to `Uint8Array`, which does not align with the type that Chrome expects.
This is essentially the same as
https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/pull/1274
Also, added a `try`-`catch` so that such problems do not cause silent crashes.
> Chrome API provider: Use ArrayBuffer type for ATR

- smart_card_connector_app/src/background.js
Remove an update listener where it was registered, not somewhere else.
This was causing a crash when opening the UI another time, since it caused a message to be
sent over the old updater that was no longer valid.
> Fix crash when reopening UI
